### ISSUE TITLE
how to keep tsserver running after file exit?

### ISSUE THREAD

**Issue by eleith** [neoclide/coc-tsserver#100]
when i open a typescript file, the tsserver background process is started and i have to wait for this process to be ready before type information  / auto completion is available. 

when i exit the file, the tsserver background process is killed. when i open the next file in the same typescript project, there is the same delay before type information / auto completion is available since the tsserver background process is starting up again.

is their a way to configure different behavior to to reduce the time before type information / auto completion is available?

**Comment by chemzqm** [comment]
Tsserver won't exit unless you exit vim.

**Comment by eleith** [comment]
i've been opening files across tabs in tmux, so that is where i ended up exiting vim.

i think to avoid exiting vim, i would need to adopt a new workflow like using vim tabs as opposed to tmux tabs.

is their a command or alternative suggestion where the user would have more control over starting/stopping tsserver?

**Comment by chemzqm** [comment]
No hope, you should keep vim running

**Comment by eleith** [comment]
good to know. 

a vim tab/buffer workflow is essential to working with the eslint/tsserver coc plugins.

thanks for the great plugins. there is quite a bit of learning / configuring to get it set up, but it pays off in the long run.
