### ISSUE TITLE
Report wrong type for Promise.all()

### ISSUE THREAD

**Issue by toancaro** [neoclide/coc-tsserver#101]
As in the screenshot, the `number1` type must be `number`, but its type is reported as `number | undefined`.  

This issue seems only happens when 1 item in the array that passed to `Promise.all()` resolved to `undefined`. Type of `number3` is correctly set as `number`.

![Screen Shot 2019-11-26 at 16 47 28](https://user-images.githubusercontent.com/3683223/69618720-ef912280-106c-11ea-80e9-83d65a7d4c2d.png)

This is my `tsconfig.json`:

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "lib": ["es2015", "dom"],
    "strict": true,
    "esModuleInterop": true
  }
}
```

**Comment by fannheyward** [comment]
Reproduced.

VSCode 1.40.1 reports as `number`, YES.
cos-tsserver with TS 3.6.4 reports as `number`, YES.
coc-tsserver with TS 3.7.2 reports as `number | undefined`, NO.
coc-tsserver with TS 3.7.2, and `"strictNullChecks": false`, reports as `number`, YES.

**Comment by chemzqm** [comment]
You can use `as [number, number | undefined]` when tsserver failed to retrieve type for you

**Comment by toancaro** [comment]
Thanks for your responeses.

Our project use that type of code a lot so I think adding `as [number, number | undefined]` might not be the best solution. Because it would make unnecessary completed code for my other team members who are using VSCode.

I have read the [configuration options](https://github.com/neoclide/coc-tsserver#configuration-options) but unfortunately I still dont know how to use the specific version of typescript. Could would please show me how to do that?

**Comment by chemzqm** [comment]
It's limitation or bug of your tsserver, we can't do anything else.
