### ISSUE TITLE
Type checking gets stuck

### ISSUE THREAD

**Issue by strathausen** [neoclide/coc-tsserver#102]
Hi there,

I'm not sure this is the right place to post the bug.

Sometimes type checking gets stuck when editing a typescript file. I've recorded the behaviour:
https://asciinema.org/a/E3dDjlnTXlR2LiW0grnoYCv7t

In the video, I added a function call to an non-existing function for demonstration purpose. However, when I do `cs''` on a string (using the surround vim plugin), type errors get displayed again.

Cheers!

Philipp

**Comment by chemzqm** [comment]
Can't see any problem with your screen shot, no idea why you gets stuck. Checkout https://github.com/neoclide/coc.nvim/wiki/F.A.Q#how-could-i-profile-vim

**Comment by strathausen** [comment]
Yeah it's weird. I don't want to always go and type `cs''` in the first line in order to see whether I have any type issues.

So for now, I configured coc to check types while typing (in insert mode) which works fine for me but I'd prefer it to check only when I'm done typing.

Thanks for the link! I'll check it out. Maybe I can force coc to type check whenever I leave insert mode? So far I only found `:CocRestart` but it's a bit of an overkill.

**Comment by chemzqm** [comment]
> but I'd prefer it to check only when I'm done typing.

It's not possible with language server, you can configure coc.nvim not update diagnostics on insert mode which is default.

**Comment by chemzqm** [comment]
You have to profile your vim to know what cause your vim slow.

**Comment by strathausen** [comment]
No, actually my vim is not slow at all. The type checking is really stuck until I need to "kick it off" by editing the quotations marks.

I'll try the profiling sometime. Meanwhile, the updating type checks on insert mode works fine for me! I'll get back once I have more info.
