### ISSUE TITLE
Auto import + completion confirmation succeds but editor.action.organizeImport doesn't

### ISSUE THREAD

**Issue by mvrozanti** [neoclide/coc-tsserver#104]
Calling `:CocCommand editor.action.organizeImport` doesn't work, even though if I start to write a class name, the import line is added after `C-y` is pressed.

I should mention this is happening on typescript files. I feel like this is such little information, but I have no idea what I'm looking for.

**Comment by chemzqm** [comment]
It works as expected for me.
