### ISSUE TITLE
First file that opens generates false positives in linting

### ISSUE THREAD

**Issue by snaveevans** [neoclide/coc-tsserver#105]
Running a typescript react project with coc.nvim and this extension.  I appear to be encountering some odd issues and any direction would be very appreciated.
This project contains server code (c#) and client code `ts` & `tsx`.  I get lots of false positives, saying my file is riddled with errors, when I open a `tsx` file first, instead of a `ts` file.  The linting errors are saying it's coming from `tsserver`.

Opened first:
![Screen Shot 2019-12-05 at 8 08 39 AM](https://user-images.githubusercontent.com/3487777/70248817-bb86c300-1738-11ea-87eb-1cd8f42085fc.png)
Opened second:
![Screen Shot 2019-12-05 at 8 09 00 AM](https://user-images.githubusercontent.com/3487777/70248837-c3defe00-1738-11ea-89f7-1e83386643fd.png)

Logs:
https://gist.github.com/snaveevans/42ee89982901a875b556df1a5b744028

vimrc:
https://github.com/snaveevans/dotfiles/blob/master/.vimrc

**Comment by chemzqm** [comment]
Try start your vim inside ClientApp folder to have correct workspaceFolder, checkout ClientApp

**Comment by ozeidan** [comment]
I have similar issues. My workspaceFolder is correct.

**Comment by gquittet** [comment]
I have the same issue. I need to `:e` in the file to fix the false positives.
Is it possible to fix it? :) It's annoying.

**Comment by gquittet** [comment]
If you need any help to fix this bug, I'm a software developer so, I can help.

**Comment by chemzqm** [comment]
@gquittet Need a repo to reproduce the bug.

**Comment by snaveevans** [comment]
This is the repo I've been generating the issue on, I'm actually experiencing a very similar issue with a vue project that uses typescript.  https://github.com/honey-dos/web

**Comment by chemzqm** [comment]
@snaveevans I don't have issue with that repo, try start your nvim in folder `HoneyDo.Web/ClientApp`

**Comment by snaveevans** [comment]
Still getting the issue after opening `HoneyDo.Web/ClientApp`.  I'm also able to replicate the issue with using stenciljs' "starter app" https://github.com/ionic-team/stencil-app-starter.  I've removed all vim plugins except `coc.nvim` and I still get the issue, I've even tried removing all `coc.nvim` plugins except `coc-tsserver`.  When I remove `coc-tsserver` the errors go away.

**Comment by snaveevans** [comment]
Fixed it.  I had these values set incorrectly
```
autocmd BufNewFile,BufRead *.jsx set filetype=javascript.jsx
autocmd BufNewFile,BufRead *.tsx set filetype=typescript.tsx
```

**Comment by felipellrocha** [comment]
Ugh, I've been struggling with this issue. Thanks for the solution.
