### ISSUE TITLE
"Can not find typescript module, run ':CocInstall coc-tsserver' to fix it!" in a non-typescript project

### ISSUE THREAD

**Issue by david-perez** [neoclide/coc-tsserver#106]
I installed the extension using `:CocInstall coc-tsserver`. But when opening a `.js` file in a *javascript* project (i.e. no local `npm install typescript`), I get the error `Can not find typescript module, run ':CocInstall coc-tsserver' to fix it!`. Rerunning the `:CocInstall coc-tsserver` command yields the same result.

I thought this happened because I needed to specify `tsserver.tsdk` in my `coc-settings.json` in order to tell Coc to use my global npm installation.

So I ran `npm install -g typescript`, and changed my `coc-settings.json` to look like this:

```json
{
    "npm.binPath": "~/.config/versions/node/v12.13.1/bin/npm",
    "eslint.nodePath": "~/.config/versions/node/v12.13.1/bin/node",
    "tsserver.tsdk": "~/.config/versions/node/v12.13.1/lib/node_modules/typescript/lib",
    "tsserver.npm": "~/.config/versions/node/v12.13.1/bin/npm",
}
```

(I am using `nvm`). However, I now get `Can not find typescript module, in 'tsserver.tsdk': ~/.config/versions/node/v12.13.1/lib/node_modules/typescript/lib`, even though the file `tsserver.js` does exist under that directory.

Everything works fine if I `npm install typescript` locally in my project (but I don't want to, because it doesn't use typescript).

I think what is happening is that `coc-tsserver` is not using the global installation of typescript. A [quick search](https://github.com/neoclide/coc-tsserver/search?q=globalVersion&unscoped_q=globalVersion) yields that `globalVersion()` is defined but never used, while I think that it should be called somewhere in [`startService()`](https://github.com/neoclide/coc-tsserver/blob/74bb59b24e7be6d9a724515586ecb6fa66dfa0f7/src/server/typescriptServiceClient.ts#L261) in order to honor the `tsserver.tsdk` setting.

**Comment by chemzqm** [comment]
run ':CocInstall coc-tsserver' to fix it

**Comment by david-perez** [comment]
Ah, I see. `tsdk` is taken into account via [`getDefaultVersion`](https://github.com/neoclide/coc-tsserver/blob/3a4f9939186a2d2ff92cabaf500e20b2f0207c26/src/server/utils/versionProvider.ts#L93) an then that is [`resolve`](https://github.com/neoclide/coc-tsserver/blob/3a4f9939186a2d2ff92cabaf500e20b2f0207c26/src/server/utils/versionProvider.ts#L24)d to a global path.

Could we add support to `~` or `$HOME`? I persist these settings in my dotfiles, which I use in various machines with different usernames.
