### ISSUE TITLE
Imports can't be resolved when using multiple tsconfig.json files

### ISSUE THREAD

**Issue by avahe-kellenberger** [neoclide/coc-tsserver#107]
Similar to #9 

When using multiple `tsconfig.json` files in a repository, importing files does not work correctly when inside directories with a tsconfig parent that is not at the highest level (project root).

Example:
```
├── package.json
├── src
│   ├── A.ts
├── test
│   ├── tsconfig.json
│   ├── unit
│   │   ├── A.spec.ts
└── tsconfig.json
```

When editing `A.spec.ts`, I am unable to import from `A.ts`. In more complex setups, importing will "work" but the path will be relative to `./test/tsconfig.json` instead of being relative to the file being edited.

My cwd does not seem to affect the behavior. If I delete `./test/tsconfig.json`, importing works as expected.

**Comment by chemzqm** [comment]
Looks like you need correct workspaceFolders, checkout https://github.com/neoclide/coc.nvim/wiki/Using-workspaceFolders

**Comment by avahe-kellenberger** [comment]
I've tried setting `b:coc_root_patterns=['.git']`which is the first variable resolved to define the current workspace directory, but the issue still persists (as a side note, there is a `.git` directory at the top level of the example project). 

I can run the command `CocList folders` and see that the workspace folder is correct for my project, but I am still unable to import from `A.ts` into `A.spec.ts`.

Having multiple `tsconfig.json` files is common practice and is very useful. If I am missing something please let me know, but it appears to me that this is a bug.

**Comment by chemzqm** [comment]
You can check verbose output of tsserver.

**Comment by avahe-kellenberger** [comment]
I tried executing `import` under the quickfix list, [here](https://0x0.st/z08a.txt) is the output.

I'm not entirely sure what I should be looking for here - usually when I need to import something it will provide a path to the file. In my case, there is no path provided. It seems to just not look outside of the test directory where `tsconfig.json` lies.

**Comment by ahmedelgabri** [comment]
I have the same problem too & was coming here to open an issue. Did you find a solution for this @avahe-kellenberger ?

**Comment by avahe-kellenberger** [comment]
Unfortunately not, either have to wait for a fix or make one. Been too busy on other projects personally, but if I start doing a lot of TS work again I'll have to fix this

**Comment by chemzqm** [comment]
Please provide log of tsserver by `:CocCommand tsserver.openTsServerLog`

**Comment by chemzqm** [comment]
`rootPatterns` issue with extension was fixed, should be working now.
