### ISSUE TITLE
tsx file has no highlighting

### ISSUE THREAD

**Issue by bedisdover** [neoclide/coc-tsserver#108]
Everything work as expected，except `.tsx` file's hightlighting. What can i do to resolve the problem? Thanks.

Output of `:CocInfo`
```
## version

vim version: NVIM v0.4.3
node version: v12.13.1
coc.nvim version: 0.0.74-937354a908
term: xterm-256color
platform: linux

## Output channel: highlight

[Info  - 3:21:12 PM] Highlight server running in node v12.13.1
```

**Comment by chemzqm** [comment]
You need install related syntax plugin https://github.com/peitalin/vim-jsx-typescript

**Comment by bedisdover** [comment]
It works, thanks!
