### ISSUE TITLE
Enhance doHover to show complete interface definition

### ISSUE THREAD

**Issue by sbernheim4** [neoclide/coc-tsserver#109]
Given the following sample code:

```ts
// index.ts
import Person from './types.d.ts';

function foo(person: Person): string {
	return `${person.name} is ${person.age} years old`;
}

// types.d.ts
export default interface Person {
	name: string,
	age: number
}
```

calling the `definitionProvider` function with the cursor on the `P` of `Person`, the current output via the `displayString` is `(parameter) person: Person`

It would be more helpful instead to have the `displayString` output something like 

```ts
(parameter) person: Person {
	name: string,
	age: number
}
```

This could be trimmed for long interfaces, set to only display the first n properties, make the popup focus-able with another command etc but showing some additional properties beyond just the imported type would be very helpful. 

Going to the definition can be annoying as it causes the user to lose focus on the current file by switching to a new file.

A rough solution off the top of my head might involve using the go to definition capability, grabbing the result from the language server, and then returning it here https://github.com/neoclide/coc-tsserver/blob/master/src/server/features/hover.ts#L29 in place of the `quickinfo` command being executed

**Comment by sbernheim4** [comment]
Playing around a bit, the go to definition contains the `filePath`, `contextStart` and `contextEnd` keys. This can be used to open up the file in the background, grab the text at the positions indicated by `contextStart` and contextEnd and then return that to the `definitionProvider` function

**Comment by bag-man** [comment]
@sbernheim4 Did you make any progress on this? If you have a PR for it I'd love to see!

**Comment by sbernheim4** [comment]
Not yet, I haven't written anything for coc before and haven't had a lot of time recently. I might do some more digging though this weekend, if you have any ideas on how to add this functionality as well let me know

**Comment by chemzqm** [comment]
I would suggest send feature request to typescript project for improve the `doHover` document for interface.

**Comment by chemzqm** [comment]
Use go to definition instead of send your feature request to typescript developer.
