### ISSUE TITLE
Optional chaining in JS is highlighted as being erroneous

### ISSUE THREAD

**Issue by pjg** [neoclide/coc-tsserver#117]
Typescript version which the tsserver uses does support optional chaining, so I'm not sure why such expressions are being highlighted as incorrect JS code:

![image](https://user-images.githubusercontent.com/10712/74324474-634aed80-4d87-11ea-86ef-14ab38e7252b.png)

**Comment by fannheyward** [comment]
Can't reproduce. TypeScirpt bundled in `coc-tsserver` is already upgrade to 3.7, which Is support optional. Do you has local workspace typescript installed?

**Comment by pjg** [comment]
That was it, I had to upgrade typescript and related packages in the project to make it all work. Thanks!

**Comment by MichelKazi** [comment]
I know this is closed, but is there a way to configure coc-tsserver to use my system typescript and not project specific typescript? Looks like a repo at work is using typescript 3.5 still

**Comment by chemzqm** [comment]
Read configuration in Readme
