### ISSUE TITLE
Fixed location of language server

### ISSUE THREAD

**Issue by jjmurre** [neoclide/coc-tsserver#118]
I am using 'autochdir' in (n)vim. When I open files from another project, that has a different version of the typescript language server, sometimes coc-tsserver starts the wrong language server.

Would it be possible to configure a fixed path to the language server (like it is possible to configure the location of the black formatter for python with "python.formatting.blackPath").

**Comment by chemzqm** [comment]
Use tsserver.tsdk configuration.
