### ISSUE TITLE
How do I disable linting?

### ISSUE THREAD

**Issue by peitalin** [neoclide/coc-tsserver#12]
Hi, thanks for the plugin, it's working great. How do I disable linting?

**Comment by peitalin** [comment]
Nevermind, found it.
Might be good to change this line in the README to mention "disable linting"
`tsserver.enable set to false to disable tsserver language server.`

**Comment by chemzqm** [comment]
`tsserver.enable` is used for disable tsserver, the server won't start.
Use those settings for disable linting:

* `typescript.suggest.enabled` 
* `typescript.validate.enable`
* `javascript.suggest.enabled` 
* `javascript.validate.enable`
