### ISSUE TITLE
Problems with coc-tsserver after update.

### ISSUE THREAD

**Issue by erickzanardo** [neoclide/coc-tsserver#120]
Hello,

I have been using this plugin for a long time, and after a long time without updating the plugin, I have changed some stuff on my vim config, and the version of this plugin was updated along, and now I have been having some issues.

There are two issues happening for me, on `ts` files, an error is show like the print bellow
![Captura de Tela 2020-02-28 às 10 43 31](https://user-images.githubusercontent.com/835641/75553457-30eff000-5a17-11ea-976c-826b1b758153.png)

And on tsx files, no error is show, but no syntax highlight or code completion is working.

I may have been able to make a workaround by adding the following lines on my init.vim file:

```
au BufNewFile,BufRead *.ts set filetype=javascript
au BufNewFile,BufRead *.tsx set filetype=javascript
```

but I am not sure if that should be required.

this is the result of my CocInfo:

```
## versions

vim version: NVIM v0.3.1
node version: v10.17.0
coc.nvim version: 0.0.75-89c0c2380b
term: iTerm.app
platform: darwin
```

and this is my init.vim: https://github.com/erickzanardo/dotfiles/blob/master/init.vim

Let me know if there is any additional info that could help with this.

Thanks a lot for the work on this plugin!

**Comment by chemzqm** [comment]
For tsx files you have to configure the filetype to typescript.tsx or use plugin for tsx files.

**Comment by erickzanardo** [comment]
Could you point me on how to use that config? I saw that on the Readme but how to make the config is not clear for me.

**Comment by erickzanardo** [comment]
Well, I guess I find out how to that, leaving this here in the hope that it will help anyone else having the same doubt

```
autocmd BufNewFile,BufRead *.tsx,*.jsx set filetype=typescript.tsx
```

**Comment by kas** [comment]
@erickzanardo thank you for actually sharing a solution!

I am using this command in my .vimrc file:
`au BufNewFile,BufRead *.tsx set filetype=typescript.tsx`

I found the command from this answer: https://stackoverflow.com/a/28117335
