### ISSUE TITLE
Error: getReferences; getDocumentHighLight timeout; getDefinition timeout; getHover - Coc.nvim PARTIALLY stops working

### ISSUE THREAD

**Issue by Annis-Monadjem** [neoclide/coc-tsserver#122]
### I). Specs (with newest and stable  nodejs)
vim version: NVIM v0.5.0-139-g610755ff6
**node version: v13.9.0**
coc.nvim version: 0.0.75-027b7a76e9
term: screen-256color
platform: linux

#### A) Problem Detail Description:
Coc.nvim **abruptly and partially** breaks-down with errors: ERROR getDocumentHighLight timeout, ERROR [languages] - getDefinition timeout, and ERROR [plugin] - Error: getDefinition. _**CocOpenLog reports that all Coc.nvim functionalities such as getDefinition, getDocumentHighlight, getReferences , getHover crash at one and the same line code 49805 in the coc.nvim plugin**_

#### B) Steps Taken To Remedy Problem:
a) Apps are up-to-date: and in particular, NVIM v0.5.0-139-g610755ff6 latest version. Nodejs used stable current version 13.9.0 (see point I above) and subsequently, LTS versions 12.6.1 (see point II below). Each time in `init.vim` applied the line of code `let g:coc_node_path = '/path/to/node'`

b) Neovim checkhealth - all "OK"

c) In Neovim i execute to reinstall and rebuild language servers: a) PlugInstall, b) PlugUpdate, c) UpdateRemotePlugins, d) CocRebuild, e) CocRestart, f) CocUpdate.
Also, prior to using Coc executed command :CocRebuild to rebuild coc extensions.

d) reinstalled Coc.nvim plugging several times appling in `init.vim`:
`Plug 'neoclide/coc.nvim', {'branch': 'release'}`

#### C) Observation of Problem Occurrences:
a) Coc.nvim is partially working - Coc.nvim works only in newly created files and directories. Coc.nvim stops working on files/directories (collection of my earlier files/directories) prior to Coc.nvim update.

b) CocOpenLog reports that all Coc.nvim functionalities such as getDefinition, getDocumentHighlight, getReferences , getHover crash/timeout at one and the same line code 49805 in the coc.nvim plugin:
```
at Timeout._onTimeout (/home/sky/.config/nvim/plugged/coc.nvim/build/index.js:49805:28)
```
c) Changing Nodejs version from current stable 13.9.0 to LTS 12.6.1 did NOT make any tangible improvement. The problem continues to persist.

##### 1. `CocCommand tsserver.openTsServerLog Report:` 
- [A] [coc-nvim-tsc.log](https://github.com/neoclide/coc-tsserver/files/4290727/coc-nvim-tsc.log)
- [B] [coc-nvim-tsc.log](https://github.com/neoclide/coc-tsserver/files/4290960/coc-nvim-tsc.log)

##### 2. `CocCommand workspace.showOutput tsserver:`
- [A] [tsserver.log](https://github.com/neoclide/coc-tsserver/files/4290733/tsserver.log)
- [B] [tsserver.log](https://github.com/neoclide/coc-tsserver/files/4290963/tsserver.log)

##### 3. `CocOpenLog:`
- [A] [CocOpenLog.log](https://github.com/neoclide/coc-tsserver/files/4290740/CocOpenLog.log)
- [B] [coc-nvim-27690.log](https://github.com/neoclide/coc-tsserver/files/4290970/coc-nvim-27690.log)

##### 4. `CocInfo:`
- [B] [info.log](https://github.com/neoclide/coc-tsserver/files/4290976/info.log)

### II). Specs (with LTS stable nodejs version 12.6.1)
vim version: NVIM v0.5.0-139-g610755ff6
**node version: v12.6.1**
coc.nvim version: 0.0.75-027b7a76e9
term: screen-256color
platform: linux

##### 1. `CocCommand tsserver.openTsServerLog Report:` 
- [C] [coc-nvim-tsc.log](https://github.com/neoclide/coc-tsserver/files/4291171/coc-nvim-tsc.log)

##### 2. `CocCommand workspace.showOutput tsserver:`
- [C] [tsserver.log](https://github.com/neoclide/coc-tsserver/files/4291174/tsserver.log)

##### 3. `CocOpenLog:`
- [C] [coc-nvim-7291.log](https://github.com/neoclide/coc-tsserver/files/4291181/coc-nvim-7291.log)

##### 4. `CocInfo:`
- [C] [info.log](https://github.com/neoclide/coc-tsserver/files/4291184/info.log)

Please, assist with resolving this problem. Hints, suggestions, solutions or any observations will be greatly appreciated.

**Comment by chemzqm** [comment]
It looks like you have some links on your disk and tsserver looks at files in /home/sky/.cache which is too big and blocked tsserver.

```
Info 61   [4:58:51.890] sysLog:: /home/sky/.cache/doc:: Changing to fsWatchFile
Info 62   [4:58:57.362] sysLog:: /home/sky/.cache/restic/0043ae64d9942eea7ad09d2f46dbeeaba82e003647791f3f0187c23cacd6b69c/data/62:: Changing to fsWatchFile
Info 63   [4:58:57.363] sysLog:: /home/sky/.cache/restic/0043ae64d9942eea7ad09d2f46dbeeaba82e003647791f3f0187c23cacd6b69c/data/68:: Changing to fsWatchFile
Info 64   [4:58:57.364] sysLog:: /home/sky/.cache/restic/0043ae64d9942eea7ad09d2f46dbeeaba82e003647791f3f0187c23cacd6b69c/data/9b:: Changing to fsWatchFile
Info 65   [4:58:57.364] sysLog:: /home/sky/.cache/restic/0043ae64d9942eea7ad09d2f46dbeeaba82e003647791f3f0187c23cacd6b69c/data/a4:: Changing to fsWatchFile
Info 66   [4:58:57.364] sysLog:: /home/sky/.cache/restic/0043ae64d9942eea7ad09d2f46dbeeaba82e003647791f3f0187c23cacd6b69c/data/e3:: Changing to fsWatchFile
Info 67   [4:58:57.364] sysLog:: /home/sky/.cache/restic/0043ae64d9942eea7ad09d2f46dbeeaba82e003647791f3f0187c23cacd6b69c/data/ec:: Changing to fsWatchFile
```

**Comment by Annis-Monadjem** [comment]
@chemzqm : also noticed this `restic` thing in the report, but cannot make any sense out of it. I am not using anything of that sorts, and thing is not on my $PATH. What would be the best thing to do in such case ?

**Comment by chemzqm** [comment]
Try other vim plugin or VSCode

**Comment by Annis-Monadjem** [comment]
I asked you how can i fix the problem above ?

**Comment by chemzqm** [comment]
No idea，your tsserver get blocked.

**Comment by Annis-Monadjem** [comment]
Fixed !

**Comment by sergeichestakov** [comment]
I'm running into this as well. @Annis-Monadjem can you share how you fixed this?

**Comment by Annis-Monadjem** [comment]
@sergeichestakov: i deleted `/home/sky/.cache/restic/` and the problem went away for good.
