### ISSUE TITLE
Fails to start on 1.4.10

### ISSUE THREAD

**Issue by simonsmith** [neoclide/coc-tsserver#124]
Hi,

Having just upgraded to 1.4.10 I no longer have tsserver starting correctly. 

`CocCommand tsserver.restart `gives me `E492: Not an editor command: CocCommad tsserver.restart`

When running `CocInfo` I cannot see `## Output channel: tsserver` in the list either.

If I manually rollback to `1.4.9` by running `npm install coc-tsserver@1.4.9` in the `.config/coc/extensions` directory it works again as expected.

More than willing to provide additional debug information as needed

**Comment by jpoppe** [comment]
To downgrade properly execute the following command in (Neo)VIM: `:CocInstall coc-tsserver@1.4.9`

**Comment by Annis-Monadjem** [comment]
> Hi,
> 
> Having just upgraded to 1.4.10 I no longer have tsserver starting correctly.
> 
> `CocCommand tsserver.restart `gives me `E492: Not an editor command: CocCommad tsserver.restart`
> 
> When running `CocInfo` I cannot see `## Output channel: tsserver` in the list either.
> 
> If I manually rollback to `1.4.9` by running `npm install coc-tsserver@1.4.9` in the `.config/coc/extensions` directory it works again as expected.
> 
> More than willing to provide additional debug information as needed

Further observation: `npm install coc-tsserver@1.4.9` fixes coc, but the solution is limited, bec. if you try to `CocUpdate` then it automatically reverts back to @1.4.10 (even though it was completely removed from `~/.config/extensions/node_modules/`). Or am i missing on something here ?

**Comment by yujinyuz** [comment]
It's working again after downgrading to 1.4.9

^ The above can be temporarily be fixed by locking the current version of coc-tsserver

`:CocList extensions`

Select coc-tsserver then press `l` to lock its version

**Comment by chemzqm** [comment]
Please upgrade to 1.4.11.

**Comment by simonsmith** [comment]
For reference, I fixed the version with `vim-plug` in the end: 
```
Plug 'neoclide/coc-tsserver', {'do': 'yarn install --frozen-lockfile', 'tag': '1.4.9'}
```

Thanks for the fix @chemzqm

**Comment by ayoubelmhamdi** [comment]
something i mess install extension and i'm get error coc lsp not found
