### ISSUE TITLE
Rollback tsserver@1.4.9 only temp solution

### ISSUE THREAD

**Issue by Annis-Monadjem** [neoclide/coc-tsserver#125]
> Hi,
> 
> Having just upgraded to 1.4.10 I no longer have tsserver starting correctly.
> 
> `CocCommand tsserver.restart `gives me `E492: Not an editor command: CocCommad tsserver.restart`
> 
> When running `CocInfo` I cannot see `## Output channel: tsserver` in the list either.
> 
> If I manually rollback to `1.4.9` by running `npm install coc-tsserver@1.4.9` in the `.config/coc/extensions` directory it works again as expected.
> 
> More than willing to provide additional debug information as needed

Further observation: `npm install coc-tsserver@1.4.9` and `CocInstall coc-tsserver@1.4.9` fix coc, but the solution is limited, bec. if you try to `CocUpdate` then it automatically reverts back to @1.4.10 (even though it was completely removed from `~/.config/extensions/node_modules/`). 

_Originally posted by @Annis-Monadjem in https://github.com/neoclide/coc-tsserver/issues/124#issuecomment-596082534_

**Comment by rbeer** [comment]
You just saved an absolute vim noob from a lot of frustration. Thanks! :D

**Comment by dessalines** [comment]
Thank you! This should probably be rolled back until 1.4.10 works, I was really confused as to why it stopped working all of the sudden.

**Comment by nxvu699134** [comment]
So many thanks bro. I wasted half of day to find your solution. It works like a magic.

**Comment by Nasafato** [comment]
You can still lock the version by using `:CocList extensions` then tabbing over `coc-tsserver` and locking it.

**Comment by DaniloMarques1** [comment]
my auto completion simply stop working. You solved my problem, thanks!!!!!!

**Comment by quentin-fox** [comment]
Thanks so much! It's surprising to find that my (neo)vim setup broke and it _wasn't_ my fault.

**Comment by xuxinhang** [comment]
Thanks! 

And the install dir of `coc-tsserver` seems to be different on Windows, which could be shown by execuating `:echo coc#util#extension_root()` . For me, that's `C:\Users\YOUR_USERNAME\AppData\Local\coc\extensions\`.

**Comment by jummy233** [comment]
If you want to use 1.4.10 you can also download the source and pack it yourself. The release works fine, but the one host on npm doesn't contain any code for some reason.

**Comment by YUFENGWANG** [comment]
Save my ass, thank you!

**Comment by werevamp** [comment]
Oh my god, I've been debugging this thing for the past 2 days, I should really look at github more often THANKS!

**Comment by chemzqm** [comment]
Please upgrade to 1.4.11.
