### ISSUE TITLE
1.4.10 npm package doesn't contain lib or src directory

### ISSUE THREAD

**Issue by jummy233** [neoclide/coc-tsserver#126]
I had [This issue](https://github.com/neoclide/coc-tsserver/issues/124) and fixed it by rollback current `coc-tsserver` to 1.4.9.
1.4.10 works fine if you compile from the source locally. But the version host on `npm` has no src file, so it is basically empty.

Here is the directory structure of 1.4.10 downloaded from npm:

![2020-03-08-040702_700x300_scrot](https://user-images.githubusercontent.com/12954634/76161769-ac2a6380-60f3-11ea-883e-08bc02f795cc.png)
It should be fixed with a simple repack.

**Comment by chemzqm** [comment]
Please upgrade to 1.4.11.
