### ISSUE TITLE
Allow disabling and enabling featurs per-buffer, on the fly

### ISSUE THREAD

**Issue by TxHawks** [neoclide/coc-tsserver#13]
As discussed in neoclide/coc.nvim#361, It'd be useful to be able to set `tsserver` options per buffer, specifically `tsserver.enableJavascript`.

When working in repositories with mixed flow and untyped javascript files, I'd like the typescript extension to check untyped javascript files, but enabling `tsserver.enableJavascript` breaks flow file, since type annotations are only allowed in ts files.

A `b:coc_tsserver_disable` buffer variable would be great

**Comment by TxHawks** [comment]
Thanks for implementing this!

Does this work on the fly, or only at buffer creation?

**Comment by chemzqm** [comment]
The variable have to be set on buffer create.
