### ISSUE TITLE
CocCommand + prettier on save possible?

### ISSUE THREAD

**Issue by gugahoi** [neoclide/coc-tsserver#130]
I am trying to use `"tsserver.organizeImports"` on save however I also use `prettier` to format my file on save. Is it possible to have them both together? For example: first run `organizeImports` and then let `prettier` do its thing? 

I've tried to add the below `autocmd` however things got messed up and it seems both the organizeImports and prettier are running at the same time. 

```
autocmd BufWritePre *.tsx :CocCommand tsserver.organizeImports
```

**Comment by chemzqm** [comment]
Use `call     CocAction('runCommand', 'tsserver.organizeImports')`

**Comment by chemzqm** [comment]
It's not a good idea to organize imports on save since it would remove unused imports.

**Comment by gugahoi** [comment]
I understand how to execute it on command, however I am trying to replicate my workflow from VS Code and was hoping I could sequentially call multiple commands on save. It is not a problem for me the chance of removing unused imports - especially given it autoimports on completion. I appreciate your help 🙏 .

**Comment by nahushf** [comment]
I am pretty new to vim so this might be a really basic question. I tried setting a keybinding to do something similar as follows
```
nnoremap <leader>oi :CocAction('runCommand', 'tsserver.organizeImports')<CR>:Prettier<CR>
```
But when I run this keybinding I get prompts such as 
```
1. Convert namespace imports to named imports
2. Remove declaration for: ABC
```
I am guessing coc-tsserver is trying to understand how it wants to organize my imports. Although when I run `:CocCommand tsserver.organizeImports` there are no such prompts. How do I get the above keybinding to work without the prompts?
