### ISSUE TITLE
How to add types to completion

### ISSUE THREAD

**Issue by vegerot** [neoclide/coc-tsserver#131]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I start typing, get some IntelliSense suggestions, but none of them have types UNTIL I hover over a specific one.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/5297725/77266284-6e8e1480-6c75-11ea-962c-a6f3863863b8.png)
instead of 
![image](https://user-images.githubusercontent.com/5297725/77266301-7b126d00-6c75-11ea-8c95-ff018cd34b72.png)

**Describe alternatives you've considered**
Just tab cycling through everything, switching to YCM
**Additional context**

**Comment by chemzqm** [comment]
Not possible, function signature is resolved.

**Comment by vegerot** [comment]
is this a CoC, coc-tsserver, or tsserver limitation? I'm pretty sure YCM can show it with tsserver (I may be misremembering that, since it's been a while since I've used that).  I suppose YCM could be iterating through the list and fetching extra info to display in the menu.  If that is the case, in that case the coc-tsserver plugin could simply have an option for this. I understand reluctance for this, due to CoC's mission to keep functionality as close to VSCode as possible, and they would rather this be added to tsserver (to return the extra info) for them to implement in coc-tsserver.
(copied from gitter)

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
