### ISSUE TITLE
How do we rename a directory and have it update all imports?

### ISSUE THREAD

**Issue by geoyws** [neoclide/coc-tsserver#132]
Right now I'm doing it via VSCode instead. I've scoured Google and the official docs but found nothing... Thanks for the help!

**Comment by chemzqm** [comment]
It can't because coc.nvim only detect file changes for now, duplicate of #52, we need try to find out some solution.

**Comment by geoyws** [comment]
Thanks man. Appreciate the effort. Perhaps we could find out how VSCode does it.

**Comment by geoyws** [comment]
Maybe we could collaborate with NERDTree and netrw and hook in from their hooks?

**Comment by chemzqm** [comment]
> Maybe we could collaborate with NERDTree and netrw and hook in from their hooks? 

Not needs, watchman can watch folder name change.
