### ISSUE TITLE
Enable only for .ts files

### ISSUE THREAD

**Issue by costerik** [neoclide/coc-tsserver#135]
Hey guys,
I would like to know if there is a way to enable this capability with only `.ts` files. I use flow for other projects so I have installed `coc-flow` and work perfectly but now I installed `coc-tsserver` but there are issues on `.js` files with flow set as the static type checker.

Thanks in advance

**Comment by chemzqm** [comment]
Please read configuration in readme

**Comment by costerik** [comment]
I solved it, I added `"tsserver.enableJavascript": false` in the `coc-settings.json` file located at `.config/nvim` folder.
```
{
    "tsserver.enableJavascript": false
}
```
