### ISSUE TITLE
Auto suggest import with extension of file

### ISSUE THREAD

**Issue by utrumo** [neoclide/coc-tsserver#137]
vscode suggest looks like that:
![vscode_suggest](https://user-images.githubusercontent.com/22612354/78997277-ed78bd80-7b4e-11ea-813a-74549225ebcf.png)
and neovim suggest looks like that:
![neovim_suggest](https://user-images.githubusercontent.com/22612354/78997324-07b29b80-7b4f-11ea-8b44-44b849978736.png)

Can you add additional information about file extension to neovim popup like it work in vscode?
Or add option to config like 'importModuleSuggestWithFileExtension' true/false?

It will be great if import suggesting will offering file with extension too like it work on auto import with   "javascript.preferences.importModuleSpecifierEnding": "js" option.

**Comment by chemzqm** [comment]
It is supported, check available option by completion use coc-json

**Comment by utrumo** [comment]
> It is supported, check available option by completion use coc-json

What kind of option are you talking about? I found only importModuleSuggestWithFileExtension
and it works only with auto imports, but it doesn't work if i simple write import by my hands.
