### ISSUE TITLE
Artifacts remain after preview balloon has closed

### ISSUE THREAD

**Issue by geoyws** [neoclide/coc-tsserver#139]
![image](https://user-images.githubusercontent.com/1738396/79215108-c9ceb380-7e7d-11ea-951d-ec6d8e0a83a5.png)

Anyone else have this problem? I have to restart Vim for the balloon remnants to go away.

**Comment by chemzqm** [comment]
It happens on some version of neoivm, use `<C-w>o` to close other windows or use `:call coc#util#float_hide()`
