### ISSUE TITLE
Go-to-definition in another file?

### ISSUE THREAD

**Issue by hew** [neoclide/coc-tsserver#14]
Question: is it possible to go-to-definition if the definition was declared in another file?

**Comment by chemzqm** [comment]
Sure.

**Comment by hew** [comment]
What does the config look like? I can't seem to get it to work. Right now I have the following: 

```js
{
  "compilerOptions": {
    "target": "ES6",
    "module": "commonjs",
    "allowSyntheticDefaultImports": true,
    "baseUrl": "./src/",
    "paths": {
      "*": ["*"]
    }
  },
  "exclude": ["node_modules", "**/node_modules/*"]
}

```

**Comment by hew** [comment]
When I use the command, my cursor just jumps up to line 12, from 15. Not into the file where it was exported.

![image](https://user-images.githubusercontent.com/3103241/54804624-6732c600-4c31-11e9-89db-b856a146ee7f.png)

**Comment by chemzqm** [comment]
I can't reproduce, it works as expected for me, need checkout verbose output from tsserver https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by chemzqm** [comment]
Maybe your local tssever is too old.

**Comment by hew** [comment]
Figured it out. Looks like an old config issue. Works now.

**Comment by hew** [comment]
Thanks for the quick response and plugin btw 😀

**Comment by kryshac** [comment]
which is the command to go to the definition?

**Comment by hew** [comment]
Default is `gd`

**Comment by kryshac** [comment]
> When I use the command, my cursor just jumps up to line 2, from 5. Not into the file where it was exported.
> 
> ![image](https://user-images.githubusercontent.com/3103241/54804624-6732c600-4c31-11e9-89db-b856a146ee7f.png)

I have the same problem

**Comment by chemzqm** [comment]
There's no command but keymap and function provided from coc.nvim, you can create command or map to the key you like to use.

**Comment by chemzqm** [comment]
Upgrade your local typescript module.

**Comment by kryshac** [comment]
my version is 
![image](https://user-images.githubusercontent.com/19764133/55798489-bbfe8980-5ad7-11e9-83d3-d8d8a5987b15.png)

**Comment by chemzqm** [comment]
It's old.

**Comment by chemzqm** [comment]
Looks like you have to stick to it, sine higher version of tsserver may not parse your code as expected.

**Comment by kryshac** [comment]
@chemzqm in vscode works correctly

**Comment by MicahMartin** [comment]
@hew what was your config issue? I'm running into the same issue

No local tsserver, but global tsserver is @3.4.5

```
Info 197  [9:17:27.484] request:
    {"seq":21,"type":"request","command":"definition","arguments":{"file":"/Users/martin/dev/js/pageBuilder/components/features/global/RecircFeed/default.jsx","line":10,"offset":8}}
Perf 198  [9:17:27.485] 21::definition: elapsed time (in milliseconds) 0.5730
Info 199  [9:17:27.485] response:
    {"seq":0,"type":"response","command":"definition","request_seq":21,"success":true,"body":[{"file":"/Users/martin/dev/js/pageBuilder/components/features/global/RecircFeed/default.jsx","start":{"line":10,"offset":8},"end":{"line":10,"offset":21}}]}
```

**Comment by sheerun** [comment]
For me `coc-definition` jumps to typescript definition instead of actual implementation :(

**Comment by sheerun** [comment]
(it happens only when typescript typings are available). I'd love command that always jumps to implementatino instead of typescript declaration (coc-implementation doesn't work as well)

**Comment by sheerun** [comment]
I think here's related issue:
https://github.com/microsoft/TypeScript/issues/6209

**Comment by chemzqm** [comment]
You have to use `<Plug>(coc-implementation)` instead, you can overwrite your keymap for typescript.

**Comment by sheerun** [comment]
@chemzqm Unfortunately `<Plug>(coc-implementation)` either shows `[coc.nvim] Implementation not found` or jumps to type definitions. This seems to be bug of typescript, not this plugin: microsoft/TypeScript#6209

**Comment by reergymerej** [comment]
```
" Remap keys for gotos
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)
```

**Comment by ColinRyan** [comment]
@hew Hey, I'm having the exact same issue. Would you be able to share your config with me? I'd like to test if it works in my case too

**Comment by TidyIQ** [comment]
> Default is `gd`

How do I run this?

```
:gd
> E492: Not an editor command: gd
```
```
:CocCommand gd
> [coc.vim] Command: gd not found
```

**Comment by chemzqm** [comment]
@TidyIQ Learn viml first.

**Comment by sangaline** [comment]
I'm seeing the same issue with `3.8.3` which is the same version that `coc-tsserver` plugin has installed as its own dependency. I'm using all of the default configuration options, nothing is overridden in `coc-settings.json`. `:CocOpenLog` doesn't display anything after the servers starting up.

@chemzqm Is there anything else I can do to debug why it's just jumping to the import instead of the definition or implementation? Everything else seems to work fine, so I don't think it's an issue with import paths.

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc-tsserver#troubleshooting

**Comment by sangaline** [comment]
Thanks for the link. I noticed when testing this that the behavior only happens when importing from a JavaScript file into a TypeScript file. I'm guessing that this behavior has to do with tsserver itself rather than coc-tsserver specifically.

The output from `CocCommand tsserver.openTsServerLog`:

```
Info 327  [11:26:24.791] request:
    {"seq":6,"type":"request","command":"definition","arguments":{"file":"/home/sangaline/workspaces/test/test.tsx","line":46,"offset":5}}
Perf 328  [11:26:24.794] 6::definition: elapsed time (in milliseconds) 2.9867
Info 329  [11:26:24.794] response:
    {"seq":0,"type":"response","command":"definition","request_seq":6,"success":true,"body":[{"file":"/home/sangaline/workspaces/test/test.tsx","start":{"line":18,"offset":3},"end":{"line":18,"offset":19},"contextStart":{"line":14,"offset":1},"contextEnd":{"line":19,"offset":39}}]}
```

The output from `CocCommand workspace.showOutput tsserver`:

```
[Trace  - 11:29:58 AM] TypeScript Server: trying to cancel ongoing request with sequence number 7
[Trace  - 11:30:15 AM] Sending request: definition (8). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/home/sangaline/workspaces/test/test.tsx",
    "line": 46,
    "offset": 5
}
[Trace  - 11:30:15 AM] Response received: definition (8). Request took 1 ms. Success: true 
Result: [
    {
        "file": "/home/sangaline/workspaces/test/test.tsx",
        "start": {
            "line": 18,
            "offset": 3
        },
        "end": {
            "line": 18,
            "offset": 19
        },
        "contextStart": {
            "line": 14,
            "offset": 1
        },
        "contextEnd": {
            "line": 19,
            "offset": 39
        }
    }
]

[Trace  - 11:30:23 AM] TypeScript Server: trying to cancel ongoing request with sequence number 8
```

**Comment by magtastic** [comment]
@chemzqm the toxicity is reeeaaal 😂.

@TidyIQ 
```
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)
```
Adding this to your vimrc file maps the keys after the `<silent>` tag to a command that follows.

Eg. `nmap <silent> gd <Plug>(coc-definition)` maps the keystrokes `gd` to the command `coc-definition`. So while in normal mode, with the cursor over something you want to check the definition of, you can simply press `gd` to jump to the definition. No need to be prefixed by any `:` ☺️

**Comment by sQVe** [comment]
> @chemzqm the toxicity is reeeaaal.

@magtastic I would like to strongly disagree. I think there are cases, like this one, where on should learn to **RTFM**. There even lots of clues in this specific issue on how to use `gd`.

I would think that you also *wouldn't take your time and hand hold every individual* if you, like @chemzqm, would maintain *loads of large repos*, try to keep up with **thousands of issues** and at the same time produce *thousands of commits over just 2 years*. Give it a try...

**Comment by firedev** [comment]
Should it work in `.js` files? It jumps to `import` line always.

**Comment by sQVe** [comment]
> @chemzqm the toxicity is reeeaaal.
> @chemzqm BTW, this is the exact reason why I did not use vim for the longest time. I thought vim was way too complicated for me because the community is so elitist with the "It is not supposed to be easy" attitude. (Turns out vim is not complicated, just different, and in need of a more welcoming community)

@magtastic How is :point_up: helping? This is not a case of *elitism* but rather a one-man-show with a pretty insane workload. I think it somewhat unfair to expect hand holding in cases which are clear **RTFM**.

Instead of pointing fingers, consider contributing.

**Comment by chemzqm** [comment]
> Should it work in `.js` files? It always jumps to the `import` line.

Not always, the javascript support of tsserver is limited.
Refer to https://github.com/microsoft/TypeScript for help in case you want it improved.

**Comment by nico-bellante** [comment]
Have we come to a conclusion on what causes this issue? Or can it be multiple things? (I have 3.8 or newer for my typescript server, but the project I'm working on has a pretty crazy tsconfig, and in using the debugging methods nothing sticks out to me as wrong.)

**Comment by sheerun** [comment]
It's typescript's bug: https://github.com/microsoft/TypeScript/pull/39426

**Comment by Guobacai** [comment]
Hi @chemzqm 

Thanks for this incredible tool.

> > Should it work in `.js` files? It always jumps to the `import` line.
> 
> Not always, the javascript support of tsserver is limited.
> Refer to https://github.com/microsoft/TypeScript for help in case you want it improved.

Is the "go to definition in another file" in js file supported by tsserver?
Right now, when I press 'gd', I got the following error:
[coc.nvim] definition not found

The tags file is generated, but I couldnt figure out why 'gd' is not working.

Thanks

**Comment by chemzqm** [comment]
@Guobacai tsserver doesn't have support of tags, use other tools instead.

**Comment by Guobacai** [comment]
Thanks @chemzqm for your quick response.

I am still new to use the vim as IDE. Looks like I misunderstand the use of universal ctags and coc-tsserver.

I was trying @hew's jsconfig, but still not working.

My project is the middle of transition from commonjs to full ES6 module. I am not sure if this would affect "go to definition" function.

**Comment by chemzqm** [comment]
Checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel, 
Some feature of tsserver doesn't work well with javascript, you could try VSCode first.

**Comment by fabriziobertoglio1987** [comment]
ctags go to definition are by default supported in vim. you just need to install ctags and use c+] to navigate 

I also use fzf.vim with :Tags to search for tags in a project

**Comment by fabriziobertoglio1987** [comment]
additionally not a good idea to use ctags with es6 .. or typescript.. 
better to use coc-tssserver as es6 new language features do not work well with ctags

**Comment by juxuny** [comment]
> ```
> " Remap keys for gotos
> nmap <silent> gd <Plug>(coc-definition)
> nmap <silent> gy <Plug>(coc-type-definition)
> nmap <silent> gi <Plug>(coc-implementation)
> nmap <silent> gr <Plug>(coc-references)
> ```

It's work for me
