### ISSUE TITLE
Yarn2 PnP support ?

### ISSUE THREAD

**Issue by svvac** [neoclide/coc-tsserver#140]
Yarn v2 takes over the `node_modules` folder of a project which breaks module resolution when using a `tsserver` external to the project.

You can still exec `yarn bin tsserver` to spin the local one, but that doesn't seem to help here.

You can also run `yarn unplug typescript` which makes the files available on disk in `.yarn/unplugged/typescript-{something}/node_modules/typescript/lib/tsserver.js`, but I can't seem to manage making that work with `tsserver.tsdk`.

Any pointers?

**Comment by svvac** [comment]
It was staring [right at my face](https://yarnpkg.com/advanced/editor-sdks#vim--cocnvim). Sorry for the noise

I'd close, but it may be worth investigating a more straightforward implementation?

**Comment by chemzqm** [comment]
Added to Readme.
