### ISSUE TITLE
Cannot find module reference from an excluded file

### ISSUE THREAD

**Issue by kidonchu** [neoclide/coc-tsserver#141]
I have test files that are _excluded_ by tsconfig.json.
```
// tsconfig.json
{
  ...
  "exclude": [
    "**/*.test.tsx",
  ]
```

In one of these test files, when I import any module
```
// components/__tests__/SearchPage.test.tsx
import Search from 'components/Search';
```
I get an error message
`[tsserver] Cannot find module 'components/Search'. [E]`

However, this works fine for tsconfig-included files. i.e. components/SearchPage.tsx.

I would expect to be able to find all reference to my modules from excluded files but it seems that's not how it works.

Is this expected behavior?

**Comment by chemzqm** [comment]
It's expected.
