### ISSUE TITLE
Could not find a declaration file for module

### ISSUE THREAD

**Issue by xiaopihai7256** [neoclide/coc-tsserver#143]
![image](https://user-images.githubusercontent.com/11835524/80306212-73a22e80-87f4-11ea-8603-3598ffd9eed8.png)

server can't find a declaration file for module. when I append '.js' for that line, It's works. 

this is my project config: jsconfig.js

```json
{
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": [
    "src/**/*"
  ]
}

```

**Comment by xiaopihai7256** [comment]
vscode is work.
![image](https://user-images.githubusercontent.com/11835524/80306402-aac50f80-87f5-11ea-9db2-551cdac452de.png)

**Comment by chemzqm** [comment]
Check server log and make sure your npmPath is global one.

**Comment by chemzqm** [comment]
Oh you have to disable suggestActions to avoid that hint
