### ISSUE TITLE
Dot completion for JavaScript?

### ISSUE THREAD

**Issue by philFernandez** [neoclide/coc-tsserver#144]
Hi, sorry if I'm not presenting this issue in the proper fashion. I'm new to javascript, and not completely sure of everything.

I use your plugins for java completion in vim, and the set of tools is by far the best that I've used for java. I have to do some javascript programming for a school assignment, so that lead me to setting up this tool. 

I have node, npm, typescript all installed globally, and I have the `"tsserver.npm": "/usr/local/bin/npm"` set in my coc-settings.json file. The autocomplete for javascript is only partly working for me. For example if I start to type `console` it will bring up `const`, `console`, etc., as completion options, but when I press the `.` as in `console.log` it does not offer completion options for `.log`, `.dir`, `.info`, etc. Same for lists, event listeners, really anything that comes after a `.`

I tested the functionality inside of a typescript file, and everything works properly, but not so inside of a javascript file. Am I missing some setting or doing something wrong in order to get auto completion in javascript file?

Thank You for the awesome set of tools!

**Comment by chemzqm** [comment]
It should just work 
https://github.com/neoclide/coc-tsserver/blob/master/Readme.md#troubleshooting

**Comment by philFernandez** [comment]
> It should just work
> https://github.com/neoclide/coc-tsserver/blob/master/Readme.md#troubleshooting

FYI, it doesn't just work

**Comment by chemzqm** [comment]
You need figure it out yourself

**Comment by philFernandez** [comment]
I apologize.. I figured out the problem. It was something in my config... my bad.

Thank you for the work you do with these tools. Do you have a place for donations?

**Comment by rlanore** [comment]
Hi, I have same problem as you. Could you explain how you resolve this.
Thanks
