### ISSUE TITLE
nullish coalescing operator syntax highlight bug

### ISSUE THREAD

**Issue by ggsalas** [neoclide/coc-tsserver#145]
Hi, I see a bug with the syntax highlight colors after add a nullish coalescing operator (`??`)
 
<img width="800" alt="Screen Shot 2020-05-04 at 19 50 57" src="https://user-images.githubusercontent.com/8403993/80996968-f9e7f180-8e40-11ea-8d70-8655baeac7fe.png">

Thanks, regards

**Comment by chemzqm** [comment]
It's bug of your syntax plugin.
