### ISSUE TITLE
Can't find tsconfig.json in monorepo

### ISSUE THREAD

**Issue by esetnik** [neoclide/coc-tsserver#146]
Unable to locate `tsconfig.json` relative to the current buffer (main.ts) when cwd is at the root of the project.

Example is opening vim at the root and then opening `main.ts`. I get an error `Parsing error: File '/users/xxx/work/project/tsconfig.json' not found.`, but it should be traversing the tree to find the nearest  `tsconfig.json` at `/users/xxx/work/project/api/tsconfig.json`

My project layout:

```
├── package.json
├── .git
├── api
│   ├── package.json
│   ├── src
│       └── main.ts
│   └── tsconfig.json
```

If I set cwd to api e.g. `nvim api` then `tsconfig.json` is found and works correctly.

**Comment by chemzqm** [comment]
Looks like error from other vim plugin, read https://github.com/neoclide/coc-tsserver#troubleshooting

**Comment by esetnik** [comment]
@chemzqm I found the issue. You were correct, it's caused by another plugin. The error only happens when I have both `coc-eslint` and `coc-tsserver` enabled.

**Comment by poupougnac** [comment]
Inside my `coc-settings.json` (:CocConfig), to fix this I used:
 `eslint.workingDirectories: [{ "mode": "auto" }]`

More info about [eslint.workingDirectories](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint#settings-options)
