### ISSUE TITLE
Suppress `0 references`

### ISSUE THREAD

**Issue by firedev** [neoclide/coc-tsserver#147]
Is it possible to suppress `0 references` which is maybe too much sometimes?

```js
value={normalizeValue({ options, value: field.value })} ‣ 2 references 0 references
```

**Comment by chemzqm** [comment]
No such option yet.

**Comment by sigmaSd** [comment]
I also found this annoying in certain projects. any workaround?

**Comment by sigmaSd** [comment]
For my own use-case this is enough
```
"javascript.referencesCodeLens.enable": false,
"typescript.referencesCodeLens.enable": false,
```

**Comment by chemzqm** [comment]
Use latest coc-tsserver,it’s improved

**Comment by sigmaSd** [comment]
Thanks a lot! that's a very recent commit so I didn't think to update, that fixes it indeed
