### ISSUE TITLE
no diagnostics in javascript files (ft=javascript.jsx)

### ISSUE THREAD

**Issue by jguddas** [neoclide/coc-tsserver#148]
**what i do:**

```
mkdir ~/coc-tsserver-test
cd ~/coc-tsserver-test
echo "const a=''; a()" > test.js
cp test.js test.ts
vim test.js test.ts
```

**what i see:**

<img width="565" alt="grafik" src="https://user-images.githubusercontent.com/25524993/81173111-cff91100-8f9f-11ea-9a5b-64150cde08ce.png">

**what i expect:**

to see `This expression is not callable.` in the `test.js` file as well as the `test.ts` file

**Comment by chemzqm** [comment]
It's expected for tsserver, send your feature request to https://github.com/microsoft/typescript
