### ISSUE TITLE
[tsserver 2686] [I] '_' refers to a UMD global, but the current file is a module.

### ISSUE THREAD

**Issue by shobhitsinghal624** [neoclide/coc-tsserver#149]
I've set `"allowUmdGlobalAccess": true` in my `tsconfig.json` file.
I'm still getting this warning:
```
[tsserver 2686] [I] '_' refers to a UMD global, but the current file is a module. Consider adding an import instead.
```
I don't get this error in VSCode.
I followed this PR & its related issue for reference: https://github.com/microsoft/TypeScript/pull/30776

**Comment by chemzqm** [comment]
Looks like you have `typescript.suggest.enabled` as `false` with VSCode.
