### ISSUE TITLE
Can't get completions options.

### ISSUE THREAD

**Issue by glepnir** [neoclide/coc-tsserver#150]
1. open a typescript file, then write these code. the `|` mean cursor here. `p.` doesn't show anything.
```typescript
class Person {
  age: number;
  constructor(age: number) {
    this.age = age;
  }
  run(): void {
    console.log(this.age);
  }
}

let p: Person = new Person(19);
p.|
```
2. this is tsserver log
[tsserver.log](https://github.com/neoclide/coc-tsserver/files/4610660/tsserver.log)

**Comment by chemzqm** [comment]
The response is correct, please try minimal vimrc.

**Comment by glepnir** [comment]
Ok. Thanks. found the problem.if config this will cause this problem, Works fine when remove this.
```json
  "emmet.includeLanguages": {
           "typescript" : "typescriptreact"
```
