### ISSUE TITLE
CPU usage by node peaks on open & makes vim unusable

### ISSUE THREAD

**Issue by thelehhman** [neoclide/coc-tsserver#151]
## Describe the bug

Vim hangs & is unusable when I open a javascript file and try to move around. This did not happen earlier. I'm not sure if its a bug or a limitation. 

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Open some javascript file, I opened a 20 KB file.

## Screenshots (optional)

<img width="663" alt="Screenshot 2020-05-12 at 9 37 32 PM" src="https://user-images.githubusercontent.com/2987087/81718116-fedc1f00-9498-11ea-9a0f-59fd9b2495de.png">
NOTE: I've checked that this is the node process that was launched by coc and not some other app.

**Comment by chemzqm** [comment]
Could be problem of node or some bad extension of coc.nvim

**Comment by thelehhman** [comment]
I have only 2 extensions coc-tsserver and coc-vetur. Also, I'm using the latest node (13.12) and Vim(8.2)

**Comment by chemzqm** [comment]
node 13 is expected to have this kind of issue.

**Comment by ngocketit** [comment]
Not only node 13, I have the same issue on Node 12. Basically unusable.
