### ISSUE TITLE
when does tsserver detect a commonjs module that can be converted?

### ISSUE THREAD

**Issue by dxuehu** [neoclide/coc-tsserver#152]
I get some inconsistent results sometimes- some require statements have a coc action associated that can es6ify the whole module, whereas others do not (right side in the ss)
Thank you!
<img width="1103" alt="Screen Shot 2020-05-14 at 3 18 07 AM" src="https://user-images.githubusercontent.com/485316/81923257-37abef00-9592-11ea-8ac3-491703e51396.png">

**Comment by chemzqm** [comment]
Don't know, but you can disable this kind of suggestions by configuring `"typescript.suggestionActions.enabled": false `

**Comment by dxuehu** [comment]
oh nevermind, i just tried moving the 'import promisify' down and now I get the suggestion on the right.

**Comment by chemzqm** [comment]
You can pickup fixes from codeActions.

**Comment by dxuehu** [comment]
sorry, can you elaborate?

**Comment by chemzqm** [comment]
Read readme of coc.nvim.

**Comment by dxuehu** [comment]
I have read it many times, I'm not sure what you mean. You mean updates to code actions (if this is a thing and separate from coc-tsserver), or just applying code actions? I have no issues applying the actions, but it doesn't always have this suggestion and I have not figured out the pattern.

**Comment by chemzqm** [comment]
It's not the place for question with tsserver, use https://stackoverflow.com/ instead.
