### ISSUE TITLE
TypeScript errors in JavaScript files

### ISSUE THREAD

**Issue by alextes** [neoclide/coc-tsserver#153]
Something appears to have changed, maybe it's my local configuration but let's see if this is expected behavior.

file.js
```
const fn = (arg) => undefined;
```

I get the error:
```
Error [tsserver 7006] Parameter 'arg' implicitly has an 'any' type.
```

When running:
```
yarn tsc --allowJs --noEmit file.js
```

No implicit any error, and why would there be? This is a JS file.

Any idea how I could get back to tsserver checking js files but without giving me errors that only apply to ts files?

For completeness sake, there is no tsconfig in the above example, my coc-settings.json only contains these settings that concern tsserver:
```
  "typescript.referencesCodeLens.enable": false,
  "javascript.referencesCodeLens.enable": false,
```

**Comment by chemzqm** [comment]
Checkout https://github.com/neoclide/coc-tsserver#troubleshooting

**Comment by alextes** [comment]
Thanks Qiming, found the culprit: https://github.com/fannheyward/coc-deno/issues/25
