### ISSUE TITLE
Cannot find module error (internal or external) 

### ISSUE THREAD

**Issue by guilhermedeandrade** [neoclide/coc-tsserver#154]
I've noticed that `coc-tsserver@1.5.1` started to display errors for all module imports, either internal or external:

<img width="554" alt="image" src="https://user-images.githubusercontent.com/8797405/82313016-b2747000-99bf-11ea-8577-afd30c69fdc6.png">

The error message is: `[tsserver 2307] [E] Cannot find module <import-path>`

CocInfo:

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/8797405/82313225-fe271980-99bf-11ea-83c2-84e18d5b5f37.png">

Additional info:

Another problem, but maybe it should have its own issue, is that types aren't being checked properly

<img width="1230" alt="image" src="https://user-images.githubusercontent.com/8797405/82313890-e56b3380-99c0-11ea-8a7f-a00244eeb8f8.png">

<img width="367" alt="image" src="https://user-images.githubusercontent.com/8797405/82313431-3b8ba700-99c0-11ea-916e-654d3f1e35e0.png">

I guess this is happening because the import is not "working" fot the tsserver and then the interface that is being imported isn't considered. 

I've already tried reinstalling it. Also, this is not a problem with this specific file or project. It is happening in all the projects I've tried so far. I do not have any similar issue when working with the same files on VSCode.

**Comment by fannheyward** [comment]
Do you install `coc-deno`? typescript-deno-plugin has some problem with non-deno project. You should to disable it in `:CocList extensions`.

**Comment by guilhermedeandrade** [comment]
That was exactly the problem @fannheyward! Thanks! I'd never have guessed it

**Comment by omulmicsinegru** [comment]
FWIW Disabling didn't work for me. I had to uninstall it .

**Comment by padulkemid** [comment]
yup can confirm, disabling didn't work on me either, I did the same as @omulmicsinegru.

**Comment by jamespottsSAFC** [comment]
I just had the same problem that was only fixed by uninstalling coc-deno

**Comment by jhwheeler** [comment]
Uninstalling coc-deno works great! Was really racking my head over this one 😆

**Comment by marcmarina** [comment]
I have this issue, and it's not because `coc-deno` as I don't have it installed.

**Comment by FactoREAL** [comment]
> I have this issue, and it's not because `coc-deno` as I don't have it installed.

I resolved this problem by updating the plugins using :PlugUpdate

**Comment by jeffrey-l-turner** [comment]
Same issue here. I uninstalled. Trying to figure out a way to conditionally run/install `coc-deno` only on `deno` projects.

**Comment by jeffrey-l-turner** [comment]
> Same issue here. I uninstalled. Trying to figure out a way to conditionally run/install `coc-deno` only on `deno` projects.

I finally got my `coc-deno` setup working. Here's what I did. I put this in my `init.vim`:
```" Per Project deno check and setup" {{{
function! InstallnEnableCocDeno()
  :CocInstall coc-deno
  :echom 'Detected deno project; Remember to make sure coc-deno is enabled'
endfunction

function! DisableCocDeno()
  :CocUninstall coc-deno
"  :echom 'Did not detect deno configuration within project; coc-deno disabled'
endfunction

function! SetupDeno()
  let s:cocSettings = 'coc-settings.json'
  let s:enableDenoKey = 'deno.enable'
  let s:settingsFile = findfile(s:cocSettings, '.vim;') " search for coc settings file project directory
  if s:settingsFile ==? '.vim/coc-settings.json' " only run logic if at project root
    let s:denoFile = readfile(s:settingsFile)
    if !empty(s:denoFile)
      let s:enableDenoDict = json_decode(s:denoFile)
      if has_key(s:enableDenoDict, s:enableDenoKey)
        let s:denoEnable = s:enableDenoDict[s:enableDenoKey]
        if !empty(s:denoEnable) 
          if !empty(s:denoEnable) && s:denoEnable ==? 'true'
            :call InstallnEnableCocDeno()
          else
            :call DisableCocDeno()
          endif
        else
          :call DisableCocDeno()
        endif
      else
        :call DisableCocDeno()
      endif
    endif
  else
    :call DisableCocDeno()
  endif
endfunction

augroup SetupDeno
  autocmd!
  autocmd VimEnter,DirChanged * :call SetupDeno()
augroup end
" " }}}
```
& then `git add`ed a `.vim/coc-settings.json` to my `deno` projects with:
```
{
  "deno.enable": true,
  "deno.lint": true,
  "deno.codeLens.reference": true,
  "deno.codeLens.referencesAllFunctions": false
}
```
it seems to be working well for me. I may make so more tweaks as I experiment more with it.

**Comment by fannheyward** [comment]
The new release of coc-deno has fixed this.
