### ISSUE TITLE
AutoComplete does not include file extension

### ISSUE THREAD

**Issue by utrumo** [neoclide/coc-tsserver#155]
I added to my coc-settings.json
` "javascript.preferences.importModuleSpecifierEnding": "js"`
In suggest popup i see file with extension, but after pressing enter it autocompletes file name without it.
Now the suggest looks like this:
![suggestWithExtension](https://user-images.githubusercontent.com/22612354/82497961-d6d36800-9af7-11ea-9994-3b40bf5a9825.png)
But autocomplete result without extension:
![AutocompleteResultWithoutExtension](https://user-images.githubusercontent.com/22612354/82498082-0c785100-9af8-11ea-822d-ce7e857f7c86.png)

**Comment by chemzqm** [comment]
Possible old tsserver module.

**Comment by chemzqm** [comment]
It works for auto import only, and only work with typescript >= 2.9

**Comment by chemzqm** [comment]
If you think it's bug, send your report to https://github.com/Microsoft/typescript
