### ISSUE TITLE
Feature Request: Ignore specific tsserver codes

### ISSUE THREAD

**Issue by kibs** [neoclide/coc-tsserver#156]
Would it be possible to add a configuration option for disabling specific tsserver disagnostics/suggestions codes.

My specific usecase, is that I want to ignore 7016 - Could not find a declaration file for module ...

But instead of disabling all suggestions, I would like to just ignore that. But maybe a configuration for disabling specific codes, could be more generic and helpful in other cases as well?

**Comment by chemzqm** [comment]
PR welcome.

**Comment by kibs** [comment]
Cool, would you implement it here?

https://github.com/neoclide/coc-tsserver/blob/master/src/server/features/diagnostics.ts#L145

**Comment by chemzqm** [comment]
No, I don't like the idea to ignore specific diagnostics, it can be useful, the feature should be provided by configuration of language server, not client.

**Comment by kibs** [comment]
tsserver doesn't seem to support this, from what I can find.

If it is an opt in feature, would it be that bad, you are already doing specific checks for code 6133

**Comment by chemzqm** [comment]
It's same as VSCode, we will support ignore 7016 when VSCode support it.

**Comment by chemzqm** [comment]
Use
```
  "javascript.suggestionActions.enabled": false,
  "typescript.suggestionActions.enabled": false,
```
