### ISSUE TITLE
tsconfig.json is ignored

### ISSUE THREAD

**Issue by L1Q** [neoclide/coc-tsserver#157]
coc warns me about "implicit any" errors even though noImplicitAny is set to false in tsconfig.json
I compile my typescript project by running ``tsc -w`` in project root and it does not produce any errors.
coc will produce errors no matter what path I use when opening a .ts file.
vs code is smart enough to find my tsconfig.json
Ideally I'd like it to look for tsconfig.json text to my .ts file even if I'm opening it from outside of typescript project directory.

Is this intended behavior?

**Comment by chemzqm** [comment]
Start your vim in that folder

**Comment by L1Q** [comment]
> coc will produce errors no matter what path I use when opening a .ts file

> Start your vim in that folder

I tried that. made no difference.

**Comment by chemzqm** [comment]
I can't reproduce, checkout https://github.com/neoclide/coc-tsserver/blob/master/Readme.md#troubleshooting

**Comment by khughitt** [comment]
In case anyone else is running into the same problem, I was getting similar warnings when I had attempting to use `ES2023` as the value for `compilerOptions.target`, which was one of the options nvim suggested when the field was empty.

Upon running `tsc -w` manually, however, it suggested that this was _not_ a valid value to use:

```
tsconfig.json:3:15 - error TS6046: Argument for '--target' option must be: 'es3', 'es5', 'es6', 'es2015', 'es2016', 'es2017', 'es2018', 'es2019', 'es2020', 'es2021', 'es2022', 'esnext'.
```

Changing the setting to `es2022` fixed the issue.
