### ISSUE TITLE
[tsserver 2584] [E] Cannot find name 'console'

### ISSUE THREAD

**Issue by cyril2day** [neoclide/coc-tsserver#158]
Hi, this error message is persisting for quite a while now and somehow I want to eliminate it as it gets annoying. It shows on every line that has console.log. This is my tsconfig.json:

{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "lib": [
      "es6",
      "dom"
    ],
    "outDir": "./public",
    "rootDir": "./src",
    "esModuleInterop": true,
    "skipLibCheck": false,
    "pretty": true,
    "moduleResolution": "node",
    "forceConsistentCasingInFileNames": true
  },
  "include": [
    "src"
  ]
}

**Comment by chemzqm** [comment]
Issue of your configuration

**Comment by cyril2day** [comment]
> Issue of your configuration

can you please elaborate where in my config might cause it?
