### ISSUE TITLE
Some flags on tsconfig.json not read

### ISSUE THREAD

**Issue by cyril2day** [neoclide/coc-tsserver#159]
Hello, just want to follow up on issue **#158** which you closed earlier. There is no problem with my **tsconfig.json**. The same config worked, all I had to do is run *npm install typescript* on the local project folder. Guess the bundled typescript in this extension emits the weird behavior as it's not reading config file properly.

**Comment by chemzqm** [comment]
Can't reproduce, please check https://github.com/neoclide/coc-tsserver/blob/master/Readme.md#troubleshooting
