### ISSUE TITLE
Getting duplication and redeclaration errors

### ISSUE THREAD

**Issue by shin-ra** [neoclide/coc-tsserver#162]
When I open a JS file to check the code generated I get the following errors on the TS files
`Duplicate function implementation.[tsserver: 2393]`
`Cannot redeclare block-scoped variable 'var-name'[tsserver: 2451]`
The errors only go away after deleting the JS files or reloading Vim without the JS files being open

Maybe I just don't know what to search for but is there a way to turn off just these types of errors?

**Comment by chemzqm** [comment]
Sure, please checkout https://github.com/neoclide/coc-tsserver#configuration-options
