### ISSUE TITLE
Suppress tsserver errors in floating/preview window

### ISSUE THREAD

**Issue by sbernheim4** [neoclide/coc-tsserver#163]
Is there a way to suppress the following message from the language server?

`[tsserver 80004] [I] JSDoc types may be moved to TypeScript types.`

This appears when I'm working on a typescript file using JSDocs. 
I'm hoping there is an easy way to suppress or filter out this particular message. This message does not appear in VSCode. The above message appears when my cursor is on the jsdocs, or any part of the function. 

Example Function:
```ts
/**
 * @description Returns a string of a persons name and age
 * @param {String} name The name of the person
 * @param {Number} age The age of the person
 * @returns {String} A string message
 */
function foo(name: string, age: number) {
    return name + ' is ' + number + ' years old';
}
```

`coc-settings`:
```json
{
    "coc.preferences.extensionUpdateCheck": "weekly",
    "coc.preferences.useQuickfixForLocations": true,
    "eslint.autoFix": true,
    "eslint.autoFixOnSave": true,
    "eslint.filetypes": [
        "javascript",
        "javascriptreact",
        "typescript",
        "typescriptreact"
    ],
    "javascript.validate.enable": true
}
```

Please let me know if you need any more information. Happy to forward along a copy of CocInfo or anything else.

Thanks so much

**Comment by chemzqm** [comment]
Read readme

**Comment by sbernheim4** [comment]
I was hoping there was a way to filter out just this message as I might want to see others that are reported. 

I can use `typescript.suggestionActions.enabled: false` to disable **all** suggestions if that's what you're referring to but I was hoping for a filter option as well. I didn't an option like that that listed in the readme

**Comment by chemzqm** [comment]
We won't provide such option, you can send feature request to typescript project

**Comment by sbernheim4** [comment]
Sounds good, thank you for the quick response

**Comment by sigmaSd** [comment]
It would be great if you rename this issue to `Filter individual tsserver warnings/info` and tag it with wont-fix, just so its more searchable and the status immediately understood

nvim lsp provides this with `filter_out_diagnostics_by_code`

**Comment by cincodenada** [comment]
Thanks for the pointer @sigmaSd, I was curious about the built-in LSP support anyway and this got me to finally check it out. For future searchers, the option referenced is actually part of [nvim-lsp-ts-utils](https://github.com/jose-elias-alvarez/nvim-lsp-ts-utils), which adds some utilities to the core LSP support.
