### ISSUE TITLE
How to debug "X" not auto-importing / suggesting a place to auto-import from?

### ISSUE THREAD

**Issue by NullVoxPopuli** [neoclide/coc-tsserver#165]
I have mixed results with auto-importing -- probably depending on a variety of things, for example:

`@action` here has no correct suggestion
![image](https://user-images.githubusercontent.com/199018/84558462-00e80680-ad01-11ea-9bba-3912bb9c22a3.png)

even though, the commented import line is clearly recognized by typescript:
![image](https://user-images.githubusercontent.com/199018/84558480-2248f280-ad01-11ea-9352-c9adac33a31a.png)

Here is an example of what I expect to happen (in the same file even, but with a different import):
![image](https://user-images.githubusercontent.com/199018/84558504-4dcbdd00-ad01-11ea-9e35-a4d2b9983f8b.png)

So, how do you debug this sort of behaviour?

**Comment by chemzqm** [comment]
It's known issue of tsserver, https://github.com/microsoft/TypeScript/issues/39048
