### ISSUE TITLE
add javascript library support

### ISSUE THREAD

**Issue by laoshaw** [neoclide/coc-tsserver#168]
is it possible to add some javascript libraries to tsserver for autocompletion, say, jquery, lodash, assuming the d.ts file is available, how to do that?

further, is d.ts file mandatory for tsserver if adding library as mentioned above works?

**Comment by chemzqm** [comment]
It should work if tsserver find them, read doc of tsserver.

**Comment by laoshaw** [comment]
can you kindly give some pointer on where to look? I read the doc and wiki still have no idea.

or do i need put jquery in a package.json and npm install?

**Comment by chemzqm** [comment]
No, it's not problem of thiss tool.

**Comment by jonmast** [comment]
For anyone else stumbling on this page, here's the reference on how to configure tsserver https://www.typescriptlang.org/docs/handbook/tsconfig-json.html
