### ISSUE TITLE
Can't initialize coc-tsserver

### ISSUE THREAD

**Issue by lamartire** [neoclide/coc-tsserver#169]
Hello! After the last `coc.nvim` update I'm always receiving an error on `coc-tsserver` update:

```
[coc.nvim] Error on load extension from "/home/lamartire/.config/coc/extensions/node_modules/coc-tsserver": ENOTDIR: not a directory, open '/home/lamartire/.config/coc/extensions/nod
e_modules/coc-tsserver/package.json'
```

How I can solve it? I'm not sure, that problem is in `coc.nvim`, may be it relates only for `coc-tsserver` package.

**Comment by chemzqm** [comment]
Reinstall extension.

**Comment by lamartire** [comment]
Just reinstalling not helps. Found next solution:

```
rm -rf ~/.config/coc/extensions
mkdir ~/.config/coc/extensions
touch ~/.config/coc/extensions/package.json
echo "{}" >> ~/.config/coc/extensions/package.json
```
Then reinstall all extensions.
