### ISSUE TITLE
[coc.nvim] engine coc & vscode not found

### ISSUE THREAD

**Issue by pietariheinovincit** [neoclide/coc-tsserver#17]
Hi

Upon start of Vim, I get this error message:
[coc.nvim] engine coc & vscode not found in /home/xxx/.config/coc/extensions/node_modules/typescript/package.json

I have installed coc through Plug and coc-tsserver via :CocInstall. I am not using nvm.

What should I do? Can I provide some additional info?

Thanks a million!

**Comment by chemzqm** [comment]
Remove `typescript` from the file `/home/xxx/.config/coc/extensions/package.json`.

**Comment by pietariheinovincit** [comment]
Thank you. It removed the problem.

Is that something I have done myself - misconfigured in some way - or will this error just re-appear upon update/reinstall/whatever?

**Comment by chemzqm** [comment]
Looks like you have run `:CocInstall typescript`
