### ISSUE TITLE
How I could set coc-tsserver to show error on vim command line?

### ISSUE THREAD

**Issue by Mdsp9070** [neoclide/coc-tsserver#173]
Coc-tsserver works like a charm, but I didn't find a option to show the warning or error on vim command line. I tought this was the default value, but nothing is shown. I also increased the height of command line but no difference. There's any option I can modify to get this?

![Screenshot from 2020-07-04 11-43-00](https://user-images.githubusercontent.com/44469426/86628484-53cf7980-bfa0-11ea-925f-309dda1a69ac.png)

**Comment by chemzqm** [comment]
No such option.
