### ISSUE TITLE
Obcene amount of memory being allocated over time

### ISSUE THREAD

**Issue by fabricio7p** [neoclide/coc-tsserver#174]
Currently using VIM 8.1, CoC with TSserver on Arch linux

As you can see from the screenshot, CoC Tsserver extension goes up filling the memory and apparently can't release it.
I work with web development and after some time coding, everytime i open a .js file i see my CPU spike to 80º C... Which i noticed to be CoC's fault again.

It can easily fill up the whole memory after a day of coding. I've done it.

![2020-07-07-074901_1920x1080_scrot](https://user-images.githubusercontent.com/46208058/86770305-df8be900-c026-11ea-9cb3-95623a2b5d40.png)

My machine fresh restarded barely uses 300mbs of ram. So this is definely an issue. Maybe i got configuration wrong?
What can i share here for debugging?

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc-tsserver#configuration-options

https://github.com/neoclide/coc.nvim/wiki/Using-the-configuration-file

Configure your jsconfig.json and tsconfig.json or ask https://github.com/microsoft/TypeScript

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc.nvim/issues/2043
