### ISSUE TITLE
Libs not included from compiler options

### ISSUE THREAD

**Issue by alexandermccormick** [neoclide/coc-tsserver#175]
# The Problem
Coc-tsserver does not seem to register `compilerOptions.lib` from local `tsconfig.json`.

# Steps to reproduce
1. Create a `tsconfig.json` file populated with the following:
```
{
  "version": "2.0.2",
  "compilerOptions": {
    "module": "es6",
    "lib": [ "dom" ],
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "target": "es6",
    "noImplicitAny": true,
    "sourceMap": true,
    "outDir": "dist",
    "baseUrl": "./",
    "types": [ "chrome" ],
    "paths": {
      "*": [
        "node_modules/*"
      ]
    }
  },
  "include": [ "src/*" ],
  "exclude": [ "dist/*" ]
}
```
2. Create a file with the corresponding path of `./src/main.ts`, populated with the following:
```
const el: HTMLInputElement = document.getElementById("someId");
```
# Expected Action
No tsserver errors should occur

# Actual Action
Tsserver throws the following errors: 
1. `[tsserver 2304] [E] Cannot find name 'HTMLInputElement'.`
2. `[tsserver 2584] [E] Cannot find name 'document'. Do you need to change your target library? Try changing the `lib` compiler option to include 'dom'.`

### Additional notes:
I did open the project up in VSCode, and there were no issues. Although I suspect that might be for other reasons, not related.

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc-tsserver#troubleshooting
