### ISSUE TITLE
Question: Is it possible to run this for other language servers

### ISSUE THREAD

**Issue by tjdevries** [neoclide/coc-tsserver#177]
Hey @chemzqm Thanks for all the work you're doing with coc.

I'm using the builtin lsp for Neovim though and was wondering if you thought it'd be possible to manually install this and use this language server for other language server clients? This seems to be one of the best and most maintained typescript servers out there, so I was hoping to use it elsewhere :)

If not, that's fine, but figured I should ask.

Thanks!

**Comment by chemzqm** [comment]
No, it uses api of coc.nvim
