### ISSUE TITLE
auto update import paths does not work

### ISSUE THREAD

**Issue by alisajadih** [neoclide/coc-tsserver#182]
hi im using macvim with plugin coc.nvim and NERDTree.
when i move a node with NERDTree Options for moving files, my imports doesn't update. and i should manually update them with COCSearch. I tried to move file without using nerdtree,but still this option doesn't work for me, i dont know why. Is it a problem with macvim?
there is my CocCofing : 
```
    { 
       "eslint.autoFixOnSave": true, 
       "eslint.filetypes": [ 
         "javascript", 
         "javascriptreact", 
          "typescript", 
          "typescriptreact" 
        ], 
        "prettier.disableSuccessMessage": true, 
        "suggest.noselect": false,           
        "diagnostic.messageDelay": 100,      
        "diagnostic.refreshOnInsertMode": true, 
        "typescript.updateImportsOnFileMove.enable": true 
     } 
```

**Comment by chemzqm** [comment]
It requires watchman to detect file changes, read readme.

**Comment by lnrssll** [comment]
I have the same issue and watchman is installed and in my path. is there some kind of additional config required?
