### ISSUE TITLE
Feature: yank type at cursor

### ISSUE THREAD

**Issue by schontz** [neoclide/coc-tsserver#184]
Many times I need to get the type of a variable and use it somewhere. For example:

```ts
const foo = getSomeData();

bar(foo); // bar needs to be written to expect typeof foo

// start writing it:
function bar(data: /* I need the type of foo here */) {
 // ...
}
```

My current workflow is to put my cursor on `const foo`, press Shift-K to view the type, remember it, and then updated `data`'s type. It would be great to be able to yank the type of the variable under the cursor so I can paste it there instead.

**Comment by chemzqm** [comment]
Move your cursor to the window by `<C-w>p` and yank.

**Comment by schontz** [comment]
Awesome. Thank you @chemzqm
