### ISSUE TITLE
Auto import uses CommonJS modules rather than ES6 modules

### ISSUE THREAD

**Issue by raph90** [neoclide/coc-tsserver#185]
I have a project with an eslintrc.js that looks like this: 

`module.exports = {
    "env": {
        "browser": true,
        "es6": true
    },
    "extends": "eslint:recommended",
    "globals": {
        "Atomics": "readonly",
        "SharedArrayBuffer": "readonly"
    },
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true
        },
        "ecmaVersion": 2018,
        "sourceType": "module"
    },
    "plugins": [
        "react"
    ],
    "rules": {
    }
};`

I have coc-eslint and coc-tsserver installed. 

When I type in an exported function name, coc suggests the function. I hit enter, and it imports it, but using CommonJS syntax. The rest of the project is in ES6 module syntax, so I don't know why this is happening. It would be great to know how to configure coc, tsserver or coc-eslint to ensure that ES6 modules are used.

**Comment by chemzqm** [comment]
Configure your jsconfig.json
