### ISSUE TITLE
No CSS completions on javascriptreact file

### ISSUE THREAD

**Issue by Moshem123** [neoclide/coc-tsserver#186]
I'm expecting to have [coc-css](https://github.com/neoclide/coc-css) completions on `javascriptreact` file type:
```
import React from 'react';
import styled from 'styled-components';

const Header = styled.h1`
  color: blue;
  text-decoration: underline;
  cursor: pointer;
`

function App() {
  return (
    <Header>
      Hello World!
    </Header>
  );
}

export default App;
```

I have no completions inside the `styled.h1` component.
Nothing special in the config file.
How can I make `coc-tsserver` complete css?
Thanks

**Comment by chemzqm** [comment]
There is tsserver for styled component, can't remember the name.

**Comment by Moshem123** [comment]
Amazing here it is:
https://github.com/fannheyward/coc-styled-components
Thanks.
