### ISSUE TITLE
Configuration option for tsserver process?

### ISSUE THREAD

**Issue by xorander00** [neoclide/coc-tsserver#189]
Related to #100  
  
Is there a way to configure coc-tsserver to connect to and use a separately started tsserver process?  I'm in the same boat as issue #100.  I frequently start/stop/switch between multiple vim instances.  Some of my projects are larger, so it does add a 5-10 second delay between launching vim and seeing the diagnostics.  
  
I read the docs, but unless I missed it, there's no way to currently do this.  I'd like to make sure that's indeed the case.  I don't mind starting and stopping a separate instance of tsserver for coc-tsserver to use.

**Comment by chemzqm** [comment]
Not possible, make your project smaller and use ssd

**Comment by xorander00** [comment]
Would a PR for this be open for merging or would it be automatically rejected?  I'm asking because if it would be rejected, then I can save myself some time.  
  
As far as making the project smaller, yes that would be nice, but it's not really an option.  The hardware is already using SSDs (two in fact), and has 64GB of RAM.  Slow hardware is not the issue.  It's just the number of types it has to discover and cache can get large.  Having a shared, long-lived instance of tsserver would likely help solve the issue after the initial launch.

**Comment by chemzqm** [comment]
You can try it out and I would merge the PR if it's stable
