### ISSUE TITLE
how to specify workspace tsc

### ISSUE THREAD

**Issue by hesxenon** [neoclide/coc-tsserver#19]
I can't seem to figure out how to tell coc-tsserver to use the local typescript install instead of the global one.

How would I go about that?

**Comment by chemzqm** [comment]
It doesn't use global typescript module, but your local typescript module when possible, if not found, it use bundled tsserver.

**Comment by chemzqm** [comment]
Make sure typescript inside node_moudles of your workspace folder: https://github.com/neoclide/coc.nvim/wiki/Using-workspaceFolders
