### ISSUE TITLE
Feature request/question: Possibility to run one instance of tsserver for multiple instances of nvim

### ISSUE THREAD

**Issue by swapsCAPS** [neoclide/coc-tsserver#190]
Is it possible to run multiple instances of nvim using one tsserver?  
Using tmux + vim in a microservices environment has me open a lot of projects. Each service in a tmux window with an nvim pane and some logs/cli panes.  
Sometimes I have more than 10 tsservers running, each of which consumes ~250 MB of RAM.

**Comment by chemzqm** [comment]
It's not possible, unfortunately.
My advice is separate your project to smaller projects

**Comment by swapsCAPS** [comment]
So I have even more editors open! :sweat_smile: 
JK. Okay cool, too bad. Thanks anyways for the plugin!
