### ISSUE TITLE
Does not find tsconfig.json when in different directory

### ISSUE THREAD

**Issue by Koxiaet** [neoclide/coc-tsserver#191]
If I have `tsconfig.json` and `src/main.ts`, `nvim main.ts` from within `src` fails to load the `tsconfig.json`, but `nvim src/main.ts` from the project root succeeds. In particular the `open` command sets `projectRootPath` as the current working directory instead of the actual project root. This can be solved by simply not setting `projectRootPath` and having `tsserver` find the config file.

**Comment by chemzqm** [comment]
Read wiki of coc.nvim

**Comment by Koxiaet** [comment]
@chemzqm I did, there's nothing related to this there. This problem is easily solved by not restricting where tsserver looks for the tsconfig file.

**Comment by chemzqm** [comment]
It's by design.  You need checkout your rootPatterns

**Comment by Koxiaet** [comment]
@chemzqm `rootPatterns` only exists when `languageServer` is used in `coc-settings.json` - when plugins are installed from `CocInstall` they don't use `languageServer` if I'm not mistaken. I have also seen other plugins be able to find their root file from whereever.

**Comment by chemzqm** [comment]
Your cwd is used when rootPattern matches

**Comment by Koxiaet** [comment]
@chemzqm So how do you recommend I have the ability to open files from within a subdirectory of my project? Having to type out `:e src/some_file.ts` every time is a pain. I did also notice that neither [coc-eslint](https://github.com/neoclide/coc-eslint) or [coc-rust-analyzer](https://github.com/fannheyward/coc-rust-analyzer) have this problem - they are able to find my `.eslintrc` and `Cargo.toml` whereever it is. Do you think you could perhaps support it here too?

**Comment by chemzqm** [comment]
You need figure out why src folder is used for workspace folder first

**Comment by Koxiaet** [comment]
@chemzqm Thank you, it works now! I eventually realized that it was [this page](https://github.com/neoclide/coc.nvim/wiki/Using-workspaceFolders) you were referring to on the coc wiki (which isn't actually linked on the home page, which is why I struggled to find it). Please add that link to the home page, and also a note about it in this repo's Readme, because other people might install this software expecting it to "just find the root file" like other coc extensions do.
