### ISSUE TITLE
Suggestions are shown even when they are disabled

### ISSUE THREAD

**Issue by Koxiaet** [neoclide/coc-tsserver#192]
Here is an excerpt from my `coc-settings.json`:

```
{
    ...
    "typescript.suggestionActions.enabled": false
}
```

And yet I still get suggestions reported from `tsserver` displayed, e.g. `[tsserver 6133] [I] 'x' is declared but its value is never read.` I am editing a Typescript file.

**Comment by chemzqm** [comment]
It's not part of suggest actions

**Comment by Koxiaet** [comment]
@chemzqm It is, I checked the logs:

```
Info 55   [18:10:3.801] event:
    {"seq":0,"type":"event","event":"syntaxDiag","body":{"file":"/path/to/src/index.ts","diagnostics":[]}}
Info 56   [18:10:3.802] event:
    {"seq":0,"type":"event","event":"semanticDiag","body":{"file":"/path/to/src/index.ts","diagnostics":[]}}
Info 57   [18:10:3.802] event:
    {"seq":0,"type":"event","event":"suggestionDiag","body":{"file":"/path/to/src/index.ts","diagnostics":[{"start":{"line":1,"offset":11},"end":{"line":1,"offset":12},"text":"'y' is declared but its value is never read.","code":6133,"category":"suggestion","reportsUnnecessary":true},{"start":{"line":2,"offset":6},"end":{"line":2,"offset":7},"text":"'z' is declared but its value is never read.","code":6133,"category":"suggestion","reportsUnnecessary":true}]}}
```

The output looks like this:

![Code showing warning from tsserver](https://user-images.githubusercontent.com/38139193/88953116-56b44600-d290-11ea-91f5-160641457876.png)

**Comment by Koxiaet** [comment]
@chemzqm Can this be reopened please?

**Comment by chemzqm** [comment]
If you think it belongs suggestActions, you have to    send your feature request to typescript project, it's controlled by tsserver

**Comment by Koxiaet** [comment]
@chemzqm I showed you the log, it is a suggestion.

**Comment by chemzqm** [comment]
It's intended, same as VSCode, you have to use `typescript.showUnused` configuration.

**Comment by Koxiaet** [comment]
Thanks a lot for helping! It does look like a suggestion though so perhaps you should add a note to the README explaining that `suggestionActions`doesn't include unused suggestions.
