### ISSUE TITLE
Problematic filetype detection

### ISSUE THREAD

**Issue by InterAl** [neoclide/coc-tsserver#198]
This plugin does not work for typescript filetypes other than the closed list defined [here](https://github.com/neoclide/coc-tsserver/blob/master/src/server/utils/languageModeIds.ts). For example, it does not work for this filetype: typescript.javascript. However, it does work for typescript.jsx. Makes no sense. Instead of checking against a closed list containing all possible combinations (which is really impossible, TBH), I believe you should simply check if the filetype contains a "typescript" FT, or even better, to allow this list to be configurable/extendable.

**Comment by antonk52** [comment]
Search terms: compound filetypes

The above solution works great. It took me some time to discover it. Hope adding "compound filetypes" to this page will help others to find it quicker.
