### ISSUE TITLE
How to activate ES6 arrow functions in symbols list?

### ISSUE THREAD

**Issue by bfulop** [neoclide/coc-tsserver#2]
Hello,

First, congratulations for your CoC plugin, it's a fantastic extension for Neovim!

I just noticed that the coc-tsserver does not list functions defined with the ES6 arrow syntax:

```javascript
function normalfunc (a,b) {
  return a + b
}

const arrofunc = (a,b) => {
 return a + b
}
```

If I do a symbols listing, then only `normalfunc` fill be listed.

Is there a way to configure the ES6 syntax?

**Comment by chemzqm** [comment]
There is `arrofunc` is returned from API `:call CocAction('documentSymbols')`.
But it's filtred since it's a `Variable` kind to avoid too much items.

**Comment by bfulop** [comment]
Yes, I'm using

```
nnoremap <silent> sl :<C-u>Denite coc-symbols<cr>
```

to get a list of document symbols.

Is there I way to configure to have the `Variable` kind included? I'm new to both CoC and Denite (just started using them both yesterday!).

**Comment by chemzqm** [comment]
No option for that, but you ou can remove:
```
            if item['kind'] == 'Variable':
                continue
```
from `coc.nvim/rplugin/python3/denite/source/symbols.py#L44`.

**Comment by bfulop** [comment]
Great thanks, it's working ! :)

**Comment by nomasprime** [comment]
Ran into the exact same issue.

Works with nvim-lspconfig out of the box. Shouldn't this be fixed in coc?
