### ISSUE TITLE
Question: How to ignore node_modules in workspaceSymbols

### ISSUE THREAD

**Issue by JoosepAlviste** [neoclide/coc-tsserver#20]
When using `CocList -I -N workspaceSymbols`, files from `node_modules` are also included in the results:

![image](https://user-images.githubusercontent.com/9450943/56309544-76cefd00-6152-11e9-9e5a-a5b50689ba6f.png)

Is it possible to only search for symbols in "my" code (ignoring libraries)? With a larger project with many dependancies it can be very slow to search for symbols (it even times out after 5 seconds).

Here is my very minimal config, maybe I'm missing some config option:

```
call plug#begin('~/.vim/plugged')

Plug 'leafgarland/typescript-vim'
Plug 'neoclide/coc.nvim', {'do': { -> coc#util#install()}}

call plug#end()

nnoremap <silent> <space>s  :<C-u>CocList -I -N symbols<cr>
```

**Comment by chemzqm** [comment]
No such option with tsserver https://github.com/Microsoft/TypeScript/blob/78b095647477b6f47d68f72a96252829e61e437c/src/server/protocol.ts#L2618.

Need to use a tag based project symbol search then.

Will add a tag list to coc-lists extension.

**Comment by JoosepAlviste** [comment]
Oh, alright, thanks. I wonder how VSCode does it though? I think the shortcut cmd+t is the default shortcut for symbol searching which ignores node modules.

Anyways, I use FZF for tag navigation
so I can get by without it being in coc-lists.

**Comment by chemzqm** [comment]
Looks like it filter filepath contains node_modules at client side.

**Comment by chemzqm** [comment]
No, VSCode doesn't filter node_modules, should be symbol not found in node_modules.

**Comment by louisrli** [comment]
I'm not sure if things have changed since this issue but does coc-lists excludePatterns solve this?

I tried it with `"**/node_modules/**` to no avail. 

> list.source.files.excludePatterns: Minimatch patterns that should be excluded., default: []

**Comment by louisrli** [comment]
Never mind, I found this: https://github.com/neoclide/coc.nvim/issues/1803
