### ISSUE TITLE
Is there a NeoVim command that I can run to add missing import statements?

### ISSUE THREAD

**Issue by SnowCone161803** [neoclide/coc-tsserver#201]

**Comment by JovanShandro** [comment]
This would be extremely useful.

**Comment by chemzqm** [comment]
Invoke codeAction and find `Add all missing imports.`

**Comment by JovanShandro** [comment]
@chemzqm  Thank you for the reply.

Sorry to ask, but what do you mean by codeAction?
Is it referring to a :CocAction? The only Coc command I managed to find regarding imports is editor.action.organizeImports.

Thank you!

**Comment by chemzqm** [comment]
```
" Applying codeAction to the selected region.
" Example: `<leader>aap` for current paragraph
xmap <leader>a  <Plug>(coc-codeaction-selected)
nmap <leader>a  <Plug>(coc-codeaction-selected)
```

**Comment by hoschi** [comment]
From my findings this only works in TypeScript projects, in my JavaScript projects it doesn't work.

**Comment by chemzqm** [comment]
@hoschi yes, it's limitation of tsserver.
