### ISSUE TITLE
Exclude file watch for node_modules

### ISSUE THREAD

**Issue by unnsteinngardars** [neoclide/coc-tsserver#202]
Sorry if this does not belong here as an issue but I am wondering if there is any way to exclude folders like `node_modules` from the file watcher?

**Comment by chemzqm** [comment]
You have to send this feature request to https://github.com/microsoft/TypeScript first.

**Comment by unnsteinngardars** [comment]
> You have to send this feature request to https://github.com/microsoft/TypeScript first.

Thanks for the answer!
