### ISSUE TITLE
Auto import broken for typescript 4.0.x

### ISSUE THREAD

**Issue by insidewhy** [neoclide/coc-tsserver#203]
Tried to auto-import `Lexeme` in a project that uses tsc `4.0.2`. Ended up with an import line that looks like this:

```typescript
import {
  Grammar,
  TreeRule,
  Rule,
  Expression,
  TreeExpression,
  Characters,
  Repetition,, Lexeme
} from './tbpegByHand'
```

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
