### ISSUE TITLE
Support Neovim LSP, succeed typescript-language-server

### ISSUE THREAD

**Issue by roginfarrer** [neoclide/coc-tsserver#204]
As of Q3 2020, coc-tsserver is the only actively-maintained LSP implementation for TypeScript. I wonder if there's an opportunity or interest to divorce the coc implementation with the LSP implementation, exposing the latter to the nascent Neovim LSP or other interested consumers.

To elaborate, the most prevalent LSP implementations for TypeScript is [`typescript-language-server`](https://github.com/theia-ide/typescript-language-server) which is [no longer maintained](https://github.com/theia-ide/typescript-language-server/issues/141), and [`javascript-language-server`](https://github.com/sourcegraph/javascript-typescript-langserver), which is in a similar state. There's an issue on the `nvim-lspconfig` repo that is discussing options for replacing typescript-language-server ([here](https://github.com/neovim/nvim-lspconfig/issues/250)), but there's no clear path forward. While there might not be a lot of value in this project for CoC, it would be a boon to the developer community wanting a maintained TypeScript LSP implementation.

FWIW, I have no idea how LSP implementation works or how complex it would be to separate CoC from the LSP implementation.

**Comment by chemzqm** [comment]
Not possible
