### ISSUE TITLE
Go to definition not working on a js file with jsx in it

### ISSUE THREAD

**Issue by nschurmann** [neoclide/coc-tsserver#208]
I have this code:

```
// @flow
import React from 'react';
import { Provider } from 'react-redux';
import codePush from 'react-native-code-push';
import { PersistGate } from 'redux-persist/es/integration/react';
import Launch from './containers/Launch';
import configureStore from './configureStore';

const App = () => {
  const { store, persistor } = configureStore();

  if (!store || !persistor) {
    return null;
  }

  return (
      <Provider store={store}>
        <PersistGate loading={null} persistor={persistor}>
          <Launch />
        </PersistGate>
      </Provider>
  );
};
```

I have coc installed and also coc-tsserver, when I put the cursor on top of the component <Launch /> and press gd I expect to go to the definition of that component, however this text is being displayed instead:

`[coc.nvim] definition provider not found for the current document`

I read in the README.md file that we need to point our javascript files to javascript.jsx or javascriptreact so I added this to my nvim config file:

```
" Javascript
autocmd bufnewfile,bufread *.tsx set filetype=typescript.tsx
autocmd bufnewfile,bufread *.jsx set filetype=javascript.jsx
autocmd bufnewfile,bufread *.js set filetype=javascript.jsx
augroup filetype javascript syntax=javascript
```

But the problem persist, is this feature supported? or I have something missing?

**Comment by chemzqm** [comment]
Check `:echo &filetype`
