### ISSUE TITLE
import/no-unresolved: Unable to resolve path to module

### ISSUE THREAD

**Issue by AlaaSaadAbdo** [neoclide/coc-tsserver#209]
Hello,

I have a private repo in which I have an `app` directory and in that directory the issue is not present. In the same repo I have another directory called `packages` inside it there multiple components/modules in which each of them is a separate "app" when I'm inside any of these directories, I face the issue that all my imports have the error `import/no-unresolved: Unable to resolve path to module` although code completion works when I want to import any package.

coc-config:

```
  "eslint.autoFixOnSave": true,
  "eslint.filetypes": ["javascript", "javascriptreact", "typescript", "typescriptreact"],
  "coc.preferences.formatOnSaveFiletypes": [
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact"
  ],
  "tsserver.formatOnType": true,
  "coc.preferences.formatOnType": true,
  "coc.preferences.rootPatterns": [".git",".hg",".projections.json","tsconfig.json",".prettierrc",".eslintrc.js","lerna.json"],
  "eslint.packageManager":"yarn"
}
```

the exact error message:
```
[eslint import/no-unresolved] [E] Unable to resolve path to module
```
although when I trigger `doHover` action, it can find the package.

I'm not sure how to go about this, if there's anything else I can provide, I'd be happy to.

Thanks for the great work you've done here :)

**Comment by chemzqm** [comment]
You have to configure eslint

**Comment by AlaaSaadAbdo** [comment]
I do have configurtion for eslint in `.eslintrc.js` in each subdirectory inside packages, the configuration works for vscode for example

**Comment by chemzqm** [comment]
This extension doesn't affect eslint

**Comment by AlaaSaadAbdo** [comment]
I see, ok. Thanks for the quick responses.
