### ISSUE TITLE
No implicit any - can't get rid of these checks for JS file

### ISSUE THREAD

**Issue by vjsingh** [neoclide/coc-tsserver#213]
I'm getting the following error in a **JS** file:

`Parameter 'someParam' implicitly has an 'any' type, but a better type may be inferred from usage`

The error is coming from coc-tsserver. I've tried adding `noImplicitAny: false` to my `jsconfig.json` but that doesn't seem to work.

This is the only unexpected error I'm getting otherwise my ts-server config seems to be perfect in coc. Any idea how to fix it?

Below is part of the dump from `CocCommand tsserver.openTsServerLog` that I think shows the `noImplicitAny: false`, but it was a very large dump so I wasn't sure what the relevant parts were.

```
Info 30   [15:52:56.513] event:
    {"seq":0,"type":"event","event":"projectLoadingStart","body":{"projectName":"/Users/.../schedule.js to open"}}
Info 31   [15:52:56.612] Config: /Users/.../jsconfig.json : {
 "rootNames": [
     ...
 ],
 "options": {
  "allowJs": true,
  "maxNodeModuleJsDepth": 2,
  "allowSyntheticDefaultImports": true,
  "skipLibCheck": true,
  "noEmit": true,
  "checkJs": true,
  "target": 2,
  "module": 5,
  "moduleResolution": 2,
  "jsx": 2,
  "alwaysStrict": true,
  "forceConsistentCasingInFileNames": true,
  "noFallthroughCasesInSwitch": true,
  "noImplicitAny": false,
   ...
 }
}
```

**Comment by chemzqm** [comment]
Try minimal vimrc.

**Comment by vjsingh** [comment]
Hi @chemzqm, thanks for the help.

I am trying with a minimal `.vimrc`. I've disabled all my other plugins except coc, and am still getting the following error in a javascript file:

`  app/someFile.js:43:24 Information [tsserver 7044] Parameter 'prevProps' implicitly has an 'any' type, but a better type may be inferred from usage.`

**Comment by chemzqm** [comment]
Try:
```
  "javascript.suggestionActions.enabled": false,
```
in your `coc-settings.json`

**Comment by vjsingh** [comment]
@chemzqm Thanks. That got rid of my 7044 no implicit any error, but I'm still getting:

`app/file.js|43 col 24 info| [tsserver 6133] 'prevProps' is declared but its value is never`

Is it supposed to be reading my jsconfig.json? I would prefer to explicitly define which warnings/suggestions I'd like to turn on and off, but adding ` "noImplicitAny": false,` to my `jsconfig.json` doesn't seem to have any effect.

**Comment by chemzqm** [comment]
Use `  "javascript.showUnused": false,`, please read readme.

**Comment by chemzqm** [comment]
> but adding "noImplicitAny": false, to my jsconfig.json doesn't seem to have any effect.

Should be issue of typescript, check log of tsserver.

**Comment by vjsingh** [comment]
Ok, thanks. This removed all the suggestions, which works for now.

It looks like it may be an issue with tsserver: https://github.com/microsoft/TypeScript/issues/28702
