### ISSUE TITLE
What's the recommended folding method?

### ISSUE THREAD

**Issue by AdrienLemaire** [neoclide/coc-tsserver#217]
With the following configuration
```vim
command! -nargs=? Fold :call     CocAction('fold', <f-args>)
```

When typing `:Fold` in a typescript file, I get the error
> [coc.nvim] foldmethod option should be manual! 

When I do `:se foldmethod=manual` followed by `:Fold`, it then works, but that means I'm losing the syntax folding from yats.vim.

I understand that I can use `:Fold region` by using comment marks `// #region` and `// #endregion`. As a side note, wouldn't it have been simpler to use the existing fold-marker syntax `{{{` and `}}}` ?

I also understand that we can call `:Fold code` (not mentioned in `:h coc-action-fold`). With the following vim config, the folding is quite broken with many excessive folds
```
set foldmethod=indent
autocmd FileType javascript,typescript,json,typescriptreact setlocal foldmethod=manual
```
Somehow, it looks like the root definition `foldmethod=indent` is affecting the manual folding when calling `:Fold`.
I could verify that commenting out `"set foldmethod=indent` to have a default foldmethod manual gives good results with `:Fold code`.

I'd like to fold imports and regions using coc-tsserver in addition to yats.vim syntax folding.
But it doesn't seem possible to mix manual and syntax folding.
It also looks like calling `:Fold code` and `:Fold import` gives a reasonable folding level, but I couldn't find a way to execute these commands when opening a buffer

```vim
augroup jsFolds
  autocmd!
  autocmd FileType typescriptreact syntax sync fromstart
  autocmd FileType typescriptreact setlocal foldmethod=manual
  autocmd FileType typescriptreact call CocAction('fold', 'imports')
  autocmd FileType typescriptreact call CocAction('fold', 'code')
augroup end
```
also tried BufEnter, BufWinEnter, BufRead, BufReadPre and more without success. I suspect that is because CocAction isn't ready by the time the autocmd is executed ?

How are folding users using coc-tsserver and coc.nvim in general to have a better folding experience?

**Comment by chemzqm** [comment]
I prefer foldmethod=expr without using tsserver

**Comment by chemzqm** [comment]
It's personal preference, not problem of this plugin.
