### ISSUE TITLE
Installation fails resolving tslint dependency

### ISSUE THREAD

**Issue by grocky** [neoclide/coc-tsserver#219]
Hello! I'm doing an install on a new machine, and `coc-tsserver` is failing to install (same error as coc-html)

![image](https://user-images.githubusercontent.com/1675518/97237046-c4eba480-17bc-11eb-9d1c-efc7d377183d.png)

```
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: coc-tsserver@1.5.8
npm ERR! Found: tslint@6.1.3
npm ERR! node_modules/tslint
npm ERR!   dev tslint@"^6.1.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer tslint@"^5.8.0" from @chemzqm/tslint-config@1.0.18
npm ERR! node_modules/@chemzqm/tslint-config
npm ERR!   dev @chemzqm/tslint-config@"^1.0.18" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
```

Doing an `npm install` on a clone of this repo results in the same error.

![image](https://user-images.githubusercontent.com/1675518/97239120-4b09ea00-17c1-11eb-8d0e-f6bb442b348e.png)

**Comment by chemzqm** [comment]
Fixed, npm is good at break things.

**Comment by grocky** [comment]
Great, thank you!

![image](https://user-images.githubusercontent.com/1675518/97338087-74755500-1857-11eb-97c5-1fdf914180a6.png)
