### ISSUE TITLE
Project wide goto reference not being picked up for jsx

### ISSUE THREAD

**Issue by ChristianChiarulli** [neoclide/coc-tsserver#221]
All of my project wide references are not being picked up until after I goto definition.

Btw I know that my files must be `.jsx` for this to work.

**Comment by chemzqm** [comment]
You may need jsconfig.json, check log of tsserver

**Comment by ChristianChiarulli** [comment]
Thank you, I wasn't aware this was a thing.

Just in case anyone stumbles upon this issue just add this to the root of your project and read up on tsconfig/jsconfig. 

```
{
  "compilerOptions": {
    "jsx": "react",
    "module": "commonjs",
    "noImplicitAny": true,
    "outDir": "./build/",
    "removeComments": true,
    "sourceMap": true,
    "target": "es5"
  },
  "include": ["./src/**/**/*"]
}
```

You might consider adding this snippet to a FAQ or something.

**Comment by chemzqm** [comment]
Readme already mentioned that.

**Comment by ChristianChiarulli** [comment]
It didn't mention a helpful snippet thought. 

Include it or don't idc I just think people will find it helpful.

**Comment by chemzqm** [comment]
It's not that helpful, you have to read through the article for jsconfig.json
