### ISSUE TITLE
No intellisense for .tsx files

### ISSUE THREAD

**Issue by tozaicevas** [neoclide/coc-tsserver#222]
Version: 1.6.0, OS X

I do get intellisense for .ts, but not .tsx.

**Comment by chemzqm** [comment]
Please read Readme https://github.com/neoclide/coc-tsserver#coc-tsserver

**Comment by brandonpittman** [comment]
I was bit by this as well. Had been fine for months though.

**Comment by chemzqm** [comment]
Make sure your filetype is expected

**Comment by brandonpittman** [comment]
@chemzqm Just added an autocommand to set it to `typescript.tsx` and it's fine now. Seems like I didn't have this issue until today though. Maybe something changed? Oh well, working now.

**Comment by chemzqm** [comment]
Use `:verbose set filetype` to check

**Comment by romariolopezc** [comment]
@brandonpittman how did you manage to do it? It was working in another computer setup but is not working in this one

**Comment by brandonpittman** [comment]
@romariolopezc Sorry, I can't remember what I did back then. I'm not using the autocommand anymore so I figured something else out.
