### ISSUE TITLE
Where Did :TS* Commands Go?

### ISSUE THREAD

**Issue by atomdmac** [neoclide/coc-tsserver#224]
Though I did not make heavy use of them in the past, it looks like the "TS" commands (such as `:TSDef`) are no longer available.  Was this a code change or does it just have to do with my configuration?

For context, I'm trying to use the "go to definition" feature of TSServer.

**Comment by chemzqm** [comment]
No such commands of this plugin

**Comment by atomdmac** [comment]
The documentation states that `Go to definition.` is one of the features supported by this plugin, no?  How do I initiate a "go to definition" command?

**Comment by atomdmac** [comment]
Just to confirm: there is no way to initiate a `go to definition` operation with `coc`?
