### ISSUE TITLE
From time to time coc-tsserver doesn't recognise TSX

### ISSUE THREAD

**Issue by raph90** [neoclide/coc-tsserver#225]
I can't really understand why this is happening - I made an issue earlier and thought I'd solved it by removing some python files from my React project, but now that they're gone it's still happening. 
From time to time coc-tsserver can't recognise my TSX code. It thinks it should just be straightforward Typescript code. 
![Screenshot 2020-11-09 at 15 48 37](https://user-images.githubusercontent.com/30865601/98563400-0a22d280-22a3-11eb-87df-2d02ae66cb95.png)

If I run tsserver restart it doesn't fix the problem. 

Here is my coc-config for this project: 
```
{
  "snippets.extends": {
    "typescript": [
      "typescriptreact"
    ]
  },
  "coc.preferences.formatOnSaveFiletypes": [
    "ruby",
    "json",
    "javascript",
    "typescript",
    "python",
    "typescriptreact",
    "javascriptreact"
  ]
}
```
It's very straightforward, and all of my filetypes are either .ts or .tsx. 

Here is my tsconfig: 
```
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react"
  },
  "include": [
    "src"
  ]
}
```

**Comment by chemzqm** [comment]
Please read readme check your filetype and log

**Comment by raph90** [comment]
I have read the readme - how do you define the filetypes?

**Comment by chemzqm** [comment]
> how do you define the filetypes?

Use vim plugin or autocmds.

**Comment by raph90** [comment]
I'm using coc, and in the readme it says: 
 _In coc.nvim, these filetypes are mapped to javascriptreact and typescriptreact because that's what tsserver uses_

So how do I define this in the coc configuration? 

I've found this on the coc readme: 
```

{
  "languageserver": {
    "go": {
      "command": "gopls",
      "rootPatterns": ["go.mod"],
      "trace.server": "verbose",
      "filetypes": ["go"]
    }
  }
}
```
But in the readme for typescript it simply says to use coc-tsserver. So there is nowhere where I can find how to actually specify the filetypes. I'd really appreciate it if you could explain this.
