### ISSUE TITLE
Format imports with spaces inside curly braces.

### ISSUE THREAD

**Issue by AnatoleLucet** [neoclide/coc-tsserver#226]
Is there a way to tell `organizeImport` to add a space after the opening curly brace and before the closing one.

What is does:
```js
import {x} from 'x';
```

What I'd like:
```js
import { x } from 'x';
```

**Comment by chemzqm** [comment]
Check format options https://github.com/neoclide/coc-tsserver#configuration-options

**Comment by AnatoleLucet** [comment]
`typescript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces` indeed. Thanks!
