### ISSUE TITLE
rename symbols cannot be applied to <script> block in vue component

### ISSUE THREAD

**Issue by GopherJ** [neoclide/coc-tsserver#228]
coc-tsserver works perfectly for all .ts files, but I believe it should also apply code actions for <script> blocks in vue component files.
Is it possible to have this feature?

**Comment by GopherJ** [comment]
Now what I do is:

1. run `rename symbols` action in ts files
2. check `coc-explorer` to see which vue component is using this symbol but not updated
3. go to the files which have error and manually correct them

**Comment by chemzqm** [comment]
It can't, send your feature request ti typescript repo if you want
