### ISSUE TITLE
bug - 'import type' removing syntax highlighting

### ISSUE THREAD

**Issue by himat** [neoclide/coc-tsserver#229]
If I use the typescript `import type` syntax, then the syntax highlight is removed for that file in vim.

Before:
![image](https://user-images.githubusercontent.com/1156974/99491862-89b34000-293a-11eb-8771-ff62e4d02f84.png)

After:
![image](https://user-images.githubusercontent.com/1156974/99491840-7d2ee780-293a-11eb-981e-f9ec255cb34e.png)

Where in `company.ts`, I have
```
export interface Company {
    id: number,
    name: string,
}
```

I have the latest coc-tsserver 1.6.0 installed.

**Comment by chemzqm** [comment]
It's the problem of your syntax plugin.
