### ISSUE TITLE
Always use 'absolute' imports with coc.nvim

### ISSUE THREAD

**Issue by PezCoder** [neoclide/coc-tsserver#231]
- [x] I've gone through the existing config options

The current implementation of coc.nvim when it comes to `autoImport` is pretty smart in terms of absolute vs relative imports.

I encountered a requirement where for a project I would like to have just 'absolute' imports, this was done to avoid any confusion.

Wondering if there is a way to achieve this?

**Comment by chemzqm** [comment]
The server could provide such kind of option which can't be controlled by coc.nvim.
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by chemzqm** [comment]
Looks like you need send feature request to typescript team, the option have to be provided by tsserver.

**Comment by PezCoder** [comment]
@chemzqm Thank you for point me there. Found this helpful option which we already support https://github.com/microsoft/TypeScript/issues/21860#issuecomment-389307342. My bad on this.

Here's how you do it in vim:
```
# Opens coc-tsserver config
:CocConfig

# Add this to the config object
"typescript.preferences.importModuleSpecifier": "non-relative"
```
