### ISSUE TITLE
Extension not working properly on Windows

### ISSUE THREAD

**Issue by marcmarina** [neoclide/coc-tsserver#233]
I have tested this extension on Linux and it works perfectly, it's amazing. However, some things (the tsserver I guess) are not working on Windows. I get code completion for things that are in the same file, such as objects. But not for things in other files (imports). Also, all my imported packages give the same error as my imported files.

`[tsserver 2307] [E] Cannot find module 'dayjs' or its corresponding type declarations.`

Here is my Coc config file:
```json
{
  "tsserver.npm": "C:\\Program Files\\nodejs\\npm",
  "tsserver.log": "verbose",
  "tsserver.trace.server": "verbose"
}
```

In another issue, I saw that `coc-deno` could conflict with this extension, but it is not installed.

Even though I have set the logging option, no errors show up, so I can't debug this.

Thanks!

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by marcmarina** [comment]
I have tried debugging the LSP using the tool mentioned in that repo to no avail. It just doesn't want to read my log :(

**Comment by marcmarina** [comment]
I have tried a different approach. I was using the Vim included in Windows' Git installation. I have now installed Vim separately and the plugin seems to works just fine. I'll do some tests to confirm it and get back to you.

**Comment by chemzqm** [comment]
It's known that coc.nvim can't work inside git shell of windows.

**Comment by marcmarina** [comment]
Ohhh I didn't know that and I hadn't seen it mentioned. Sorry then.
