### ISSUE TITLE
Add languages provided by "typescriptServerPlugins" to languageModeIds

### ISSUE THREAD

**Issue by znck** [neoclide/coc-tsserver#235]
`languageIds` defined in https://github.com/neoclide/coc-tsserver/blob/9c56024d8d53b0c57a008bfbcf8917cf3eb11c0e/src/server/utils/languageModeIds.ts#L15 and `languageModeIds` defined in 
https://github.com/neoclide/coc-tsserver/blob/b59f5bd5a4cca80b401776e320d0e95f2260d3b0/src/server/utils/languageDescription.ts#L22-L40
are used provide features. 

It should include languages from extensions when registering providers:
https://github.com/neoclide/coc-tsserver/blob/b59f5bd5a4cca80b401776e320d0e95f2260d3b0/src/server/languageProvider.ts#L73

Also,  sync with upstream is also required to support `configNamespace` (a new option added to `typescriptServerPlugins`).

**Comment by chemzqm** [comment]
Should work now.
