### ISSUE TITLE
Errors of using types in js files

### ISSUE THREAD

**Issue by Flamme13** [neoclide/coc-tsserver#238]
after the update, errors of using types in js files began to be shown.

in settings coc-settings.json

{
   "javascript.validate.enable": false
}

but that doesn't help.

![Selection_001](https://user-images.githubusercontent.com/8742198/101539319-69adf400-39af-11eb-9b60-0e8fbc47a816.png)

because of this, the experience of working with legacy code written in flowjs was worsened

is it possible to somehow remove errors from js files without turning off the ts server?

there was no problem before the update.

**Comment by chemzqm** [comment]
Make sure your filetype is javascript or starts with javascript.

**Comment by chemzqm** [comment]
Seems VSCode have this bug as well.
