### ISSUE TITLE
Can't install with CocInstall: install exited with 1

### ISSUE THREAD

**Issue by chgara** [neoclide/coc-tsserver#247]
When I try to install coc-tsserver with CocInstall it fails and output _coc-tsserver C:\Program Files\nodejs\npm.CMD install exited with 1_
**Node version:** v15.3.0
**NPM version:**7.0.150
**coc.nvim version:** 0.0.80-a112e6621b

Detailed logs:(output of CocInfo)
![Sin título](https://user-images.githubusercontent.com/57034271/104136570-64b9d700-5397-11eb-9c4c-2832b1f18eca.png)

**Comment by chemzqm** [comment]
Use npm 6 or update your coc.nvim.
