### ISSUE TITLE
WSL mounted project dirs are very slow, or not working at

### ISSUE THREAD

**Issue by ruslanzelinskyy** [neoclide/coc-tsserver#249]
I was getting this error.

In my case it's because I'm using WSL2(virtual machine under the hood) and the project was on the Windows filesystem(mounted in the VM), copying it over to my home folder fixed the issue.

_Originally posted by @diegomichel in https://github.com/neoclide/coc-tsserver/issues/25#issuecomment-671595875_

**Comment by ruslanzelinskyy** [comment]
what could be the reason of that WSL mounted project dirs are very slow, or not working at all with tsserver?
FZF, vifm etc works fine.

**Comment by chemzqm** [comment]
Seems issue with tsserver itself, try exists configurations or split your project to smaller ones.

**Comment by ruslanzelinskyy** [comment]
@chemzqm I have a clean create-react-app template, it couldn't be splitted more.

Seems like a problem with symlinks or smth. 
I am not sure how WSL mounts the windows dirs, but maybe there is some way to do that in more efficient way?

**Comment by chemzqm** [comment]
Don't know, it's problem of tsserver, you need https://github.com/microsoft/typescript

**Comment by diegomichel** [comment]
Hi guys,

Just adding more info on what I found when I researched the issue. It looks like the issue is that shared folders are just too slow, and because of that tsserver times out.

Interesting read about it here:
https://github.com/microsoft/WSL/issues/4197#issuecomment-604592340

Bests,
Diego.
