### ISSUE TITLE
Error highlight dissapears on save

### ISSUE THREAD

**Issue by WhyNotHugo** [neoclide/coc-tsserver#251]
When I edit a file, errors are highlighted correctly:

![image](https://user-images.githubusercontent.com/730811/105081431-16d55b00-5a8a-11eb-86d9-e12435a2e5eb.png)

However, after saving `:w`, they disappear:

![image](https://user-images.githubusercontent.com/730811/105081458-20f75980-5a8a-11eb-91e7-1b0da31c28d2.png)

If I run `:copen`, however, the errors are still listed, so they're still reported, just not highlighted:

![image](https://user-images.githubusercontent.com/730811/105081570-43897280-5a8a-11eb-9c6e-f38d39e44a57.png)

Re-reading the files makes the error's highlighting appear again (e.g.: `:e`). This happens only with `coc-tsserver` (e.g.: Not with coc-jedi, etc).

**Comment by chemzqm** [comment]
Could be tsserver slow to response.

**Comment by WhyNotHugo** [comment]
I don't _think_ so.  

When I run `:w`, the highlights disappear and do not appear (even if I wait for a few minutes).

If run `:e` immediately after the save, the highlights reappear within a couple of seconds.

At no point do the errors disappear from the quickfix window (I display errors via ALE).

I'll try to trim down my nvim config to a be as minimal as possible to repro this.

**Comment by byeokim** [comment]
I can reproduce this. Another case: highlights disappear after typing `K` on any (highlighted or not) variables to hover documentation, and then moving cursor to close hovered documentation.

**Comment by chemzqm** [comment]
Should be issue with ale
