### ISSUE TITLE
auto-complete not working on single-char variable names

### ISSUE THREAD

**Issue by rkulla** [neoclide/coc-tsserver#254]
If I name an array with only a one-character name like `a`, methods don't complete. For example:

    const a = [1, 2, 3];
    a.m[tab]  // doesn't work. In fact, no array methods will complete or be suggested.

    const a1 = [1, 2, 3];
    a1.m[tab] // completes a1.map as expected. and even shows other suggestions like flatMap

the same goes for naming it `b` instead of `a`. It won't work but `bb` will work, etc.

It's a problem with arrays for sure but I can name a string simply `s` and completion works, e.g., to s.trim. Very confusing.

**Comment by rkulla** [comment]
What's even weirder is that if i put a `jsconfig.json` file inside the same directory (has to be inside the exact same directory only, short name arrays work.  For example:

    my-project/
        jsconfig.json
        my-subdir/
             foo.js 

Completion of an array named `a` (one char) won't work but if i copy jsconfig.json INTO my-subdir it works magically.  This is not normal behavior based on the docs afaict.

**Comment by chemzqm** [comment]
Can't reproduce https://github.com/neoclide/coc-tsserver#troubleshooting

**Comment by rkulla** [comment]
I can reproduce it on 2 different macs running latest MacVim and latest CoC currently. I uninstalled all other vim plugins and all CoC extensions except for coc-tsserver and without anything in coc-settings.json. Also with very minimal vimrc with `filetype plugin indent on`.

Example file (foo.js), even with ONLY this one line:
   
    a1.m // works (shows suggestions like `map`, `flatMap`,`some`) from `f [TSC]`
    a.m  // doesn't work  (no auto-complete suggestions)

**Comment by chemzqm** [comment]
Check your keymap by `:verbose imap <tab>`

**Comment by rkulla** [comment]
This same behavior happens wither tab is mapped to nothing or the suggested pumvisible/coc#refresh/check_back_space snippet.  Also it happens *before* hitting tab.
