### ISSUE TITLE
Disable aliasing on rename

### ISSUE THREAD

**Issue by JakeElder** [neoclide/coc-tsserver#255]
Given code like this

```typescript
const person = { hgt: 180 }
const { hgt } = person;
console.log(hgt)
```

Using `<Plug>(coc-rename)` `hgt` ~> `height`

Results in this;

```typescript
const person = { hgt: 180 }
const { height: hgt } = person;
console.log(hgt)
```

Whereas
```typescript
const person = { hgt: 180 }
const { height } = person;
console.log(height)
```

would be much preferable.

This has been implemented in Microsofts ts server and vscode. Link -
https://github.com/Microsoft/TypeScript/issues/29238#issuecomment-494866713

Is there any chance of having this implemented?

**Comment by fannheyward** [comment]
Set `typescript.preferences.useAliasesForRenames` to false in your coc-settings.json.

**Comment by JakeElder** [comment]
> Set `typescript.preferences.useAliasesForRenames` to false in your coc-settings.json, `javascript.preferences.useAliasesForRenames` if you're using JS.

Thank you. This doesn't seem to catch object property shorthands. IE

Before
```typescript
type Params = {
  arg: string;
};

function doAThing({ arg }: Params) {
  const t = { arg };
}
```

`<Plug>(coc-rename)` `arg` ~> `newArgName` (while cursor is over arg in the type definition)

Results in;

```typescript
type Params = {
  newArgName: string;
};

function doAThing({ newArgName }: Params) {
  const t = { arg };
}
```

Which results in a "no value exists" error. Perhaps the reason why aliasing is the default. Anyway that is another issue, thank you for the answer.

**Comment by fannheyward** [comment]
@JakeElder tested your code with VSCode + https://github.com/microsoft/TypeScript/issues/29238#issuecomment-494866713 settings, same issue. It's related to coc or coc-tsserver.

**Comment by JakeElder** [comment]
Thanks @fannheyward, closing. Would it be useful for me to create a PR that adds this setting to the documentation?
