### ISSUE TITLE
How to get function signatures for jQuery on JS files?

### ISSUE THREAD

**Issue by jorgelespinoza** [neoclide/coc-tsserver#259]
I get function signatures for jQuery on html files, like this:
![image](https://user-images.githubusercontent.com/42013600/107778009-4e9a9000-6d22-11eb-9e82-5d2c891850fa.png)
But inside a js file, the method is recognized but without signature:
![image](https://user-images.githubusercontent.com/42013600/107778208-902b3b00-6d22-11eb-96f2-8715c6731d39.png)
How can I activate it for js files if it works for html files?

**Comment by chemzqm** [comment]
You need types, read docs of typescript.
