### ISSUE TITLE
Lack of relative lookup for pnpfied (Yarn v2) tsserver.tsdk

### ISSUE THREAD

**Issue by ambasta** [neoclide/coc-tsserver#260]
Hi,

I have a yarn v2 monorepo with the .vim/coc-settings in the rootdir. However, while launching vim from any subdirectory recognizes the coc-settings.json from parent .vim directory, relative paths in tsserver.tsk are resolved wrt cwdir instead of relative to project root.

This leads to tsserver failing to find modules w/

` [coc.nvim] Can not find typescript module, in 'tsserver.tsdk': .yarn/sdks/typescript/lib`

**Comment by chemzqm** [comment]
Use `${workspaceRoot}` at the beggining.

**Comment by ambasta** [comment]
@chemzqm You mean like so?

[coc.nvim] Can not find typescript module, in 'tsserver.tsdk': ${workspaceRoot}/.yarn/sdks/typescript/lib

**Comment by chemzqm** [comment]
Yes

**Comment by chemzqm** [comment]
Yes

**Comment by ambasta** [comment]
@chemzqm Thanks a lot.. setting appropriate root pattern in vim settings resolves this. I am not sure if coc-tsserver should handle this, but the current contributes.rootPatterns doesn't work for monorepos. I am not sure how this can be addressed in general, but using npm.lock or yarn.lock instead for pnp projects instead of package.json/tsconfig.json might be more benefitial

**Comment by chemzqm** [comment]
You may have to use `workspace.bottomUpFiletypes` configuration.
