### ISSUE TITLE
"untitled" buffer opened when writing new ts/tsx file

### ISSUE THREAD

**Issue by GitSquared** [neoclide/coc-tsserver#261]
### What happens
When I :w a new buffer to a .ts (or .tsx) file, it creates a hidden `^untitled` buffer and keeps re-opening it until I restart Coc.

### What i would expect
I use hidden buffers to work on multiple files at a time. This unclosable buffer clutters my workspace and seems to be unused anyway (nothing to see in it). I would expect that tsserver doesn't create it.

### Demo

![Peek 2021-02-21 16-14](https://user-images.githubusercontent.com/24496417/108629521-8f9c4e00-7460-11eb-973c-87ee42074d0c.gif)

(what happens in the gif: I save a new, empty buffer as a .ts file. Coc-tsserver kicks in, and for some reason opens the hidden buffer. I try to close it and go back to my .ts file, but tsserver opens it again.)

### Logs

[`CocCommand tsserver.openTsServerLog`](https://pastebin.com/W703g63Q)
[`CocCommand workspace.showOutput tsserver`](https://pastebin.com/tA0tQefM)

---

Thanks for your help!

**Comment by chemzqm** [comment]
Try minimal vimrc.

**Comment by GitSquared** [comment]
Thanks for the fix, all good now.
