### ISSUE TITLE
Auto-completion doesn't suggest the "extends" keyword for interfaces

### ISSUE THREAD

**Issue by sarrietav-dev** [neoclide/coc-tsserver#262]
![Example](https://user-images.githubusercontent.com/25210925/108661222-4d433300-7499-11eb-89ba-f2766183d965.gif)

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc-tsserver#troubleshooting

**Comment by chemzqm** [comment]
Send your request to https://github.com/microsoft/TypeScript
