### ISSUE TITLE
Go to definition don't resolve dependency injection (vscode does)

### ISSUE THREAD

**Issue by feliperama** [neoclide/coc-tsserver#264]
Hi everyone!

When I uses the go to definition when I have an dependency injection using inversify, coc is redirecting me to the interface, while VScode is capable to redirect me direct to the class which implements that interface. I would like to know if:
1 - There is away to this at vim (any option of tsserver to change)? Any Go To Next?
2 - If not, any idea on how to fix this?

So for example, for the code bellow (of course just an example it was in multiple files), vim redirects me to `InterfaceClassB` while VSCode redirects me to `ClassB`:

```Typescript
import { inject, injectable, Container} from 'inversify';

interface InterfaceClassB<Parm1> {
    execute(parm1: Parm1): void;
}

class ClassB implements InterfaceClassB<string> {
    execute(parm1: string) {}
}

const kernel = new Container();

kernel
    .bind<InterfaceClassB<any>>('ClassB')
    .to(ClassB)
    .inSingletonScope()
    .whenTargetNamed('ClassB');

@injectable()
class ClassA {
    constructor(
        @inject('ClassB')
        private readonly classB: InterfaceClassB<string>
    ) {}
}
```

**Comment by chemzqm** [comment]
Should be different version of tsserver.

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc-tsserver#troubleshooting

**Comment by feliperama** [comment]
You was totally right! I just updated to 3.9.9 and it's working the same.

Btw, I can't say enough thankyou for this great plugin. With all that work our beloved vim/neovim would die :)
