### ISSUE TITLE
enableProjectDiagnostics uses constantly 100% CPU

### ISSUE THREAD

**Issue by Kokujou** [neoclide/coc-tsserver#265]
Hey guys... i just ran into this awesome feature... i love the idea behind it! and it really helped us. 
but sadly i just figured that it constantly eats all of my CPU, this also results into some not-nice cursor flickering (like it's switching to the loading-cursor every few milliseconds). i disabled it and my CPU went back to normal.

and now i'll be constructive. I see two ways to fix it:
1. run the check once on startup and then only run it again on changed files (but also include changes like on regex replacements)
2. make the interval configurable. milliseconds is definitely too much for a checking interval. seconds, or even one minute might be enough.

maybe a general optimization of the feature itself could also help. if you "just" do the normal semantic checking on every file in the project, then i have the fear my vscode will explode after our project will grow bigger :)

this is really an awesome fixture and one of the most annyoing things on a not-project-based programming language. now i can basically work with javascript like with c#, moving files is no problem anymore, renaming is the same. so i would personally consider this feature as most important.

**Comment by chemzqm** [comment]
My suggestion avoid enable project diagnostics, it's issue of typescript checkout https://github.com/microsoft/TypeScript/issues

**Comment by Kokujou** [comment]
thanks, i will try it there.
as i said this feature is important to keep a look on our project. since JS has no compilation it's really annoying to find bugs in your frontend which could have easily be tracked with a feature like this.

**Comment by chemzqm** [comment]
I don't agree, tsserver is quite limited for javascript, it doesn't help much.
Use typescript and run the compile task for project errors is recommended.

**Comment by Kokujou** [comment]
> 
> 
> I don't agree, tsserver is quite limited for javascript, it doesn't help much.
> Use typescript and run the compile task for project errors is recommended.

i know, but my team doesn't like typescript... because it's not native, requires an additional build step... actually right now i found a way to have javscript behave exactly like typescript.
with JSDoc you can even have proper typing without implementing those instanceof calls to ensure a type. 

i mean i personally like typescript and i would've done it like that, but out there are a lot of people who don't like it because of reasons... for example it doesn't use the latest ES version or so... 

but having all the type safety also in javascript makes such a feature way more important.
