### ISSUE TITLE
Error link library

### ISSUE THREAD

**Issue by thevan96** [neoclide/coc-tsserver#269]
Why library does not links inside folder node_modules without the link to  ~/Library/Caches/typescript/...
I checked on vscode it still an error, maybe the error is due to the tsserver
![Screen Shot 2021-03-16 at 12 46 33 PM](https://user-images.githubusercontent.com/47932916/111261812-a562f480-8655-11eb-947b-e89578b4cb2d.png)
![Screen Shot 2021-03-16 at 12 46 44 PM](https://user-images.githubusercontent.com/47932916/111261839-ac8a0280-8655-11eb-914b-33efb4da4c37.png)

**Comment by chemzqm** [comment]
Ask https://github.com/microsoft/TypeScript/issues

**Comment by thevan96** [comment]
![Screen Shot 2021-03-16 at 2 03 28 PM](https://user-images.githubusercontent.com/47932916/111268836-64bca880-8660-11eb-8220-8056c13a20dd.png)
Sorry, I upload an image missing node_modules
I try but it stilll error

**Comment by chemzqm** [comment]
Make sure you have correct version of `@types/express` in your node_modules folder.

**Comment by thevan96** [comment]
@types/express diffrent express ?

**Comment by chemzqm** [comment]
tsserver need that types to work with your javascript.
