### ISSUE TITLE
tsserver not starting

### ISSUE THREAD

**Issue by jeremyong** [neoclide/coc-tsserver#27]
After opening a `.ts` file, `CocInfo` shows no tsserver starting and I have no syntax highlighting, completion, or jumping. A `checkhealth` shows that everything is clean. The other extensions I have are `coc-json` and `coc-neosnippet`

If I do a `CocList extensions`, it shows the three extensions, all enabled but only the `neosnippet` extension is activated. If I manually launch `coc-tsserver`, I see that it starts without error in the log and even loads the ts config file properly. A `ps` shows that a `tsserver` executable is running. However, even at this point, trying to jump to a function definition shows an error `[coc.nvim] Definition provder not found for current document`. No other messages are available from `messages`.

I should also mention that I have cquery enabled as another language server in `CocConfig` but I'm not sure if that would impact things. I've checked that the `tsserver.enable` option is set to `true` in the configuration as well, and have no other customizations.

Any ideas what could be wrong or how to troubleshoot further?

Thanks!

**Comment by jeremyong** [comment]
Another piece of information, if I enable `tsserver.enableJavascript', the extension loads `js` files just fine but still no luck with either `ts` or `tsx` files.

**Comment by chemzqm** [comment]
You should make sure your filetype is corrent, install a typescript plugin like https://github.com/leafgarland/typescript-vim

**Comment by jeremyong** [comment]
doh Yes that was it thanks, I didn't install my syntax file properly (I'm using https://github.com/HerringtonDarkholme/yats.vim).
