### ISSUE TITLE
es6 imports and commonjs imports in jsx region are different

### ISSUE THREAD

**Issue by login224444** [neoclide/coc-tsserver#270]
// jsconfig.json in the root of nextjs project
{
  "compilerOptions": {
    "baseUrl": "."
  }
}
[](url)
When imports used in js region it uses ES6 imports.
Whed imports used in jsx region - commonJS. What i'm doing wrong?
How to use only ES6 moduels in jsx region also?

![Screenshot_2021-03-18_13-05-21](https://user-images.githubusercontent.com/74967516/111600730-21db0c00-87eb-11eb-9cfe-2c012904ead2.png)
![Screenshot_2021-03-18_13-05-54](https://user-images.githubusercontent.com/74967516/111600733-23a4cf80-87eb-11eb-8cfa-5d2ff3cb84b7.png)

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc-tsserver#configuration-options
