### ISSUE TITLE
[tsserver 2307] [E] Cannot find module 'react-router-dom' or its corresponding type

### ISSUE THREAD

**Issue by flleonx** [neoclide/coc-tsserver#271]
I don't know why I get this warning if all the routes are properly configured. It happens with all the files that I want to import. In VSCode I don't get any problem. 

![vim](https://user-images.githubusercontent.com/69682697/112019571-8e148300-8afd-11eb-8b4c-bb7e994bb7fe.jpg)
![vim2](https://user-images.githubusercontent.com/69682697/112019768-bf8d4e80-8afd-11eb-838a-12a41a6ca264.jpg)

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
