### ISSUE TITLE
option to suppress tsserver diagnostics

### ISSUE THREAD

**Issue by MagicDuck** [neoclide/coc-tsserver#275]
First of all, thanks for the great work on this plugin! It's really awesome how well everything works out of the box! :heart:
I am running into a slight issue though that I would appreciate some assistance with:
If I want to have auto-import of symbol under cursor be available as a code action, the following option needs to be turned on in `jsconfig.json`:
```json
{
  "compilerOptions": {
    "checkJs": true,
...
```
Which is fine and expected as per vscode docs.

The trouble is, at least in my particular case, that when that option is turned on, I also start getting a bunch of other diagnostics from tserver that I don't care about, such as type violations ,etc. Ex:
![image](https://user-images.githubusercontent.com/95201/112775211-0d6bf000-8ff1-11eb-8669-ccfad258a4b1.png)
This makes it hard to pick out the actual eslint diagnostics I need to fix before committing my code.
I am wondering if an option could be added to suppress the tsserver diagnostics?

**Comment by chemzqm** [comment]
No, unless tsserver ptovide it , Avoid checkJS or use ts-ignore comment
