### ISSUE TITLE
Nullish coalescing operator (??) breaks highlighting syntax

### ISSUE THREAD

**Issue by Classy-Bear** [neoclide/coc-tsserver#276]
TO REPRODUCE:

<details>
<summary>With `??`:</summary>

![Screen Shot 2021-03-29 at 12 22 12 PM](https://user-images.githubusercontent.com/37255403/112867920-74d57e80-9089-11eb-8a50-0f825cecf6ad.png)
</details>

<details>
<summary>Without it:</summary>

![Screen Shot 2021-03-29 at 12 22 24 PM](https://user-images.githubusercontent.com/37255403/112867926-769f4200-9089-11eb-9177-b61cc1cc1414.png)
</details>

**This happens because is a new feature in JS?**
If so, Where can I find a list or documentation of operators/methods that are new in JS?

**Comment by chemzqm** [comment]
It's issue of your syntax plugin

**Comment by Classy-Bear** [comment]
Could you please elaborate more on your answer

**Comment by chemzqm** [comment]
It has nothing to do with coc-tsserver
