### ISSUE TITLE
coc-rename and changing file name doesn't work even if using watchman

### ISSUE THREAD

**Issue by carlosala** [neoclide/coc-tsserver#278]
Hi!
I have `watchman` installed without errors, but when I rename a variable using `<Plug>(coc-rename)` or with `<Plug>(coc-refactor)` the changes only affect to the opened buffers.
The same thing happens when I do `:CocCommand workspace.renameCurrentFile`
Is there any way to apply the changes for all project files?
I have a blank config for tsserver.
Thanks!

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by carlosala** [comment]
> Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

But, I am putting this issue in the coc-tsserver repo. I red something about `"tsserver.watchOptions"`, but I cannot find any template config. Can you share some default config to just watch all the root directory?

**Comment by chemzqm** [comment]
`<Plug>(coc-rename)` is used for rename variable under cursor, it has nothing to do with wathcman, which is required for updatet import path on file name.
