### ISSUE TITLE
`tsserver` doesn't quit on vim exit

### ISSUE THREAD

**Issue by ascagnel** [neoclide/coc-tsserver#279]
I've had a few cases where, after fully exiting vim, the coc-tsserver plugin will leave the instance of `tsserver` it started (invoked via `tsserverForkStart`) running.  I'm not sure how I can capture this a log format for follow-up, the most I can say is that I've seen a bunch of entries in `htop` trying to recompile after big code changes (eg: branch checkouts) even though there are no running vim processes.

**Comment by CloudyyUw** [comment]
I am having a similar problem.
I use neovim, and whenever I close it, the node instances of `tsserver` don't close.

**Comment by chemzqm** [comment]
`tsserverForkStart` not used any more, try upgrade coc-tsserver.
