### ISSUE TITLE
Feature request: import suggestion only for current cursor

### ISSUE THREAD

**Issue by lo1tuma** [neoclide/coc-tsserver#282]
Hi, I’ve switched from `nvim-typescript` to `coc` recently and so far I’m quite happy but I’m missing one feature. I don’t really like auto imports, since they are quite often wrong in bigger projects. `nvim-typescript` provided a command `:TSImport` which suggested several possible imports for the identifier under the current cursor where you could then choose which one should be added to import statements of the current file. If there was only one suggestion, then the step of choosing something was skipped and the import statement was added directly.

Currently I have disable auto imports and add a `:OR` command which just runs `organizeImports`. Unfortunately this command also tries to import things for every unresolved identifier, even for still work-in-progress code that I want to change in the next minute. Additionally it seems like it sorts my existing import statements alphabetically, which is an undesired change for me.

**Comment by fannheyward** [comment]
Does code action work for you? Put your cursor on unresolved identifier and fire `<Plug>(coc-codeaction-cursor)`, coc will list available imports.

<img width="683" alt="截屏2021-04-14 下午5 08 40" src="https://user-images.githubusercontent.com/345274/114685028-1294a300-9d44-11eb-9a07-8f86afc79042.png">

**Comment by chemzqm** [comment]
You have to use codeActions

**Comment by lo1tuma** [comment]
Nice,  I wasn’t aware of that feature. Thank you.
