### ISSUE TITLE
nvim with coc-tsserver becomes really slow after long periods of time

### ISSUE THREAD

**Issue by lucasvinhas** [neoclide/coc-tsserver#283]
When I'm using coc for long periods of time with the coc-tsserver plugin, nvim starts to become really, really slow. Initially, I thought that the problem was the number of buffers, but  then I realized that even when I'm working with a small number of buffers it also gets slow after 2-3 hours of work. I know this is impossible to reproduce but I wonder if there is anything I can do do debug this ?

**Comment by chemzqm** [comment]
If your vim slow checkout `:h :profile`, if your tsserver get slow to response, use `:CocRestart`
