### ISSUE TITLE
Not working in a monorepo.

### ISSUE THREAD

**Issue by AvKat** [neoclide/coc-tsserver#284]
I use neovim as my primary editor with coc.nvim installed.

I recently started a project, a monorepo, and installed typescript in all the packages.
Whenever I open any of those projects in neovim, coc warns me that there is no tsserver installed. No features work.

What can I do to make it work ?

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc-tsserver#troubleshooting

**Comment by AvKat** [comment]
I still can't figure it out. Could you please help me?
@chemzqm
