### ISSUE TITLE
How to add tsserver plugins with new filetype

### ISSUE THREAD

**Issue by DarwinSenior** [neoclide/coc-tsserver#287]
I realised that now there is a new plugin for svelte within typescript.
https://github.com/sveltejs/language-tools/tree/master/packages/typescript-plugin

Do you know how to add this plugin to enable tsserver on svelte files?

**Comment by chemzqm** [comment]
You can't, that plugin of tsserver is supposed to make tsserver work with svelte code inside typescript or javscript file.
