### ISSUE TITLE
Auto import with CommonJS

### ISSUE THREAD

**Issue by lioaslan** [neoclide/coc-tsserver#293]
## Describe
Can't require from module.exports or exports
## Code
```javascript
// root/a/b/c.js
'use strict';

module.exports = {
  LOGIN_WARNING: 'LOGIN_WARNING',
  RESET_PASSWORD: 'RESET_PASSWORD'
}
```
```javascript
// root/d/e/f.js
console.log(RESET_PASSWORD)
```
```json
// jsconfig.js
{
  "compilerOptions": {
    "module": "commonJS",
    "allowSyntheticDefaultImports": true
  },
  "exclude": ["node_modules"],
  "include": ["utils/*", "lib/**/*"] 
}
```
## Expectation
Show suggestion for `RESET_PASSWORD`
## Actuality
![image](https://user-images.githubusercontent.com/24852182/120741765-d7327b80-c51f-11eb-882e-43694d870e61.png)

Moreover, I don't have any configuration about tsserver in `coc-settings.json`

**Comment by chemzqm** [comment]
Send your feature request to typescript project.

**Comment by lioaslan** [comment]
I don't think this is the shortcoming of `typescript`. I tried with `VS Code` and it worked well.

**Comment by fannheyward** [comment]
<img width="705" alt="截屏2021-06-04 下午6 14 35" src="https://user-images.githubusercontent.com/345274/120786375-b9393b00-c560-11eb-90e3-66600b171aad.png">

**Comment by lioaslan** [comment]
Thanks for the great update
