### ISSUE TITLE
Auto-completing TSX component results in parentheses

### ISSUE THREAD

**Issue by jacksonludwig** [neoclide/coc-tsserver#296]
In react/tsx/jsx, components can be functions like this:

```tsx
export default function ExampleComponent() {
  return (
    ...
  );
}
```
When trying to use this component inside another, you should write it like this:
```tsx
<ExampleComponent />
```
However, when using completion to select `ExampleComponent`, it is completed as `ExampleComponent()` instead. It seems that tsserver is mistaking `ExampleComponent` for a normal function instead of a react component.

I'm using the latest release branch of COC, and the most updated version of coc-tsserver. I'm on neovim nightly.

Setting   `"typescript.suggest.completeFunctionCalls"` to `false` is a workaround for this issue, but of course disables parens in all completions.

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by chemzqm** [comment]
Can't reproduce with typescript 4.2.x.
