### ISSUE TITLE
Syntax error with .tsx files - CoC does not recognise .tsx files to have .jsx syntax

### ISSUE THREAD

**Issue by jininvt** [neoclide/coc-tsserver#299]
I am getting errors on all TSX / JSX code in my .tsx file. Attached is a screenshot of the ```App.tsx``` file you get when you run ```npx create-react-app --template typescript repo-name```

One example of an error I'm seeing is:
```[tsserver 2304] [E] Cannot find name 'className'.```

It seems that CoC does not recognise that .tsx files have .jsx syntax. Btw there is no issue with any .jsx files.

![Screenshot 2021-06-24 at 9 04 06 PM](https://user-images.githubusercontent.com/19875264/123267969-2c1a4e00-d530-11eb-80c2-8a085b96cf8b.png)

**Comment by chemzqm** [comment]
Fix your filetype option.

**Comment by jininvt** [comment]
And how can I do that exactly? I've followed the instructions on the [CoC Github page](https://github.com/neoclide/coc.nvim) but the problem is still occurring. 

Below is the updated coc-settings.json file. I've added in Lines 14 to 19.

<img width="1440" alt="Screenshot 2021-06-25 at 8 30 09 PM" src="https://user-images.githubusercontent.com/19875264/123425156-5af9f800-d5f4-11eb-8d8e-795177ed34bc.png">

**Comment by chemzqm** [comment]
Please read https://github.com/neoclide/coc-tsserver#coc-tsserver

**Comment by jininvt** [comment]
From what I understand I have to use g:coc_filetype_map to map tsx to typescriptreact. I have look at the example [here](https://github.com/neoclide/coc.nvim/blob/release/doc/coc.txt) but it still doesn't work. What am I missing?

<img width="1440" alt="Screenshot 2021-06-25 at 9 06 21 PM" src="https://user-images.githubusercontent.com/19875264/123429174-39e7d600-d5f9-11eb-8ace-8ffe24de22e8.png">

**Comment by saltedpotatos** [comment]
For anyone else having this issue, [this](https://www.reddit.com/r/neovim/comments/it6xe5/coctsserver_reports_a_lot_of_errors_in_tsx_files/g5gdyb1/) fixed it for me. 

Quoting here in case link goes down:

>Had a similar issue. Does :set ft output typescript?
>
>If so, tsserver needs filetype to be ˋtypescriptreact` to parse your file as intended.
>
>Add the following to your init.vim file:
```
augroup ReactFiletypes
  autocmd!
  autocmd BufRead,BufNewFile *.jsx set filetype=javascriptreact
  autocmd BufRead,BufNewFile *.tsx set filetype=typescriptreact
augroup END
```

**Comment by rafaVls** [comment]
> For anyone else having this issue, [this](https://www.reddit.com/r/neovim/comments/it6xe5/coctsserver_reports_a_lot_of_errors_in_tsx_files/g5gdyb1/) fixed it for me.
> 
> Quoting here in case link goes down:
> 
> > Had a similar issue. Does :set ft output typescript?
> > If so, tsserver needs filetype to be ˋtypescriptreact` to parse your file as intended.
> > Add the following to your init.vim file:
> 
> ```
> augroup ReactFiletypes
>   autocmd!
>   autocmd BufRead,BufNewFile *.jsx set filetype=javascriptreact
>   autocmd BufRead,BufNewFile *.tsx set filetype=typescriptreact
> augroup END
> ```

I had the same problem. and this solution fixed it for me.
