### ISSUE TITLE
Freeze on go-to definition

### ISSUE THREAD

**Issue by academo** [neoclide/coc-tsserver#301]
At times when trying to go to definition or implementation of symbols the editor freezes and it won't come out of it until the tsserver is killed or nvim is killed.

This is normal when the server is starting up but it also happens when it simply can't find a definition and the server stays looking for one (with high CPU consumption).

I am not sure if this is a tsserver error or in this plugin.

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
