### ISSUE TITLE
type definitions on imports are always "any"

### ISSUE THREAD

**Issue by andykais** [neoclide/coc-tsserver#302]
given these files:

```ts
// src/database.ts
export class Database {}
```
```ts
// src/index.ts
import { Database } from './database'

class Logger {}

class Context {
  db = new Database()
  logger = new Logger()
}
```
tsconfig.json:
```json
{
  "compilerOptions": {
    "outDir": "build",
    "sourceMap": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "alwaysStrict": true,
    "strict": true,
    "declaration": true,
    "declarationMap": true
  },
  "include": ["src/**/*.ts"]
}
```

using "K" on a type definition that is imported will always be `any`
![screenshot(658)](https://user-images.githubusercontent.com/6627147/125652563-b6b2e357-a8a7-47e5-a00e-a41f31c16eed.png)
types defined within a file are correctly shown:
![screenshot(657)](https://user-images.githubusercontent.com/6627147/125652612-13572949-c60d-49f3-a0c3-038b38dff77b.png)

my CocConfig:
```json
{
  "suggest.autoTrigger": "none",
  "diagnostic.enable": false,
  "signature.preferShownAbove": false
}
```

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
