### ISSUE TITLE
Cannot use JSX unless the '--jsx' flag is provided when using "jsx" field as "react-jsx" in tsconfig.json

### ISSUE THREAD

**Issue by ohmydieu** [neoclide/coc-tsserver#303]
Argument for '--jsx' option must be: 'preserve', 'react-native', 'react'
But the newest `tsconfig.json` from create-react-app is 'react-jsx' and coc-tsserver alerts the error:

```
Cannot use JSX unless the '--jsx' flag
```

It seems the TS version coc-tsserver is out of date.
Hope it could be fixed soon!

**Comment by chemzqm** [comment]
It's problem with schema of coc-json

**Comment by EdmundsEcho** [comment]
Apologies for not tracking here; I'm getting the same error.  If it's a problem with schema of coc-json, what am I supposed to do to change that?
