### ISSUE TITLE
Is there a way to access tsserver from inside a running Docker container?

### ISSUE THREAD

**Issue by bttf** [neoclide/coc-tsserver#304]
Hi,

I'm running into an issue with my local development environment that runs on docker compose.

My node_modules are installed on a volume that is accessible inside the docker container, and is not accessible on the host machine.

Locally, tsserver tries to find modules on the local disk, but fails to do so since they are all housed within the volume.

I thought about how to solve this outside of doubly installing node_modules locally since it's not really a clean solution.

It seems like one way would be to have tsserver run inside the container, and have coc-tsserver leverage that instead of a local instance.

Has anyone had experience with this? Would the proposed solution be possible? Thanks

**Comment by chemzqm** [comment]
Use `tsserver.ignoreLocalTsserver` configuration.
