### ISSUE TITLE
add or remove braces to arrow function

### ISSUE THREAD

**Issue by linde12** [neoclide/coc-tsserver#309]
I cant get this feature to work (or maybe it needs implementation in coc-tsserver?) It should be available in typescript: https://github.com/Microsoft/TypeScript/pull/23423

The only option i get is to create a function statement. I want to be able to quickly add braces around an arrow function, e.g. if i have something like:

```tsx
<button onClick={() => setCount(count + 1)}>
  Click me!
</button>
```

Then i want to be able to quickly convert that arrow function to a block as such:

```tsx
<button onClick={() => {
  return setCount(count + 1)
}}>
  Click me!
</button>
```

![image](https://user-images.githubusercontent.com/3235069/131359621-2f7bd414-1724-4674-bca7-f10a470092db.png)

vim version: NVIM v0.5.0
node version: v14.17.2
coc.nvim version: 0.0.80-3086844413
coc.nvim directory: /home/linde/.vim/plugged/coc.nvim
term: alacritty
platform: linux

**Comment by fannheyward** [comment]
In my tests, put your cursor on `=>` and fire `<Plug>(coc-codeaction-cursor)`, you will get:

<img width="640" alt="截屏2021-08-31 上午9 52 35" src="https://user-images.githubusercontent.com/345274/131428792-77c52fc9-55b0-4554-8f67-8b08fd003ae0.png">

After the first action executed:

<img width="279" alt="截屏2021-08-31 上午9 53 20" src="https://user-images.githubusercontent.com/345274/131428835-87069a00-1e5d-41fc-b174-80ff74536c8b.png">

**Comment by fannheyward** [comment]
What's your coc-tsserver version? I'm using 1.8.6.

**Comment by chemzqm** [comment]
Check log of your tsserver https://github.com/neoclide/coc-tsserver#troubleshooting

**Comment by linde12** [comment]
> In my tests, put your cursor on `=>` and fire `<Plug>(coc-codeaction-cursor)`, you will get:
> 
> <img alt="截屏2021-08-31 上午9 52 35" width="640" src="https://user-images.githubusercontent.com/345274/131428792-77c52fc9-55b0-4554-8f67-8b08fd003ae0.png">
> 
> After the first action executed:
> 
> <img alt="截屏2021-08-31 上午9 53 20" width="279" src="https://user-images.githubusercontent.com/345274/131428835-87069a00-1e5d-41fc-b174-80ff74536c8b.png">

Thank you! I was using `coc-codeaction`, i didn't know of `coc-codeaction-cursor` :smiley:

**Comment by chemzqm** [comment]
coc-codeaction-cursor is recommended
