### ISSUE TITLE
Tsserver works for Javascript, but doesn't for Typescript

### ISSUE THREAD

**Issue by lucasvinhas** [neoclide/coc-tsserver#31]
The title is self-explanatory. Tsserver works perfectly for Javascript, but doesn't work at all for typescript. Coc only shows completions for buffers and snippets.

**Comment by chemzqm** [comment]
Make usre your have filetype typescript by `:echo &filetype`

**Comment by lucasvinhas** [comment]
yes, i have.` :echo &filetype` returns `typescript`

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc-tsserver#trouble-shooting

**Comment by lucasvinhas** [comment]
> https://github.com/neoclide/coc-tsserver#trouble-shooting

I tried that. Both `CocCommand tsserver.openTsServerLog` and `CocCommand workspace.showOutput tsserver` didn't do anything.
It is supposed to open the file? or I need to manually search it?

**Comment by chemzqm** [comment]
Yes, check `:CocList services` to see if tsserver have started.

**Comment by lucasvinhas** [comment]
> Yes, check `:CocList services` to see if tsserver have started.

It was running. I stopped and started again. Doing that, now the completion is working, but the linting works for a while and  then stops. I need to toggle the running service again to update the lint
