### ISSUE TITLE
Speed up tsserver

### ISSUE THREAD

**Issue by pavlo-hadzheha** [neoclide/coc-tsserver#314]
I am here due to the following note:

    **Note**: tsserver could be quite slow to initialize on big project, 
    exclude unneunnecessary files in your jsconfig.json/tsconfig.json.

Could someone help me set up an angular project folder to exclude an enormous node_modules folder?

![image](https://user-images.githubusercontent.com/44346150/134009946-f1db77ca-2acc-4784-9c16-9703b1b1d635.png)

My tsconfig.json:
![image](https://user-images.githubusercontent.com/44346150/134010282-56617ee4-3123-4ef2-9a0c-605e98bc8126.png)

**Comment by chemzqm** [comment]
There is https://github.com/iamcco/coc-angular for angular project, and we have `typescript.preferences.includePackageJsonAutoImports` configuration which might helps.

**Comment by chemzqm** [comment]
That's not too many files, maybe you need SSD.
