### ISSUE TITLE
insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets

### ISSUE THREAD

**Issue by kabo** [neoclide/coc-tsserver#32]
Hi,

It'd be great if coc-tsserver could add something like
`typescript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets`
and
`javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets`

Right now it's formatting from `[ 't1', 't2' ]` to `['t1', 't2']`. I'd like to keep the spaces at the beginning and the end.

**Comment by chemzqm** [comment]
It can only be supported if tsserver support this, so send request to https://github.com/microsoft/TypeScript/issues

**Comment by kabo** [comment]
I think the tsserver does support it.
https://github.com/microsoft/TypeScript/blob/15daf42b2c0bc4f06970c9e4688f1a93bff0f7a0/src/server/protocol.ts#L2932

**Comment by chemzqm** [comment]
Need upgrade to add new format options.

**Comment by kabo** [comment]
Thanks!
