### ISSUE TITLE
TS Server Very Slow Diagnostics, Suggestions, etc

### ISSUE THREAD

**Issue by excalios** [neoclide/coc-tsserver#327]
ts server has been very slow whether it is showing diagnostics or autocomplete suggestions and etc.
![image](https://user-images.githubusercontent.com/42968441/142761631-92559e18-dfea-435f-b175-663007425f74.png)
I tried it by deleting an import statement and the diagnostics error showed 13 seconds after as the picture above. Even autocomplete showed very slowly sometimes auto import doesn't even work at all. I am genuinely not sure why. I tried deleting watchman there's no noticeable change. Tried coding on vscodium and it works fine and fast.

**Comment by fannheyward** [comment]
It's difficult to reproduce the slow type issue. What's your TypeScript version? What's the size of your project? I'm using the coc-tsserver to work on the coc.nvim project, I think it's big enough, didn't came across the slowness .

**Comment by excalios** [comment]
You can take a look at the projects [here](https://github.com/excalios/garudahacks-namatim) I'm unsure as to why it happens not sure if it's my neovim config or tsconfig. My updatetime is 50 I'm on nvim 0.5.1

**Comment by excalios** [comment]
![image](https://user-images.githubusercontent.com/42968441/143276881-62ae944d-44a0-4cea-a196-6c6b24e0c3ad.png)
I just checked this and does this have anything to do with it? The "trying to cancel ongoing request with sequence number x"

**Comment by excalios** [comment]
So I think I found the problem but I don't know how to fix it. I keep trying to find what's wrong by deleting an import and then undoing it. I found it's not all the files that are slow it's only model.ts files. I thought at first it was because of the import of other model.ts files which is partially true. I thought it has something to do with the class or because of extending objection model. Like it was too big or something. I found that it's this part of the code
![image](https://user-images.githubusercontent.com/42968441/143445610-4efc4435-6bfa-4fb8-8de7-bc1fd103d211.png)

When importing other model.ts for the modelClass on this part of the code it became really slow. If I remove this part of the code and import the models it works just fine. I don't know why it's like this but on vscodium it works just fine no performance problem. On my older projects too it's just fine there's no problem at all.

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by chemzqm** [comment]
We've add `tsserver.enableTracing` support, you can find trace file by checkout the output of tsserver.

**Comment by chemzqm** [comment]
The tsserver could be slow after some time, use latest typescript > 4.9 and disable logging of tsserver should helps.
```json
  "tsserver.log": "off",
  "tsserver.trace.server": "off",
```
See https://devblogs.microsoft.com/typescript/announcing-typescript-4-9/#file-watching-now-uses-file-system-events

**Comment by duongapollo** [comment]
big thanks @chemzqm 

update Typescript to 4.9.3 solved the diagnostic issue
