### ISSUE TITLE
Snippet Completions for JSX Attributes

### ISSUE THREAD

**Issue by TrietMinh799** [neoclide/coc-tsserver#328]
With the release of typescript 4.5 and vs code also merged it, so would this feature be added to coc-tsserver ?

[Snippet Completions for JSX Attributes](https://devblogs.microsoft.com/typescript/announcing-typescript-4-5/#jsx-attribute-snippets)

**Comment by fannheyward** [comment]
This https://github.com/neoclide/coc-tsserver/pull/319?

**Comment by TrietMinh799** [comment]
yes?

**Comment by TrietMinh799** [comment]
Would that pull request be merged to coc-tsserver?

**Comment by fannheyward** [comment]
Of course.

**Comment by TrietMinh799** [comment]
Ok, and can I ask when that pull request be merged to coc-tsserver ?

**Comment by TrietMinh799** [comment]
if you plan to merge it then I will close this issue now
