### ISSUE TITLE
Specifying location of tsconfig.json

### ISSUE THREAD

**Issue by thedelchop** [neoclide/coc-tsserver#33]
My current setup uses `.tsconfig.json` instead of `tsconfig.json`.  Is it possible to inform `coc-tsserver` of this somehow?  As soon as I rename my `tsconfig` file from `.tsconfig.json` to `tsconfig.json` it works great.

**Comment by chemzqm** [comment]
It can't for now, since tsconfig.json used for locate the project root, and I don't know how to make tsserver use custom configuration file name as language server.
