### ISSUE TITLE
How do I remove tslint from the commands list?

### ISSUE THREAD

**Issue by NullVoxPopuli** [neoclide/coc-tsserver#34]
I don't even have tslint installed
```
let g:coc_global_extensions = [
  \ 'coc-tsserver',
  \ 'coc-css',
  \ 'coc-json',
  \ 'coc-html',
  \ 'coc-vimlsp',
  \ 'coc-highlight'
\ ]
```

and yet:

![image](https://user-images.githubusercontent.com/199018/58657872-38019a80-82ed-11e9-901e-5942ac941903.png)

**Comment by chemzqm** [comment]
Checkout your extensions list

**Comment by NullVoxPopuli** [comment]
![image](https://user-images.githubusercontent.com/199018/58665018-ffb68800-82fd-11e9-8ecb-786d7c645874.png)

**Comment by NullVoxPopuli** [comment]
HM

**Comment by NullVoxPopuli** [comment]
thanks :)
