### ISSUE TITLE
Syntax colors along with other plugins.

### ISSUE THREAD

**Issue by CamiloGPT** [neoclide/coc-tsserver#340]
I am using this plugin for syntax [yats.vim](https://github.com/HerringtonDarkholme/yats.vim). <br />

Before tsserver starts:
![enable yats.vim](https://i.ibb.co/WfC0wH2/Selecci-n-003.png)
<br />
After tsserver starts:
![enable tsserver](https://i.ibb.co/c8wKGKs/Selecci-n-004.png)

**Why did the colors change?**
The white color is what predominates the most.

pdt: I don't like having everything in white. Thanks

**Comment by chemzqm** [comment]
Use configuration `"coc.preferences.semanticTokensHighlights": false`, will be changed in the future.
