### ISSUE TITLE
Update import path on file rename using watchman is not working

### ISSUE THREAD

**Issue by andrescuco** [neoclide/coc-tsserver#341]
On my work laptop (Intel Macbook Pro 2019) I constantly use `:CocCommand workspace.renameCurrentFile` to rename the current file and automatically update the imports on other files, as suggested on the readme I installed watchman so I could use this functionality. 

Recently I got an M1 Macbook Air and installed watchman, but noticed that when I run the command, the import paths are not being updated. When I run `:CocCommand workspace.clearWatchman` I get the error: `executing job failed: No such file or directory`. It seems like it's not being initialized, when I run `:CocCommand workspace.showOutput` I don't see anything regarding watchman.

Any idea on what may be causing the issue?

Could be related to https://github.com/neoclide/coc-tsserver/issues/278

**Comment by chemzqm** [comment]
Seems your watchman not working.

**Comment by chemzqm** [comment]
Make sure your watchman is working in your command line.
