### ISSUE TITLE
When disableAutomaticTypeAcquisition is set to true, all hover documentation is rendered as [object Object]

### ISSUE THREAD

**Issue by dmitmel** [neoclide/coc-tsserver#343]
Reproduction:

1. Create this minimal vimrc:
   ```vim
   set rtp^=~/.config/nvim/plugged/coc.nvim
   let g:coc_global_extensions = ['coc-tsserver']
   let g:coc_user_config = {
   \ 'tsserver.disableAutomaticTypeAcquisition': v:true,
   \ }
   ```
2. `nvim -u minimal_vimrc.vim test.js`
3. Type `console.log` into the buffer
4. Position the cursor over `log`
5. `:call CocAction('doHover')`
6. The following popup is displayed: \
   ![image](https://user-images.githubusercontent.com/15367354/149565374-8559dff2-435b-4631-9d1f-98e6bb7c40fe.png)

**Comment by chemzqm** [comment]
Install latest coc-tsserver by run `:CocUpdate`

**Comment by dmitmel** [comment]
Thanks, it did the trick.
