### ISSUE TITLE
Error [tsserver 6133] 

### ISSUE THREAD

**Issue by costerik** [neoclide/coc-tsserver#345]
`[tsserver 6133] [I] 'React' is declared but its value is never read`

This error is thrown on NeoVim in `ts` and `tsx` files

**Comment by TrietMinh799** [comment]
you can [read this post](https://stackoverflow.com/questions/64541040/jsx-can-be-used-without-importing-react), for more details,

**Comment by chemzqm** [comment]
It's information diagnostic from tsserver, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
