### ISSUE TITLE
jsxattribute complete in wrong way

### ISSUE THREAD

**Issue by TrietMinh799** [neoclide/coc-tsserver#346]
My config
```vim
call plug#begin('~/.vim/plugged')

Plug 'neoclide/coc.nvim', {'branch': 'master', 'do': 'yarn install --frozen-lockfile'}

call plug#end()

filetype plugin indent on
syntax enable

set number
set relativenumber
set expandtab
set shiftwidth=2
set shiftround
set tabstop=2
set autoindent
set smartindent
set cmdheight=2
set updatetime=300
set shortmess+=c
set signcolumn=number
set clipboard+=unnamedplus
```

When I types attribute of p tag like this
![Screenshot from 2022-01-19 21-21-06](https://user-images.githubusercontent.com/57322084/150151065-963d3972-3b21-45ee-963a-4b78379c0cf3.png)

I want classname completed like 
classname="|"

but the result is in the wrong way
![Screenshot from 2022-01-19 21-22-43](https://user-images.githubusercontent.com/57322084/150151389-4a8cb970-d69e-4885-8e59-f76ce4f5df58.png)

[tsserver.log](https://github.com/neoclide/coc-tsserver/files/7897905/tsserver.log)

**Comment by chemzqm** [comment]
No such feature, since you may want to input `={` instead.
