### ISSUE TITLE
Suggestions from project stop intermittently

### ISSUE THREAD

**Issue by dj-foxxy** [neoclide/coc-tsserver#347]
In my TS project, suggestions from the project (not external, e.g., browser objects) stop appearing in the suggestions list. Type checking still works, just suggestions stop. `:CocRestart` temporary fixes the issue.

I'm not sure what  information to provide so let me know and I'll add it to this issue.

Thanks :)

**Comment by chemzqm** [comment]
Seems your tsserver stop working for some reason https://github.com/neoclide/coc-tsserver#troubleshooting

**Comment by dj-foxxy** [comment]
Thanks. I've updated my config as per your link and will post again when it next happens.

**Comment by dj-foxxy** [comment]
These are logs just after it happened. I looked at the end of the logs but I don't know enough about coc or tsserver to see an issue. Here are the full logs, hope this helps.

https://foxdogstudios.com/static/peter/tsserver.log
https://foxdogstudios.com/static/peter/tsserver.output

**Comment by dj-foxxy** [comment]
I tried settings the max TS server memory really high  (`"tsserver.maxTsServerMemory": 16384`) to see that would help. The issue still occurred and looking at htop I can see that the server is still running and using a small amount of memory.

**Comment by chemzqm** [comment]
The tsserver could be slow after some time, use latest typescript > 4.9 and disable logging of tsserver should helps.
```json
  "tsserver.log": "off",
  "tsserver.trace.server": "off",
```
