### ISSUE TITLE
Code lens references display on line above instead of in-line

### ISSUE THREAD

**Issue by tylucaskelley** [neoclide/coc-tsserver#348]
Not sure when exactly this started happening, but at some point code lens references started displaying on top of the relevant code rather than next to it, making it less usable IMO - 

![image](https://user-images.githubusercontent.com/5448759/150589708-6c2f1f51-78b7-43cc-b489-edbc4e7d224a.png)

Can provide any additional info if needed, but some basics:

1. OS: Fedora 35
2. Neovim version: 0.6.1
3. COC version: 0.0.80-03a532b544
4. TS server version: 1.9.8
5. Node version: 16.13.2

**Comment by chemzqm** [comment]
`:h coc-config-codelens`
