### ISSUE TITLE
Randomly stopped understanding TSX

### ISSUE THREAD

**Issue by rivertam** [neoclide/coc-tsserver#35]
Hey, so yesterday I had this random problem where tsserver stopped understanding TSX. I'm starting to get errors like `Operator '<' cannot be applied to type 'boolean' and 'StyledComponentClass'` as errors/annotations.

I hadn't changed any configurations or updated or anything when this started happening, but I updated coc, coc-tsserver, and neovim since then and there's been no resolution.

I suspect this is an error on my end, but I don't really know where to check. My Create React App instance has no problem parsing these files. My `init.vim` has only one line mentioning coc: `Plug 'neoclide/coc.nvim', { 'tag': '*', 'do': './install.sh' }` and the only line about tsx is to call Prettier.

Do you have any recommended debugging steps? It seems like the typescript server calls are not including the fact that it's tsx for some reason.

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc-tsserver#trouble-shooting

**Comment by chemzqm** [comment]
In your tsconfig.json, add `"jsx": "react",` in `"compilerOptions"`.

Make your filetype to `typescript.tsx`.
