### ISSUE TITLE
Auto import suggestions are not complete

### ISSUE THREAD

**Issue by hexh250786313** [neoclide/coc-tsserver#352]
`coc-tsserver`'s auto import suggestions are less than VSCode's. `coc-tsserver`'s suggestions are not complete actually.

Both of Coc and VSCode work in my react project. There are several components have a same name. I input the compoent name. Then I get only one auto import suggestion from Coc but full suggestions from VSCode.

I have no idea what the issue related to.

**Comment by hexh250786313** [comment]
I think it is probably because of the not showing components are very deep in my project. It seems `coc-tsserver` cannot find such components that have a deep path.

**Comment by chemzqm** [comment]
It may be coc-tsserver's issue or not, you have to checkout the log https://github.com/neoclide/coc-tsserver#troubleshooting

**Comment by hexh250786313** [comment]
I run `:CocCommand tsserver.openTsServerLog` and get `completionInfo`. That's a json file has 6156 lines and I find the component name I input which is only one result.

I do the same in VSCode and get a 6270 lines json file. There are 5 components info about my input. Then I copy the other 4 items into coc-tsserver's `completionInfo`. I get a 6270 lines file as expected.

That is to say, the output info from coc-tsserver is indeed missing this part of the result.

**Comment by hexh250786313** [comment]
@chemzqm I have tried lsp-tsserver and got the same result as coc-tsserver. Maybe there is something else different between VSCode's tsserver and coc-tsserver(or lsp-tsserver). And VSCode's has better performance.

**Comment by chemzqm** [comment]
Please provide evidence, could be different tsserver version

**Comment by hexh250786313** [comment]
Ok, you are right maybe. I find VSCode's tsserver is `/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js` when my coc-tsserver use project-local tsserver.

But why `"tsserver.tsdk": "/home/<user>/.nvm/versions/node/v16.5.0/lib/node_modules/typescript/lib"` does not work for me then?

**Comment by chemzqm** [comment]
lib at the end is not needed

**Comment by hexh250786313** [comment]
@chemzqm Still not work. It only works after project's `node_modules/typescript` deteled. Is there any way to ignore the project-local tsserver?

By the way, `coc-tsserver` works beautifully using the global tsserver.

**Comment by chemzqm** [comment]
Use `"tsserver.ignoreLocalTsserver": true`, Readme need update for that.

**Comment by hexh250786313** [comment]
@chemzqm Thx. Now it works very well.
