### ISSUE TITLE
Support for `"imports"` and `"exports"` fields in package.json

### ISSUE THREAD

**Issue by MuhammadSawalhy** [neoclide/coc-tsserver#354]
I am using the ["exports"](https://nodejs.org/api/packages.html#exports) field in package.json with [self-referencing import](https://nodejs.org/api/packages.html#self-referencing-a-package-using-its-name) the files. But coc-definition and coc-reference doesn't work with theme new fields. 

Note: I was using `jsconfig.json` file to define my paths but switched to the new field because of FOMO... This was of defining alias or path was working with some tweak for webpack, babeljs, eslint. I thought they will work well with the new standard fields.

```json
  "name": "-",
  "exports": {
    "./*": "./src/*"
  }
```

```js
import whatEver from "-/some-file/in/src"; 
```

**Comment by chemzqm** [comment]
You need to configure jsconfig.json or tsconfig.json https://code.visualstudio.com/docs/languages/jsconfig

**Comment by MuhammadSawalhy** [comment]
This is a feature request 👈

**Comment by chemzqm** [comment]
That should be done by tsserver, send your feature request to tsserver, or you can create plugin for tsserver.

**Comment by MuhammadSawalhy** [comment]
> or you can create plugin for tsserver

And I will call it Yatss which stands for "yet another tsserver" 😂



> That should be done by tsserver, send your feature request to typescript team

Thank you! I will do that insha'Allah...
