### ISSUE TITLE
Best way to handle JSX / TSX

### ISSUE THREAD

**Issue by sQVe** [neoclide/coc-tsserver#36]
Hey :wave:,

[vim-polyglot](https://github.com/sheerun/vim-polyglot) recently changed their `jsx` and `tsx` provider, https://github.com/sheerun/vim-polyglot/commit/26c678b08d88b658ec6069eb2ada2b2ba21c5d39, and it's creating issues with `coc-tsserver` due to it using the `filetype` `javascript` and `typescript` for both regular files and files which include `jsx` and `tsx` syntax. This is going to be an issue due to the popularity of `vim-polyglot`. 

Is there a way to configure `coc-tsserver` to default to `jsx` or `tsx`? If no, what would be the best way to handle these issues? Are a `autocmd` looking on file extension the best way?

**Comment by sheerun** [comment]
Here's my answer: https://github.com/sheerun/vim-polyglot/issues/409#issuecomment-500154566

In short you could either override filetype of all js files to `javascript.jsx` or just support jsx in `javascript` filetype like vim-polyglot decided to follow.

**Comment by chemzqm** [comment]
It work with buffers with javascript as filetype but using jsx syntax since default jsx option is `preserve`.

**Comment by sQVe** [comment]
@chemzqm Roger. I'm confused on why it does not work for typescript though. It sets `preserve` for jsx option too.

**Comment by chemzqm** [comment]
For using typescript with react, it's recommended to use `.tsx` as file suffix and use autocmd to set the filetype to `typescript.tsx`.
