### ISSUE TITLE
Sort suggestions alphabetically by object property first?

### ISSUE THREAD

**Issue by muhammad-bin-zafar** [neoclide/coc-tsserver#361]
![image](https://user-images.githubusercontent.com/90899789/158764571-f5cdb466-f37b-4117-9aff-c21939b8ad34.png)

Can I have the object methods listed and sorted after the object properties?

**Comment by chemzqm** [comment]
`:h suggest.defaultSortMethod` which works when the items have same `sortText`.

**Comment by muhammad-bin-zafar** [comment]
So, to have properties listed before methods, I'd need to work with [this](https://github.com/neoclide/coc.nvim/blob/master/src/completion/complete.ts#L195) ?
