### ISSUE TITLE
LSP Snippets not expanding

### ISSUE THREAD

**Issue by otavioschwanck** [neoclide/coc-tsserver#362]
https://github.com/neoclide/coc.nvim/issues/3747

Tried to debug but it gives no errors.

Did not get any trace (dont know how to get it).

Including:
  "typescript.suggest.includeCompletionsWithSnippetText": false,

Make the problem goes away (but lose the snippet funcionality)

**Comment by chemzqm** [comment]
Can't reproduce, please provider verbose output https://github.com/neoclide/coc-tsserver#troubleshooting

**Comment by otavioschwanck** [comment]
Log: https://pastebin.com/TyULyECS
Output: https://pastebin.com/erjyYg3q

**Comment by chemzqm** [comment]
I see, typescript 4.6.3 changed it's signature, `isSnippet` not exists before.
