### ISSUE TITLE
Sometimes autocomplete snippets dont trigger

### ISSUE THREAD

**Issue by otavioschwanck** [neoclide/coc-tsserver#363]
Continuation of: https://github.com/neoclide/coc.nvim/issues/3754

Server log: https://pastebin.com/EVScjucP
Output: https://pastebin.com/AS0WCiBD

**Comment by chemzqm** [comment]
It's tsserver issue.

**Comment by otavioschwanck** [comment]
@chemzqm what can we do about it ?

**Comment by otavioschwanck** [comment]
@chemzqm i did a test on vscode and it inserts the id=""

**Comment by fannheyward** [comment]
@otavioschwanck tested coc + coc-html for the `<div id` issue, got `id=""`, as expected.

**Comment by otavioschwanck** [comment]
> @otavioschwanck tested coc + coc-html for the `<div id` issue, got `id=""`, as expected.

the problem is on typescriptreact

**Comment by chemzqm** [comment]
> @chemzqm i did a test on vscode and it inserts the id=""

Can't reproduce, please provide verbose output from tsserver

**Comment by otavioschwanck** [comment]
> > @chemzqm i did a test on vscode and it inserts the id=""
> 
> Can't reproduce, please provide verbose output from tsserver

@chemzqm Here:

Output: https://pastebin.com/fpUCSApD
Server Log: https://pastebin.com/8gHGtNiS
