### ISSUE TITLE
Jump-To-Definition no longer works on JSX-Tags

### ISSUE THREAD

**Issue by on3iro** [neoclide/coc-tsserver#364]
Hi,

I just recently updated coc-tsserver and somehow Jump-To-Definition won't work inside JSX-Tags anymore.

When I press my shortcut for go-to-definition the following window comes up:

![image](https://user-images.githubusercontent.com/8681413/164708943-74c509b1-fd61-4000-9e08-864dcef4e409.png)

Before the update I could press enter here and the correct file would open.
Now when I press enter nothing happens.

Is this a bug or do I have to adjust my config somehow?

Thanks in advance :)

**Comment by chemzqm** [comment]
Try minimal vimrc and checkout `:h coc-list-mappings-custom`
