### ISSUE TITLE
How do I disable coc-tsserver for a buffer based on filetype, but have coc-tsserver still running in typescript buffers?

### ISSUE THREAD

**Issue by NullVoxPopuli** [neoclide/coc-tsserver#368]
My overall problem is that I want to have multiple buffers open, containing files with extensions `ts` and `gts`, where 
`ts` - should have coc-tsserver enabled -- `filetype` is: `typescript`
`gts` - should not have coc-tsserver enabled -- `filetype` is: `typescript.glimmer` <- this is a custom syntax I'm helping with, and because tsserver doesn't allow syntax plugins, I gotta do some custom stuff (like what Vue and Svelte do), so I need tsserver turned off for this file type.

I tried doing this within vim
```vim
  autocmd FileType,BufEnter *.gjs,*gts call CocActionAsync('deactivateExtension', 'coc-tsserver')
  autocmd FileType,BufEnter *.js,*ts call CocActionAsync('activeExtension', 'coc-tsserver')
```

but active/deactivate extension applies to the whole vim instance and is not per-buffer.

I'm going to poke around the code here to see if I can find anything obvious to help out, because the behavior for vue and svelte is what I want -- just need to figure out how (custom language server -- which already exsits -- just need to disable tsserver)

**Comment by chemzqm** [comment]
You need filetype to be something like `typescriptglimmer`

**Comment by chemzqm** [comment]
Or use `g:coc_filetype_map`

**Comment by NullVoxPopuli** [comment]
> You need filetype to be something like `typescriptglimmer`

why? what's the difference? (other than the missing dot) and why does it have an effect?

> `g:coc_filetype_map`

I couldn't find any examples how this is used -- do you have examples?

**Comment by chemzqm** [comment]
`:h g:coc_filetype_map`

**Comment by NullVoxPopuli** [comment]
I added 
```vim
	let g:coc_filetype_map = {
		\ 'typescript.glimmer': '',
		\ }
```

to my init.vim, and confirmed it's set with `:echo g:coc_filetype_map`

however, tsserver is still starting up on `typescript.glimmer` files

**Comment by chemzqm** [comment]
Empty string not work since it considered as false value.

**Comment by NullVoxPopuli** [comment]
gotchya.

setting to
```vim
	let g:coc_filetype_map = {
		\ 'typescript.glimmer': 'glint',
		\ }
```

appears to do the trick! thanks!

next up -- coc-glint!

**Comment by NullVoxPopuli** [comment]
oh, is there a way a language server plugin can provide a config like this so users don't have to configure their `coc_filetype_map`?

**Comment by chemzqm** [comment]
No, main filetype from filetype with dot is considered as languageId, it should have a different language id.

**Comment by NullVoxPopuli** [comment]
oh :thinking: are there docs somewhere on filetype formats?

**Comment by chemzqm** [comment]
`:h 'filetype'` nothing else.

**Comment by NullVoxPopuli** [comment]
kind of overwhelming amount of text in there that mostly seems unrelated :sweat_smile:

**Comment by NullVoxPopuli** [comment]
the words "language" and "Id" do not appear in this document :upside_down_face:

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc.nvim/blob/master/src/model/document.ts#L128
