### ISSUE TITLE
Strange issue with JSDoc being replaced by `any`

### ISSUE THREAD

**Issue by rschristian** [neoclide/coc-tsserver#369]
I've ran into a really odd issue in which a promise's resolved value gets replaced with `any` under a number of circumstances, but only with `coc-tsserver`. I cannot reproduce this behavior in any other editor.

I tried to cut this down as much as I could, apologies if this is still a bit heavy. Removing anything else pretty much means it cannot be reproduced.

In the example below, `foo` is shown to have a type of `any`, however, doing any of the following steps corrects it:
 - Comment out `return console.log(foo);`
 - Keep the `return`, but remove the `console.log()`
 - Keep the `return` and the `console.log()`, but separate them (i.e., don't return the result of `console.log()`)
   - This is just to show that the issue is returning AND using the value. On their own they're not an issue.
 - Replace `String(context.params.foo)` with a static string (`"foo"`)
 - Call `Foo()` without passsing any params at all
 - Remove the `await` and notice `foo`'s type is correctly marked as `Promise<{ ... }>`

Calling `Foo()` from a plain async function or top-level doesn't result in this issue. It seems limited to this library's method.

[TS Server Log pastebin](https://pastebin.com/e8yTXgfA)

## Project

> src/index.js

```js
import { Router } from "worktop";

new Router().add("GET", "/:foo", async (_req, context) => {
    const foo = await Foo(String(context.params.foo));

    return console.log(foo);
});

/**
 * @param {string} stringParam
 * @returns {Promise<{ foo: number, bar: [] }>}
 */
async function Foo(stringParam) {
    return {
        foo: 0,
        bar: []
    };
}
```

> jsconfig.json

```json
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "Node",
    "allowJs": true,
    "checkJs": true
  },
  "include": [
    "src/index.js"
  ]
}
```

> package.json
```json
{
  "name": "tmp",
  "private": true,
  "dependencies": {
    "typescript": "^4.6.4",
    "worktop": "^0.8.0-next.13"
  }
}
```

**Comment by chemzqm** [comment]
> In the example below, foo is shown to have a type of any

Can't reproduce, works as expected for me.

**Comment by rschristian** [comment]
Well the instant-close feels a bit premature, any ideas what could lead to this? Definitely isn't working correctly for me.

![temp](https://user-images.githubusercontent.com/33403762/167070159-8495b789-4c9e-47b9-8559-e1d78fda7c35.png)

**Comment by chemzqm** [comment]
Maybe you have truned off `"typescript.suggest.jsdoc.generateReturns"`

**Comment by rschristian** [comment]
Hm, not sure if you just skimmed over the issue without reading or what, but I did say that there are a number of things I could do to have the type "magically" show up. Like the 4th item, swapping out `String(context.params.foo)` with a static string (`"foo"`).

![temp](https://user-images.githubusercontent.com/33403762/167071780-1e5e8d29-f449-4b15-9816-17ab45a6c1aa.png)

There's no reason why that should have an effect, but for some reason it does. The type CAN resolve (and does so quickly enough, I'm using the same isolated test case provided here), but in that specific code block, it doesn't. It's really weird.

I don't think it's possible to be and issue in user code/config.

**Comment by chemzqm** [comment]
You have to wait for sometime, it's issue with tsserver.
You should send report to typescript team.

**Comment by rschristian** [comment]
The type doesn't change over time. I get `any` even if I leave it for 3-4 minutes.

> You should send report to typescript team.

I can't reproduce the issue outside of coc, so the issue doesn't seem to be with typescript. Works just fine in CodeSandbox, for example.

**Comment by chemzqm** [comment]
From log of your tsserver
```
Info 90   [06:25:06.286] response:
    {"seq":0,"type":"response","command":"completionEntryDetails","request_seq":10,"success":true,"body":[{"name":"foo","kindModifiers":"","kind":"const","displayParts":[{"text":"const","kind":"keyword"},{"text":" ","kind":"space"},{"text":"foo","kind":"localName"},{"text":":","kind":"punctuation"},{"text":" ","kind":"space"},{"text":"any","kind":"keyword"}],"documentation":[],"tags":[]}]}
```
it's what it returned, I got same response first time and it gives me correct type after some seconds.

**Comment by chemzqm** [comment]
It happens on latest VSCode as well
<img width="803" alt="Screen Shot 2022-05-06 at 14 42 28" src="https://user-images.githubusercontent.com/251450/167080401-14362937-cc09-4229-bee2-32811865cbce.png">

**Comment by rschristian** [comment]
Hmm, weird. I don't know if it's just my method of get syntax hints (I don't have hover hints, just when I go to use the value) but nothing ever changes, the hint is completely static.

Odd that you can reproduce in VSCode, I think I tried for a half hour to get CodeSandbox to reproduce but never once did. Fair enough then, sorry to bring it up here.
