### ISSUE TITLE
typescript.tsx filetype does not format on save

### ISSUE THREAD

**Issue by richchurcher** [neoclide/coc-tsserver#37]
**Problem:** `.tsx` files have the correct `typescript.tsx` filetype, but do not format on save. Changing the extension to `.ts` or forcing the filetype with an autocmd fixes the issue, but unfortunately this causes the language server to treat JSX as typescript, which of course results in multiple errors.

It's probably worth noting that invoking Prettier directly works fine on the same file (`:CocCommand prettier.formatFile`).

**Versions:** coc.nvim 0.0.69, coc-tsserver 1.3.0, coc-prettier 1.1.1, vim-polyglot (latest), Neovim 0.3.7

**Related:** #36 , https://github.com/sheerun/vim-polyglot/issues/409

My `coc-settings.json`:
```
{
  "diagnostic.errorSign": "✖",
  "diagnostic.warningSign": "⚑",
  "diagnostic.infoSign": "⚑",
  "diagnostic.hintSign": "⚑",
  "coc.preferences.formatOnSaveFiletypes": [
    "css",
    "html",
    "javascript",
    "javascript.jsx",
    "json",
    "typescript",
    "typescript.tsx"
  ],
  "tsserver.formatOnType": false
}
```
I can produce a minimal `init.vim` if required (I did try with just yats.vim and coc.nvim installed, and the problem reproduced.)

If you can point me to the relevant section of the source, I'd be happy to contribute a PR, just not very familiar with the project.

**Comment by chemzqm** [comment]
You have to use typescriptreact as filetype,since tsserver use it.

**Comment by richchurcher** [comment]
That's it! Thanks, would never have thought to do that. I might chuck a quick note in the docs about it. Cheers!

**Comment by JikkuJose** [comment]
When I do `set filetype=typescriptreact` nothing happens. Infact the code highlighting even goes away.

**Comment by chemzqm** [comment]
`typescriptreact ` should be used in `"coc.preferences.formatOnSaveFiletypes"`

**Comment by mikohan** [comment]
I've added `"typscriptreact"` to `"coc.preferneces.formatOnSaveFileTypes"` and it works.
