### ISSUE TITLE
`<Plug>(coc-funcobj-i)` can't recognize getter/setter functions

### ISSUE THREAD

**Issue by persytry** [neoclide/coc-tsserver#371]
```vim
xmap if <Plug>(coc-funcobj-i)
omap if <Plug>(coc-funcobj-i)
xmap af <Plug>(coc-funcobj-a)
omap af <Plug>(coc-funcobj-a)
```
Above four map cannot work for getter/setter functions.
.eg typescript
```typescript
get fn():number{
    return 1;
}
set fn(v:number){
   this.v = v;
}
```

**Comment by persytry** [comment]
```typescript
class c{
    constructor(){
        ...
    }
}
```
The function `constructor` cannot to be recognize either.

**Comment by chemzqm** [comment]
It's expected since they're reported as properties.
Use other tools tree-sister might helps

**Comment by persytry** [comment]
I understand tree-sister and COC do similar things, but I prefer the COC approach. I don't think it's worth introducing another language parser because of this one problem.
Getters, setters, and constructor methods are treated only as properties, which I don't think makes sense; they should be both properties and functions (or methods).
If they can be thought of as functions (or methods), then they aren't `can't fix`, are they?
