### ISSUE TITLE
TypeError: import_coc26.SnippetString is not a constructor

### ISSUE THREAD

**Issue by Skythrew** [neoclide/coc-tsserver#374]
Hello there ! Today, I installed coc-tsserver extension and the installation successfullied but there was an error when I ran Neovim.
This is the error:
```TypeError: import_coc26.SnippetString is not a constructor (at line 11725)```

I went to the lib/index.js file and corrected this by changing the import_coc26.SnippetString to SnippetString only. I open this issue just to warn you about this error :)

**Comment by fannheyward** [comment]
Upgrade your coc.nvim to latest release please.
