### ISSUE TITLE
Javascript Support

### ISSUE THREAD

**Issue by AlexiHadjilambris** [neoclide/coc-tsserver#375]
Highlighting is not working as expected with Javascript.

I originally noticed this trying to edit javascriptreact files, and then realised that it is a general problem with Javascript.

I even tried creating a jsconfig.json file, to no effect.

Should this just work with coc-tsserver, or should I need an additional plugin?

**Comment by chemzqm** [comment]
This extension doesn't provide syntax highlight

**Comment by AlexiHadjilambris** [comment]
I'm not sure I understand what you mean.

```
[Trace - 19:18:06.709] Response received: documentHighlights (11). Request took 2 ms. Success: true Result: [
    {
        "file": "/Users/alexi/doot/pages/index.js",
        "highlightSpans": [
            {
                "start": {
                    "line": 15,
                    "offset": 8
                },
                "end": {
                    "line": 15,
                    "offset": 14
                },
                "kind": "none"
            },
            {
                "start": {
                    "line": 33,
                    "offset": 9
                },
                "end": {
                    "line": 33,
                    "offset": 15
                },
                "kind": "none"
            }
        ]
    }
]
```

This is the output from `:CocCommand workspace.showOutput`.

What extension is providing syntax highlight then, if it's not coc?

Can you just tell me how to fix this?
