### ISSUE TITLE
Feature: Inlay hints separator 

### ISSUE THREAD

**Issue by lmburns** [neoclide/coc-tsserver#382]
"It would be nice to be able to set the separator for the `inlayHints`. They all seem to be colons. And in something like `rust-analyzer`, there are the following options:
* `"rust-analyzer.inlayHints.typeHintsSeparator"`
* `"rust-analyzer.inlayHints.chainingHintsSeparator"`

**Comment by chemzqm** [comment]
PR welcome https://github.com/neoclide/coc.nvim/blob/9efd466e833848747bcee7c7792dca6d6806082b/src/handler/inlayHint/buffer.ts#L89

**Comment by chemzqm** [comment]
Fixed on coc.nvim, see `:h coc-config-inlayHint`

**Comment by chemzqm** [comment]
Fixed on coc.nvim, see `:h coc-config-inlayHint`
