### ISSUE TITLE
Inline template literal causes remaining code to be formatted like a string

### ISSUE THREAD

**Issue by willocho** [neoclide/coc-tsserver#386]
I have this code in a file. The issue is that all of the code following the template literal string is highlighted as a string, which is incorrect.

```
                const filePath = `${configDir}/state.config.json`;
                const intermediateFilePath = `${configDir}/state.config.tmp.json`;

                if (existsSync(intermediateFilePath)) {
                    /** shouldn't ever happen */
                    unlinkSync(intermediateFilePath);
                }
```

![image](https://user-images.githubusercontent.com/45779458/180022572-81c5984e-144d-4e2e-8e86-50da8558c7f1.png)

coc-settings.json:
```
{
    "languageserver": {
        "sql": {
            "command": "sql-language-server",
            "args" : ["up", "--method", "stdio"],
            "filetypes" : ["sql", "mysql"]
        }
    },
    "coc.preferences.jumpCommand": "tab drop"
}
```

If this isn't an issue with coc-tsserver please let me know and I'll try to find the right repository to open an issue in.

**Comment by chemzqm** [comment]
It's issue of vim's syntax highlight.
