### ISSUE TITLE
disable local file fields or put them at the end of hint list

### ISSUE THREAD

**Issue by laoshaw** [neoclide/coc-tsserver#388]
![image](https://user-images.githubusercontent.com/18351761/182040890-95e6c229-5146-4c09-a5ad-c8016b8694e6.png)

for js files using coc-tsserver, the list always put F(local Field) ahead of f (from TSC language server?), is there a way I sort 'f' ahead of 'F' in the middle column? tried coc-source-list and checked coc-tsserver configurations to no avail. other languages(c++, typescript worked fine)

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.
