### ISSUE TITLE
TSServer keeps exiting "normally"

### ISSUE THREAD

**Issue by mjarrettjohnson** [neoclide/coc-tsserver#39]
I'm working in a typescript react project where the every few minutes the tsserver will shutdown. 

i get the following logs

running CocOpenLog:
```2019-06-12T17:52:03.128 ERROR (pid:51272) [languages] - Source "tsserver-typescript" complete error: TypeError: Cannot read property 'type' of undefined
    at TypeScriptCompletionItemProvider.<anonymous> (/path/to/coc/extensions/node_modules/coc-tsserver/lib/server/features/completionItemProvider.js:99:34)
    at Generator.next (<anonymous>)
    at fulfilled (/path/to/coc/extensions/node_modules/tslib/tslib.js:104:62)
```

running CocInfo:
```
[Info  - 5:52:02 pm] TSServer normal exit
[Info  - 5:52:02 pm] TSServer log file: /path/to/bq/sh9c7r_n6_31x2l71lc6n5zr0000gn/T/coc-nvim-tsc.log
```

in the TSServer log file:
```
Info 8972 [17:52:2.96] request:
    {"seq":61,"type":"request","command":"completionInfo","arguments":{"file":"/path/to/file","line":70,"offset":16,"includeExternalModuleExports":true,"includeInsertTextCompletions":true}}
Info 8973 [17:52:2.96] Starting updateGraphWorker: Project: /path/to/tsconfig.json

```

I am currently running 3.5.1 but this was also occurring on 3.4.5. 

The strange part is tsserver says it is exiting normally. 

It would be great to get to the bottom of this OR provide a few to automatically restart TSServer on "normal" exit.

**Comment by chemzqm** [comment]
There's code to restart tsserver on exit.
I have no idea why tsserver exit, please provide full log.

**Comment by mjarrettjohnson** [comment]
How do i set up tsserver to automatically restart on exit?

**Comment by chemzqm** [comment]
You can't detect tsserver exit, but restart should just works.

**Comment by chemzqm** [comment]
I've fixed logic of restart, it might be caused by network access since it need network to download typings.

**Comment by mjarrettjohnson** [comment]
Restart was working normally.

My question was more whether I could set up a listener that would detect tsserver exiting and automatically restart it without me having to do it manually. 

Interestingly, using vs-code I notice that sometimes the ts-server will crash and then automatically restart, I will keep an eye on this and note how often vscode restarts. 

This seems to suggest it may not be an issue with coc-tsserver. 

Thanks for your help, and for the awesome plugin!

**Comment by chemzqm** [comment]
> whether I could set up a listener that would detect tsserver exiting

You can't, it should restart automatically.
