### ISSUE TITLE
Context Provider not detected on type

### ISSUE THREAD

**Issue by andresflorez16** [neoclide/coc-tsserver#392]
![image](https://user-images.githubusercontent.com/88729409/185522114-80482e1e-fcc7-4b07-8649-da765cd8b27c.png)
![image](https://user-images.githubusercontent.com/88729409/185522204-ccd9feef-21c7-4f60-bd9e-961add72460f.png)

how to avoid these errors?

**Comment by chemzqm** [comment]
Read docs of typescript.
