### ISSUE TITLE
JSDoc deprecation message missing only in static warning

### ISSUE THREAD

**Issue by rschristian** [neoclide/coc-tsserver#397]
## Reproduction Repository
https://github.com/rschristian/coc-tsserver-jsdoc-deprecation-bug

## Description

The JSDoc deprecation message, that is, the content provided alongside `@deprecated`, is missing in static warnings. It is working correctly in autocomplete.

I'll try to poke around, but I'm quite unfamiliar. Maybe it's as simple as stripping out the JSDoc messages in this one popup form, but not another?

## Desired Outcome

I'd like the warning popup to display the deprecation reason, not just the generic TS message about the function signature being deprecated. This would better mirror VSCode & other editors.

## Images

- Correctly showing in autocomplete:

    ![vim-auto](https://user-images.githubusercontent.com/33403762/187492022-28b3f032-43fe-4459-bede-d738d29b80f1.png)

- Not showing as a static warning

    ![vim-static](https://user-images.githubusercontent.com/33403762/187492719-c9557ce0-3b06-4dbf-92a5-f53086a0de30.png)

- VSCode displaying the deprecation message

    ![vscode-static](https://user-images.githubusercontent.com/33403762/187492333-6d09c052-7892-4267-b009-42cabe6434d4.png)

## Env

- nvim: v0.7.2
- coc.nvim:   0.0.82
- coc-tsserver: 1.11.5

- Result of `:CocInfo`
  ```
  ## versions

  vim version: NVIM v0.7.2
  node version: v16.16.0
  coc.nvim version: 0.0.82-d12cee8c 2022-08-30 19:51:36 +0800
  coc.nvim directory: /home/ryun/.vim/plugged/coc.nvim
  term: alacritty
  platform: linux
  ```

**Comment by chemzqm** [comment]
VSCode shows hove message along with diagnostic message, you can invoke `CocAction('doHover')`

**Comment by rschristian** [comment]
Is there a way to do that automatically? When it comes to deprecations, that "hover message" (or at least the doc comment) is a rather key part of the diagnostic.

**Comment by chemzqm** [comment]
Not yet

**Comment by rschristian** [comment]
Okay, thanks!
