### ISSUE TITLE
[question] How to use goto definition/declaration?

### ISSUE THREAD

**Issue by godlikeSwan** [neoclide/coc-tsserver#398]
In VSCode I can ctrl+click for example on `log` in `console.log('hi')` and this will open file where that log defined
Can I do actions like this in vim/coc/coc-tsserver?
I've tried `:call CocAction('definitions')`, `call CocAction('declarations')` implementations etc
In case of declarations this prints
`Error on request (declarations): declaration provider not found for current buff
er, your language server doesn't support it.`
Other commands seems to do nothing

I'm using vim 8.1

**Comment by chemzqm** [comment]
> Error on request (declarations): declaration provider not found for current buff er, your language server doesn't support it.

There are no declarations for js.

`:h coc-locations`

**Comment by godlikeSwan** [comment]
`:call CocAction('jumpDefinition')` helps 😄
