### ISSUE TITLE
Autocomplete snippet not always expand

### ISSUE THREAD

**Issue by otavioschwanck** [neoclide/coc-tsserver#399]
Example with typescript and Bootstrap-react (Button tag):

Its seems that is randomly expands.

Or maybe only when i go down a (when its in 3rd item), this way it expand most of times.
![Kapture 2022-09-04 at 20 18 35](https://user-images.githubusercontent.com/9551316/188330028-22a1a417-346b-4709-8fde-640068adb3ba.gif)

Infos:
https://pasteio.com/xjxMp6rXQqzf
https://pasteio.com/xbDke1p52DWQ

about the infos:
executed two times, one worked, one not

**Comment by chemzqm** [comment]
Maybe you have triggered `coc#pum#insert` which not insert snippet, or something else happened.

**Comment by otavioschwanck** [comment]
@chemzqm i used:
    inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm()
                                  \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

**Comment by chemzqm** [comment]
Try minimal vimrc

**Comment by otavioschwanck** [comment]
@chemzqm 

> Try minimal vimrc

my imap CR:
i  <CR>        & EunuchNewLine(coc#pum#visible() ? coc#pum#confirm(): "\<C-G>u\<CR>\<C-R>=coc#on_enter()\<CR>")

Only using CoC

**Comment by otavioschwanck** [comment]
@chemzqm one important detail:

the onClick, when dont complete the snippet, it adds the = (part or snippet)

the result is:
```
onClick=
```

And when expand all snippets it gets:
```
onClick={}
```

**Comment by chemzqm** [comment]
Always expand as expected for me, try latest tsserver by configure tsserver.sdk

**Comment by otavioschwanck** [comment]
> Always expand as expected for me, try latest tsserver by configure tsserver.sdk

how can i do that?

**Comment by otavioschwanck** [comment]
Ignoring the local tsserver fixes the problem
