### ISSUE TITLE
Error: cannot find module 'vscode-languageserver-protocol/lib/protocol.selectionRange.proposed"

### ISSUE THREAD

**Issue by neculaesei** [neoclide/coc-tsserver#40]
It seems like it's not there, to be sure it wasn't the last release I tried:
`yarn add vscode-languageserver-protocol@3.14.0`

Is this a vscode-language-server issue?
Thanks for the help!

![image](https://user-images.githubusercontent.com/3195552/59347586-badb1a00-8d1d-11e9-8b12-8f6795a9b29d.png)

**Comment by chemzqm** [comment]
Should be issues of package-lock.json, I've removed it from git.
Use yarn for install dependencies is recommended.

**Comment by chemzqm** [comment]
It's fixed now.

**Comment by neculaesei** [comment]
Thanks, it works!
