### ISSUE TITLE
Go to definition make neovim stop responding

### ISSUE THREAD

**Issue by otavioschwanck** [neoclide/coc-tsserver#400]
when i try to go to definition in some imported lib, that was upgraded, it just freezes neovim.

Reproduce:
Install a lib in a older version and import in some typescript code.
Upgrade the lib
Press gd on the imported item.

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc.nvim/wiki/F.A.Q#my-vim-is-blocked-sometimes
