### ISSUE TITLE
Autocomplete expansion jump inserts $1 and jumps past insert point

### ISSUE THREAD

**Issue by alextes** [neoclide/coc-tsserver#403]
I'm guessing this is just something in my config somewhere, trying to narrow it down, any idea why this would be happening?

If not, that's fine, I'll keep searching until I have a minimal reproducible example 👍 .

Can someone confirm that this does have something to do with this specific extension and not something completely different?

![Kapture 2022-09-18 at 12 59 09](https://user-images.githubusercontent.com/2011351/190900982-d1ef8be6-1356-40e7-9138-7186b4af862d.gif)

**Comment by iamcco** [comment]
Same issue.

**Comment by alextes** [comment]
@chemzqm you're the best 🔥 .

I recently switched to full lua config, set everything up from zero, lua only plugins, native language server client + nvim-cmp + null-ls, all the goodies... but after using it a few days, concluded there is still too much missing compared to coc.nvim, also for Rust, so I came back 😄 .

Hats off to you and all other contributors 🙇 .
