### ISSUE TITLE
Javascript linting doesn't catch undefined variables

### ISSUE THREAD

**Issue by t-mdo** [neoclide/coc-tsserver#404]
Hey there,

I've been using coc.nvim for a while with coc-tsserver, and I've just noticed that nvim was not underlining as error variables that were used but not defined in scope.

Eg: I'm calling a function I haven't imported yet, no errors in vim.

I've edited a simple javascript file to see if that was my react setup, but I can reproduce it with a simple javascript one-liner:

`console.log(undefined_variable)` yields no error.

The linting seems to be working fine to spot other types of errors. Any ideas where this could come from?

EDIT:
Here's my CocConfig:
```
{
  "coc.preferences.formatOnSaveFiletypes": ["html", "css", "ruby", "javascript"],
  "suggest.enablePreselect": false,
  "suggest.noselect": true
}
```

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc-tsserver#troubleshooting

**Comment by chemzqm** [comment]
It's expected, tsserver doesn't check javascript by default.
