### ISSUE TITLE
import with short path using package.json

### ISSUE THREAD

**Issue by sandrodz** [neoclide/coc-tsserver#406]
When using component that is not imported in current doc, tsserver automatically adds import at the top of the file.
File path is like this:

`import AppLayout from './layouts/App/App.layout'`

But in the component directory there is a file with ./layouts/App/packages.json, it contains:
```
{
  "main": "App.layout.tsx"
}
```

Which means that filename is redundant and import statement can be:

`import AppLayout from './layouts/App`

How do I force coc-tsserver use this pattern instead?

**Comment by chemzqm** [comment]
Configuration `typescript.preferences.importModuleSpecifier` might help

**Comment by sandrodz** [comment]
@chemzqm none of these seem to work, I tried:

```
typescript.preferences.importModuleSpecifier: Preferred path style for auto imports. default: "shortest" Valid options: ["shortest","relative","non-relative","project-relative"]
typescript.preferences.importModuleSpecifierEnding: Preferred path ending for auto imports. default: "auto" Valid options: ["auto","minimal","index","js"]
```

Docs also mention `typescript.preferences.includePackageJsonAutoImports: default: "auto" Valid options: ["auto","on","off"]` but this doesn't seem to be released feature yet. LS complains when I put this config.

**Comment by chemzqm** [comment]
Seems you're not using latest coc-tsserver.

**Comment by sandrodz** [comment]
@chemzqm 2.0.2
<img width="947" alt="Screenshot 2022-11-19 at 17 24 01" src="https://user-images.githubusercontent.com/8479569/202861071-34e2aefa-0c30-4f28-99a0-3264c9c770e6.png">

I am not sure what that error means.

**Comment by chemzqm** [comment]
`:h coc-configuration-scope`

**Comment by sandrodz** [comment]
> It means it may not work as folder configuration in your project `:h coc-configuration-scope`

but is it the right setting for my issue?

**Comment by chemzqm** [comment]
Seems not, you need to send feature request to typescript project.
