### ISSUE TITLE
Using .tpl file as .js

### ISSUE THREAD

**Issue by curkan** [neoclide/coc-tsserver#408]
Hi how do I get coc-tsserver to parse the tpl file like a js file so it can use jumpDefinition etc?
now throws an error:
`Error on notification jumpDefinition Error: definition provider not found for current buffer, your language server doesn't support it.`

**Comment by chemzqm** [comment]
You need configure correct filetype, see `:h filetype-detect`

**Comment by curkan** [comment]
> configure correct filetype

It didn't get any easier to be honest :D

**Comment by curkan** [comment]
> You need configure correct filetype, see `:h filetype-detect`

Maybe some settings need to be registered in nvim?

**Comment by curkan** [comment]
> You need to make sure the buffer have correct filetype.
did like this:
**autocmd BufNewFile,BufRead *.tpl setlocal filetype=javascript**

but in the tpl file there can be both html and javascript, what is the best way to do it so that both work?
![image](https://user-images.githubusercontent.com/1681501/203744851-c939a317-d9de-4a44-9e9a-b0113007188b.png)
