### ISSUE TITLE
Ignoring tsconfig "types": ["node"]

### ISSUE THREAD

**Issue by myarcana** [neoclide/coc-tsserver#416]
My `tsconfig.json` specifies `"types": ["node"]`, but nvm thinks that the first line of the sibling ts file `import * as path from 'path';` has a

> Cannot find module 'path' or its corresponding type declarations. (tsserver 2307)

error. `ts-node that-file.ts` runs perfectly fine, it's only inside of nvim that I see this "error"

**Comment by chemzqm** [comment]
You may need `"moduleResolution": "node"` in your `tsconfig.json`
