### ISSUE TITLE
tsserver-javascript timeout

### ISSUE THREAD

**Issue by YUFENGWANG** [neoclide/coc-tsserver#42]
When editing with `*.js` files, vim becomes pretty slow, and it warns `source tsserver-javascript timeout after 2000ms`, but when editing `*.ts` files, everything seems ok.

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc-tsserver#trouble-shooting

**Comment by YUFENGWANG** [comment]
bug of this js syntax highlight plugin  `Plugin 'othree/yajs.vim'`
