### ISSUE TITLE
[feature request]Add linkedEditing LSP feature

### ISSUE THREAD

**Issue by qiqiboy** [neoclide/coc-tsserver#423]
Typescript already [supports linkedEditing](https://github.com/microsoft/TypeScript/pull/53284)(not yet released, but available in v5.1.0-dev.20230409).

**Comment by fannheyward** [comment]
This is the server side support, right? coc.nvim already has linkedEditing support, you can enable it by setting `coc.preferences.enableLinkedEditing` to `true`.

**Comment by qiqiboy** [comment]
I tried it, but didn't work. The `coc-html` works fine. I searched 'linkedediting' in `coc-html`, and [found some relevant  codes](https://github.com/search?q=repo%3Aneoclide%2Fcoc-html%20linkedediting&type=code). So I think there should be some adaptation work to be done.

**Comment by fannheyward** [comment]
Got your point, but that PR is for TypeScript, coc-tsserver is something like https://github.com/microsoft/vscode/tree/main/extensions/typescript-language-features and , let's see how VSCode handle this in typescript-language-features.

**Comment by qiqiboy** [comment]
From [vscode's April iteration plan](https://github.com/microsoft/vscode/issues/178951), this feature will be released in early May. The maintainers of vscode are already working on it: https://github.com/mjbvz/vscode/commit/5babe30cb80fc6754614200017ea26d5fa0f2db7.
