### ISSUE TITLE
No Action Available when executing 'doQuickfix'

### ISSUE THREAD

**Issue by Aerex** [neoclide/coc-tsserver#43]
The file in question is a javascript file but the filetype is set to javascript.jsx. The diagnostics do appear in the command line but when I run `CocActionAsyn('doQuickfix')` via `<Plug>(coc-fix-current)` I get **No action available* in the commandline. The dianostic in question are identation errors which I can fix using ALE but I was under the impression that I could use code actions to fix it like I would in VSCode. Below are the logs that I retrieved from both *tsserver* and the *LSP*

LSP log (*abbreviated for brevity*)
```
[Trace  - 8:16:59 PM] Response received: getSupportedCodeFixes (14). Request took 4 ms. Success: true 
Result: [
    "2352",
    "1329",
    "7051",
    "80004",
    "7034",
    ....
]
```

Tsserver (*abbreviated for brevity*)
```
Perf 486  [20:44:15.655] 14::getSupportedCodeFixes: elapsed time (in milliseconds) 0.2613
Info 487  [20:44:15.655] response:
    {"seq":0,"type":"response","command":"getSupportedCodeFixes","request_seq":14,"success":true,"body":["2352","1329","7051","80004","7034","7005","7006","7019","7033","7010","7032","7008","7046","7043","7044","7047","7048","7050","7049","7045","80002","80006","80001","...}
```

Perhaps the listed actions above do no fix indentations?

**Comment by chemzqm** [comment]
Please provide code and configuration to reproduce the problem.

**Comment by chemzqm** [comment]
Check if the diagnostic code inside the result code, I think not, so it's expected.
