### ISSUE TITLE
Feature Request: Go to source definition

### ISSUE THREAD

**Issue by minhchu** [neoclide/coc-tsserver#437]
Not sure to put this issue in this repo or in coc.nvim :sweat_smile: 

It’s similar to Go To Definition, but it never returns results inside declaration files. Instead, it tries to find corresponding implementation files (like .js or .ts files), and find definitions there — even if those files are normally shadowed by .d.ts files.

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html#go-to-source-definition

**Comment by fannheyward** [comment]
https://github.com/neoclide/coc-tsserver/issues/383

**Comment by minhchu** [comment]
Thanks !
