### ISSUE TITLE
Is it necessary to force using the coc core 0.0.82?

### ISSUE THREAD

**Issue by Konata9** [neoclide/coc-tsserver#438]
I am using the iSH (an alpine Linux v3.14) on iPad. 
I tried to run `npm ci` on the latest coc.nvim (v0.0.82) but got the error. `node v16.20.1` with `npm=6.14.18`.
So, I changed the coc.nvim to version v0.0.81. Then I got error on installing coc-tsserver, the error message shows needs the coc core v0.0.82.

So, is it necessary to force using the coc-core 0.0.82?
If not, how can I install in the lower version?

**Comment by fannheyward** [comment]
> npm ci on the latest coc.nvim

Do you use the latest master branch or the 0.0.82 tag release?

**Comment by Konata9** [comment]
Yes. I'm using the latest master branch.

`Plug 'neoclide/coc.nvim', {'branch': 'master', 'do': 'npm ci'}`

**Comment by fannheyward** [comment]
Can you post the error message? coc.nvim's master changed to use `npm` in last week, I need some feedback for this.

**Comment by Konata9** [comment]
OK. I cloned the latest repo from the GitHub page, then went to the folder and ran `npm ci`.
Here are the logs.
```shell
13:23:23 with maochichen in coc.nvim at MacBook-Pro-2 on  master is 📦 v0.0.82 via ⬢ v16.20.1
➜ node -v
v16.20.1

13:23:25 with maochichen in coc.nvim at MacBook-Pro-2 on  master is 📦 v0.0.82 via ⬢ v16.20.1
➜ npm --version
6.14.18

13:23:30 with maochichen in coc.nvim at MacBook-Pro-2 on  master is 📦 v0.0.82 via ⬢ v16.20.1
➜ npm ci
npm ERR! Cannot read properties of undefined (reading '@chemzqm/neovim')

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/maochichen/.npm/_logs/2023-09-04T05_23_32_958Z-debug.log
```

**Comment by yaegassy** [comment]
@Konata9 It seems that the issue is occurring with the version of npm you are currently using. As a workaround, please try upgrading to the latest npm version that is available for Node 16 and see if that resolves the issue. 

**e.g.**:

```
npm i -g npm@8.19.4
```

**Comment by yaegassy** [comment]
Hmm... it appears that this issue is likely related to the `lockfileVersion` of `package-lock-json` on the coc.nvim itself.

- <https://docs.npmjs.com/cli/v9/configuring-npm/package-lock-json#lockfileversion>

**Comment by Konata9** [comment]
@yaegassy You mean the `package-lock.json` is too high in the `coc.nvim`?
I saw the `lockfileVersion` is `3`, which means I need to use the npm9 to do the installation ?

**Comment by yaegassy** [comment]
@Konata9 

> `3`: The lockfile version used by npm v9. Backwards compatible to npm v7.

I think npm v7 or later is fine.

**Comment by fannheyward** [comment]
https://nodejs.org/en/download/releases

Upgrade your npm please.

**Comment by Konata9** [comment]
@yaegassy @yaegassy Thanks guys.
I tried on my iPad with `npm 9`, and the dependencies have downloaded successfully but are stuck in the `npm run build` process. 

I guess it may related to the platform, iSH is a 32-bit Linux system but everything works fine on my Mac.
I will use the older v0.0.81 on my iPad.

Thanks for your help again.

**Comment by chemzqm** [comment]
Use release branch of coc.nvim is recommended.
