### ISSUE TITLE
Progress notification

### ISSUE THREAD

**Issue by YHYJ** [neoclide/coc-tsserver#439]
Set `notification.statusLineProgress = false`, "Initializing tsserver" shows in the status line, but "Initializing pyright" shows in the float window.

![Screenshot_20230908_110641](https://github.com/neoclide/coc-tsserver/assets/21995281/caaf17c3-b8fb-4892-b386-876e3d208b83)

**Comment by chemzqm** [comment]
It's not using progress notification.
