### ISSUE TITLE
Autofill object members feature request

### ISSUE THREAD

**Issue by preslavmihaylov** [neoclide/coc-tsserver#443]
There's apparently a feature in tsserver which allows one to auto-fill missing members in an object, given that you know what type you're looking for.

a good way to understand what the feature looks like is [this comment](https://github.com/microsoft/TypeScript/issues/28491#issuecomment-704092929).

Is these support for something similar in coc-tsserver or are there plans to implement it?

**Comment by fannheyward** [comment]
It's already supported, fire codeAction on `data`

<img width="434" alt="image" src="https://github.com/neoclide/coc-tsserver/assets/345274/f0e040fc-d4db-4a9a-82d2-e185d84fe197">

**Comment by preslavmihaylov** [comment]
ahh thank you, wasn't aware of code actions!

For completeness, the way I triggered this window is by adding this mapping:
```
xmap <leader>a  <Plug>(coc-codeaction-selected)
```

and after selecting the line I'm interested in, it does suggest adding the missing properties.
