### ISSUE TITLE
Is there any way to get non-truncated messages from tsserver?

### ISSUE THREAD

**Issue by nullromo** [neoclide/coc-tsserver#444]
## Problem

When I use the `show_docs` feature, sometimes tsserver will truncate the results

## Config

<details>

<summary>config</summary>

I got this from the CoC README.

```lua
function _G.show_docs()
    local cw = vim.fn.expand('function')
    if vim.fn.index({'vim', 'help'}, vim.bo.filetype) >= 0 then
        vim.api.nvim_command('h ' .. cw)
    elseif vim.api.nvim_eval('coc#rpc#ready()') then
        vim.fn.CocActionAsync('doHover')
    else
        vim.api.nvim_command('!' .. vim.o.keywordprg .. ' ' .. cw)
    end
end
vim.keymap.set('n', 'K', '<CMD>lua _G.show_docs()<CR>', {silent = true})
```

</details>

## Examples

Here are some examples:

![image](https://github.com/neoclide/coc-tsserver/assets/8991581/58eabef3-1f5b-4695-b862-c2474f6f7c04)

As you can see, the window says `... 5 more ...` but I don't have a way of seeing what those 5 more are.

![image](https://github.com/neoclide/coc-tsserver/assets/8991581/2cf6db76-4a20-4f38-853f-9677fa70b80e)

In this one, you can see that some of the types are listed as `{ ... }`, which doesn't really tell me anything.

## Desired Outcome

I just need to be able to see the type of a variable without truncation (or at least with a longer truncation limit). Maybe there's an option I can pass to coc-tsserver or to tsserver itself for this. Or maybe there's another command I can run that will give me the full information instead of the truncated version.

**Comment by fannheyward** [comment]
I don't think coc-tsserver truncate the messages, can you test VSCode with your codes? Properly this's tsserver's behavior.

**Comment by nullromo** [comment]
I installed VSCode to test it out and it looks the same.

Now I see what you mean—tsserver is actually separate from coc-tsserver and this isn't really the right place for the bug report.

Based on what I've been reading online recently, I don't think tsserver is even capable of displaying full error messages...

Thanks anyway though.
