### ISSUE TITLE
typescript.preferGoToSourceDefinition

### ISSUE THREAD

**Issue by preslavmihaylov** [neoclide/coc-tsserver#449]
Is there a setting in coc-tsserver which acts the same way vscode's `typescript.preferTGoToSourceDefinition` does?

Without this, working in a monorepo which relies on typechecking via declaration files vs implementation breaks the functionality for going into a func implementation
https://twitter.com/kamilogorek/status/1735947897986769136

**Comment by fannheyward** [comment]
coc-tsserver already supports `tsserver.goToSourceDefinition` command https://github.com/neoclide/coc-tsserver/pull/384.

You can add custom mapping for ts file only:

```viml
autocmd FileType typescript nnoremap <buffer><silent> gd :CocCommand tsserver.goToSourceDefinition<CR>
```

**Comment by fannheyward** [comment]
This feature has been released in `coc-tsserver-dev`, try `:CocUninstall coc-tsserver` and `:CocInstall coc-tsserver-dev`.

Note: coc-tsserver-dev is only used for unmerged PRs, and after PR merged into coc-tsserver, you should use coc-tsserver instead.

**Comment by preslavmihaylov** [comment]
Nice, thank you!

**Comment by fabOnReact** [comment]
go to the definition does not work with libraries like React.js 

https://github.com/microsoft/TypeScript/issues/37777#issuecomment-2259714084

https://github.com/user-attachments/assets/35636636-31aa-4ad3-88ab-187176e12b4b


for example, I can not navigate the source code implementation of useRef. It is minified.
https://github.com/neoclide/coc-tsserver/pull/384
