### ISSUE TITLE
Conflict with flow lsp

### ISSUE THREAD

**Issue by amiralies** [neoclide/coc-tsserver#45]
I Work on different js codebases written vanilla js, flow js and some times typescript.
what is the preferred way to manage conflict between flow lsp and coc-tsserver maybe.
maybe disable coc-tsserver when there is `.flowconfig` available in workspace root?

**Comment by chemzqm** [comment]
Use `mkdir .vim && echo '{  "tsserver.enableJavascript": false}' > .vim/coc-settings.json` in your flow project root.
