### ISSUE TITLE
Support for "typescript.unstable" configuration

### ISSUE THREAD

**Issue by AlexEmerson** [neoclide/coc-tsserver#453]
First of all, thanks for the extension, love it.

Currently specifying any option from the [typescript.unstable](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#case-insensitive-import-sorting-in-editors) section in `settings.json` doesn't seem to take any effect.

Is that going to be supported?

**Comment by fannheyward** [comment]
This feature has been released in `coc-tsserver-dev`, try `:CocUninstall coc-tsserver` and `:CocInstall coc-tsserver-dev`.

Note: coc-tsserver-dev is only used for unmerged PRs, and after PR merged into coc-tsserver, you should use coc-tsserver instead.

**Comment by AlexEmerson** [comment]
Thanks. Already added line from the PR to coc-tsserver index.js file locally till PR is merged. Works fine.
