### ISSUE TITLE
Add a LICENSE file to the repo

### ISSUE THREAD

**Issue by christopher-francisco** [neoclide/coc-tsserver#457]
After a merger, the vim guild in my company find ourselves in need to procure many different open source projects in order to use them. The process require use to submit a link to a license file.

I appreciate many of the `neoclide/coc-*` projects declares it's licensed as MIT in the README or package.json. Unfortunately we need to provide a link to a license file with the license contents so it's reviewed by legal. Without this, we won't be able to use the tools. I humbly request your support.

I have taken the liberty of opening #454 to address this.

I hope you consider this. Thanks in advance!

**Comment by chemzqm** [comment]
#454
