### ISSUE TITLE
Import code action always provides paths relative to baseUrl

### ISSUE THREAD

**Issue by hallettj** [neoclide/coc-tsserver#46]
This is a minimal reproduction of the problem: [baseurl-issue.tar.gz](https://github.com/neoclide/coc-tsserver/files/3315894/baseurl-issue.tar.gz)

## Steps to Reproduce

Set some value for `baseUrl` in TypeScript's compiler options:

```json
{
  "compilerOptions": {
    "baseUrl": "node_modules"
  }
}
```

Create two files, one of which refers to a symbol that is exported by the other but where the relevant `import` line is missing:

```ts
// src/a.ts
export const a = 1
```

```ts
// src/b.ts
export const b = a
```

Place the cursor on the symbol `a` in `src/b.ts` and bring up code actions (e.g. with a key bound to `<plug>(coc-codeactions)`).

## Expected Results 

The code action to import `a` should provide an import path that is relative to `src/b.ts`:

```
Import 'a' from module "./a"
```

I checked the quickfix options in VS Code in the same minimal project, and saw the result that I expected.

## Actual Results

The code action to import `a` provides an import path that is relative to `baseUrl`. In this case the path is `"../src/a"` instead of `"./a"`. These are the options that I see provided by coc-tsserver:

```
:call CocActionAsync('codeAction',     '')
Choose by number:
1. Import 'a' from module "../src/a"
2. Add import
3. Convert named export to default export
4. Move to a new file
Type number and <Enter> or click with mouse (empty cancels):
```

I noticed that there is a similar issue that has been address in the TypeScript project: https://github.com/Microsoft/TypeScript/issues/19920

**Comment by chemzqm** [comment]
It's problem of tsserver, coc-tsserver use your local tsserver when possible.

**Comment by hallettj** [comment]
Ok, thanks for the response!
