### ISSUE TITLE
Formatting based on project's eslint/biome

### ISSUE THREAD

**Issue by qauff** [neoclide/coc-tsserver#460]
Maybe I've my coc-tsserver setup incorrectly, but it seems like when I run `:Format`, the formatting used doesn't respect my projects eslint or biome. Is there a way to specify or a priority list of what formatter to use?

**Comment by fannheyward** [comment]
coc-server doesn't run biome to do formatting. Try coc-biome.

**Comment by qauff** [comment]
I want to keep using `:Format` so that it's project specific. Does `typescript.format.enable` disable just `coc-tsserver` from being a formatter (defaulting to others that are enabled)? Or does it disable `typescript` and related filetypes from being affected by `:Format` altogether?

**Comment by qauff** [comment]
Ah. I see the issue now. It's not coc-tsserver. My bad. coc-prettier only supports an outdated prettier version, and doesn't like `prettier.config.mjs`.  Sorry for false alarm!

https://github.com/neoclide/coc-prettier/pull/172
