### ISSUE TITLE
VIM automatically goes into select mode and selects all contents before the cursor

### ISSUE THREAD

**Issue by ayonli** [neoclide/coc-tsserver#465]
When using this plugin, and for example, typing the following code:

```ts
import { EventEmitter } from "events";

const events = new EventEmitter();

event.on
```

When I press `Enter` key, the editor automatically goes into **Select** mode, and select all contents before the `console.on(eventName`, which is very annoying, because if I type any key at this moment, the contents selected will be wiped out.

**Comment by fannheyward** [comment]
What's your `:CocInfo`?

Similar issue https://github.com/neoclide/coc.nvim/issues/4599, upgrade your vim and try again.

**Comment by ayonli** [comment]
OK, I just installed Neovim, and it works well.
