### ISSUE TITLE
Could not install with vim-plug

### ISSUE THREAD

**Issue by thesergiomiguel** [neoclide/coc-tsserver#48]
It has worked so far, but this morning I ran `PlugUpdate` and coc-tsserver stopped working. None of the exposed commands were available either. I tried removing it, `PlugClean`, adding it again, and nothing worked. Only after installing with `CocInstall` did it start working again.

What kind of logs could I provide to make it easier to debug this situation?

**Comment by chemzqm** [comment]
Try `npm install -g webpack webpack-cli`

**Comment by thesergiomiguel** [comment]
I'm not sure that should be a requirement, but if so it should be listed somewhere no? All the other coc extensions I'm using installed fine through vim-plug, btw.

**Comment by chemzqm** [comment]
npx command should install them for you, so it looks like network issue

**Comment by JackCA** [comment]
I just ran into this as well and running `PlugUpdate`  after `npm install -g webpack webpack-cli` worked but I don't think it's limited to a network issue.

I know the `prepare` npm command should run after the `install` in `Plug 'neoclide/coc-tsserver', {'do': 'yarn install --frozen-lockfile'}` but I'm not sure what's happening because I didn't see the same webpack logs appear prior to the global install

**Comment by mhintz** [comment]
Had the same issue happen to me - I had removed my global webpack installation, then later ran PlugUpdate, then coc-tsserver stopped working. Re-installing webpack globally seems to have done the trick.

But it seems like maybe this issue could be solved by adding webpack to the devDependencies for this package?

**Comment by chemzqm** [comment]
It uses `npx` which should install webpack when not found.

**Comment by pearofducks** [comment]
I just bumped into this - directions somewhere (maybe [here](Either this shouldn't be closed, or the directions [here](https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions#use-vims-plugin-manager-for-coc-extension)) should be updated so this information isn't buried in a closed issue.

I agree with the above comment though, it seems a bit odd to require a global install of webpack for this plugin, when all other plugins install fine.
