### ISSUE TITLE
[Feature Request] Completion Locality Bonus

### ISSUE THREAD

**Issue by bogdan0083** [neoclide/coc-tsserver#5]
Here's the link for this cool feature: [Locality Bonus](https://code.visualstudio.com/docs/editor/intellisense#_locality-bonus). I don't think it is high priority issue, but it would be cool if this would be implemented in `coc-tsserver`! 

Thank you! ❤️

**Comment by chemzqm** [comment]
It's implemented https://github.com/neoclide/coc.nvim/commit/447d1c4ee322e6bf1c7d6bc1610f621b80adb11b
