### ISSUE TITLE
How do I... 

### ISSUE THREAD

**Issue by faurehu** [neoclide/coc-tsserver#56]
Sorry if this has been asked before.

I'm trying to simulate the vscode experience in nvim and there are fundamentally two features I miss:

- Smarter autocompletion: the sorting of my current autocomplete suggestions is alphabetical. The one in vscode is by recent use. Is it possible to enable this?
- Populate symbols: when I currently go into `:CocList` > `symbols`, it is empty. This extension claims to offer the possibility to find symbols at least in the buffer. Vscode's Go To Symbol is very powerful, can I emulate this?

Thanks.

**Comment by chemzqm** [comment]
It is sorted like vscode.
Type characters to search symbols,you have to use interactive mode

**Comment by faurehu** [comment]
I'm trying the following command: 
`:CocList --interactive symbols` 
and I receive:
`[coc.nvim] Error on "CocList symbols": Workspace symbols provider not found for current document`

I have tried `:CocList symbols --interactive` but it says the list only works in interactive mode.

**Comment by chemzqm** [comment]
> but it says the list only works in interactive mode.

It's documented.

> Workspace symbols provider not found for current document

You have to use it within document handled by tsserver.

**Comment by faurehu** [comment]
How can I tell a file is being handled by tsserver? I am running the command on a typescript file.

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by faurehu** [comment]
Hey thanks, the symbols filter suddenly started working and it's quite nice. Is there a way to start the preview right away? That'd be neat.

I'm also trying to make `outline` list command work but it just stays there empty. The server shows a successful response but the list is empty. Any clues?

**Comment by aigo-tech** [comment]
any solution for this error?

**Comment by chemzqm** [comment]
@aigo-tech configure  language server that support workspace symbols for your buffer.
