### ISSUE TITLE
How can i setup typescript-lit-html-plugin with coc-tsserver?

### ISSUE THREAD

**Issue by dementor5** [neoclide/coc-tsserver#59]
I mean make global install, like coc-tsserver plugin - without install it to project devDependencies and creating tsconfig.json in project root

**Comment by chemzqm** [comment]
Don't know

**Comment by chemzqm** [comment]
It has nothing to do with this plugin, please be specific of your problem

**Comment by dementor5** [comment]
My current project is written on lit-element (includes lit-html).
typescript-lit-html-plugin extends tsserver for support lit-html syntax and code autocompletion.
Need add it as plugin in tsconfig.json: https://github.com/microsoft/typescript-lit-html-plugin

How can i install it in coc-tesserver and how extends buildin config?

**Comment by chemzqm** [comment]
You have to use devDeoendencies and tsconfig.json unless someone can create a coc extension for it.

**Comment by fannheyward** [comment]
@dementor5 I make an extension https://github.com/fannheyward/coc-lit-html , provides lit-html support with typescript-lit-html-plugin. Give it a try and feedback is welcome.
