### ISSUE TITLE
suppress missing declaration errors

### ISSUE THREAD

**Issue by burgessa23** [neoclide/coc-tsserver#6]
Hi, I'm using the tsserver for javascript only (no typescript files) is there a way to keep the functionality for js, but not get the missing declaration errors for imported modules?

example of what I mean: the module listed has no ts types
```sh
[tsserver 7016] [I] Could not find a declaration file for module '@ux/radio-group'. '/Documents/Projects/top-navigation/n
  Try `npm install @types/ux__radio-group` if it exists or add a new declaration (.d.ts) file containing `declare module '@ux/radio-group
```

thanks!

**Comment by chemzqm** [comment]
Change `javascript.suggest.enabled` to `false` in your coc-settings.json.
But it's not recommended, since tsserver would not work well without type information,

**Comment by christopher-allene-piximedia** [comment]
While setting `javascript.suggest.enabled` work as advertised, I am puzzled by that fact that setting the following in the jsconfig.json file seems not to have any effect:

```
        "compilerOptions": {
                "suppressImplicitAnyIndexErrors": true,
                "noImplicitAny": true
        }
```

Any idea why the latter did not work?

**Comment by chemzqm** [comment]
Don't know, I think you need ask at https://github.com/microsoft/TypeScript

**Comment by SalTor** [comment]
> Change `javascript.suggest.enabled` to `false` in your coc-settings.json.
> But it's not recommended, since tsserver would not work well without type information,

Wouldn't `javascript.suggest.enabled` be a better candidate for this?

**Comment by chemzqm** [comment]
Should be `javascript.suggestionActions.enabled` and `typescript.suggestionActions.enabled`
