### ISSUE TITLE
Trouble installing plugin after 1.3.15 release

### ISSUE THREAD

**Issue by asermax** [neoclide/coc-tsserver#60]
After the latest release, I'm having issues installing the plugin. Aparently, since [the removal of webpack from the dependencies](https://github.com/neoclide/coc-tsserver/commit/f8ed02524da46c71e5c3b79e0707cbc6d66666f5), the build command isn't run to completion, at least when installing the plugin through `vim-plug`.

Trying to run `yarn install --frozen-lockfile` directly on the plugin's folder leads to a loop, where after package installation the `prepare` hook tries to run `npx webpack`, which in turn prompts to install `webpack-cli`, kicking the loop again:

```
$ yarn install --frozen-lockfile                                                                                                                    
yarn install v1.17.3
[1/5] Validating package.json...
warning coc-tsserver@1.3.15: The engine "coc" appears to be invalid.
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
$ npx npm-run-all clean build
[#####################################################################] 221/221[.....
npx: installed 58 in 6.573s
yarn run v1.17.3
warning coc-tsserver@1.3.15: The engine "coc" appears to be invalid.
$ rimraf lib
Done in 0.11s.
yarn run v1.17.3
warning coc-tsserver@1.3.15: The engine "coc" appears to be invalid.
$ npx webpack
npx: installed 322 in 14.204s
One CLI for webpack must be installed. These are recommended choices, delivered as separate packages:
 - webpack-cli (https://github.com/webpack/webpack-cli)
   The original webpack full-featured CLI.
We will use "yarn" to install the CLI via "yarn add -D".
Do you want to install 'webpack-cli' (yes/no): yes
Installing 'webpack-cli' (running 'yarn add -D webpack-cli')...
[1/5] Validating package.json...
warning coc-tsserver@1.3.15: The engine "coc" appears to be invalid.
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning " > webpack-cli@3.3.6" has unmet peer dependency "webpack@4.x.x".
[5/5] Building fresh packages...
[...snip...]
$ npx npm-run-all clean build
warning coc-tsserver@1.3.15: The engine "coc" appears to be invalid.
$ rimraf lib
warning coc-tsserver@1.3.15: The engine "coc" appears to be invalid.
$ npx webpack
One CLI for webpack must be installed. These are recommended choices, delivered as separate packages:
 - webpack-cli (https://github.com/webpack/webpack-cli)
   The original webpack full-featured CLI.
We will use "yarn" to install the CLI via "yarn add -D".
Do you want to install 'webpack-cli' (yes/no): 
```

So far the only workaround I've found was rolling back the webpack dependencies removal change.

**Comment by pirey** [comment]
can you share with us how do you exactly 'roll back' the webpack dependencies removal change?

**Comment by asermax** [comment]
Hey @pirey, this shouldn't be an issue anymore, @chemzqm added back the webpack dependencies in the latests versions so the build shouldn't have any problems in that respect. I've been able to build the plugin after the dependencies issue was addressed, at least.
If you're having an issue with the last version of the plugin, you should probably create a new issue with a more detailed report of what exactly is going on for you.
