### ISSUE TITLE
How do I rename file

### ISSUE THREAD

**Issue by kanmii** [neoclide/coc-tsserver#61]
Thanks @chemzqm for this wonderful project. Please how do I rename a file so that imports are renamed?

Apologies in case this has been documented somewhere but I can't seem to find it.

Thanks.

**Comment by chemzqm** [comment]
It doesn't care how you rename the file, install https://facebook.github.io/watchman/ to detect the rename.
Use `:CocCommand workspace.renameCurrentFile` for rename current buffer is recommended.

**Comment by pablopunk** [comment]
Hi @chemzqm, I have `watchman` installed and I don't seem to be getting this feature to work. In this screenshot, I'd expect the file on the right to be updated with the new path (I also tested it without having the file on a buffer):

![Kapture 2020-04-14 at 17 15 27](https://user-images.githubusercontent.com/4324982/79241630-9424cd00-7e73-11ea-8f91-d10d52ee8215.gif)

**Comment by chemzqm** [comment]
Checkout output from watchman.

**Comment by chemzqm** [comment]
Duplicated of #52
