### ISSUE TITLE
insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis not being followed by tsserver

### ISSUE THREAD

**Issue by harisb2012** [neoclide/coc-tsserver#62]
I have "typescript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis" set to true in my CocConfig. However, autoimport is still importing modules like:

import {connect} from 'react-redux';

Is there a way to force it to add spaces there. It is annoying.

**Comment by anark** [comment]
You need to use braces/brackets instead of parentheses 

typescript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces
