### ISSUE TITLE
Upgrade typescript version to 3.6.2?

### ISSUE THREAD

**Issue by brainkim** [neoclide/coc-tsserver#67]
I’m trying to use typescript 3.6.2 but coc is reporting errors from 3.5.3. Dunno if there is a way for `coc-tsserver` to use the local typescript, but that would be nice.

`CocInfo` output:
```

## versions

vim version: NVIM v0.3.8
node version: v10.16.0
coc.nvim version: 0.0.73-bacaaa8ef2
term: Apple_Terminal
platform: darwin

## Messages

## Output channel: watchman
[Info  - 3:51:47 PM] watchman watching project: /Users/brian/Projects/repeater/packages/repeater
[Info  - 3:51:47 PM] subscribing "**/[tj]sconfig.json" in /Users/brian/Projects/repeater/packages/repeater
[Info  - 3:51:47 PM] subscribing "**/package.json" in /Users/brian/Projects/repeater/packages/repeater
[Info  - 3:51:48 PM] subscribing "**/*.{ts,tsx}" in /Users/brian/Projects/repeater/packages/repeater
[Info  - 3:51:48 PM] subscribing "**/*.{js,jsx}" in /Users/brian/Projects/repeater/packages/repeater


## Output channel: tsserver
[Info  - 3:51:47 PM] Forking TSServer
PATH: /Users/brian/.volta/tools/image/node/10.16.0/6.9.0/bin:/Users/brian/.volta/tools/image/yarn/1.17.3/bin:/Users/brian/Library/Python/2.7/bin:/Users/brian/.cargo/bin:./node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/brian/Library/Python/2.7/bin:/Users/brian/.cargo/bin:./node_modules/.bin:/usr/local/sbin 
[Info  - 3:51:47 PM] Started TSServer
{
  "path": "/Users/brian/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib",
  "_pathLabel": "",
  "_api": {
    "versionString": "3.5.1",
    "version": "3.5.1"
  }
}
```

**Comment by brainkim** [comment]
Somehow got coc-tsserver to use 3.6.2. 🤷‍♀️

**Comment by brainkim** [comment]
So the problem was that `Coc` wasn’t finding my local typescript in a yarn workspaces monorepo project. Normally I don’t notice this, but 3.6.2 has some changes which were treated as errors in 3.5.1. I fixed the problem permanently by setting `"tsserver.tsdk"` manually in my `coc-settings.json` to my global typescript installation (`{"tsserver.tsdk": "/Users/brian/.config/yarn/global/node_modules/typescript/lib"}`).

Hope this helps future people.

**Comment by chemzqm** [comment]
The problem is how to detect monorepo ?

**Comment by brainkim** [comment]
> The problem is how to detect monorepo

Yes I think coc-tsserver doesn’t correctly detect tsserver’s in a yarn workspace directory structure.

**Comment by chemzqm** [comment]
Bundled tsserver is used when local tsserver can't be resolved.
