### ISSUE TITLE
Diagnostics view help

### ISSUE THREAD

**Issue by arbitrary-dev** [neoclide/coc-tsserver#69]
Could you please clarify a couple of **Diagnostics view** aspects to me, or point me to a documentation page, as I was unable to locate it quickly:
- How do I scroll the view?
- How can I change the colors used?

The view in question:

<img width="412" alt="Screen Shot 2019-09-05 at 12 17 14 PM" src="https://user-images.githubusercontent.com/6984946/64329053-4095fb00-cfd7-11e9-9d5d-d87a34836331.png">

Thanks, for awesome tools, btw!

**Comment by fannheyward** [comment]
1. `C-w-w` to floatong window，then j/k
2. Your colorscheme isn’t works well with floating window.

**Comment by arbitrary-dev** [comment]
1. `C-w-w` isn't working, `C-p` & `C-n` also
2. Which style does it uses?

**Comment by arbitrary-dev** [comment]
By the way…
```
:version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug 22 2019 04:02:38)
macOS version
Included patches: 1-1900
Compiled by Homebrew
```

**Comment by chemzqm** [comment]
It's not supported on vim8 yet.

**Comment by chrisbra** [comment]
So what is your plugin using for Vim?

**Comment by chemzqm** [comment]
I've tested you can just scroll by use mouse.
Checkout `:h coc-highlights` for highlight groups used by coc.nvim

**Comment by arbitrary-dev** [comment]
Would also be nice to have support for people with disabilities, like me :-)
```
-mouse
```

>There are no key controls by default (because that would take away keys from the main view).  The plugin author can add a filter to allow for scrolling with keys.

Something like `<C-j>` & `<C-k>` would be perfect.
