### ISSUE TITLE
Request ability to disable formatting just for this plugin

### ISSUE THREAD

**Issue by ohjames** [neoclide/coc-tsserver#70]
I'm using `coc-prettier` to do formatting, so I want to keep `coc.preferences.formatOnSaveFiletypes` enabled for typescript. But I don't want `coc-tsserver` to format my file, only for `coc-prettier` to then reformat it a second time. The `coc-tsserver` formatting is totally redundant.

**Comment by chemzqm** [comment]
PR welcome

**Comment by ohjames** [comment]
@chemzqm Good to know, thanks for responding so soon! I'll work on it ASAP.

**Comment by avahe-kellenberger** [comment]
Just wanted to say I'm looking forward to this. Been having some serious issues with tsserver formatting recently (duplicating lines, thus breaking code).

**Comment by chemzqm** [comment]
> (duplicating lines, thus breaking code).

Should be issue of coc.nvim, IMO tsserver is the best tool for javascript/typescript format, it provides all format methods and most complete configuration.

**Comment by ohjames** [comment]
Every team I've worked with for the last 3 years is using `prettier`. IMO it's the best formatter available for TypeScript and JavaScript.

**Comment by avahe-kellenberger** [comment]
@chemzqm it seems to only be happening with an older (es2015) JavaScript codebase, no other languages, so I'm not sure what's actually causing it. Been looking into other solutions than coc-nvim because of this bug I'm running into

**Comment by avahe-kellenberger** [comment]
@ohjames I was able to achieve the functionality you are seeking by removing the file types from coc-settings and adding this to my init.vim

```command! -nargs=0 Prettier :CocCommand prettier.formatFile

autocmd BufWritePre *.js,*.jsx,*.mjs,*.ts,*.tsx,*.css,*.less,*.scss,*.json,*.graphql,*.vue,*.yaml,*.html Prettier
```

This also fixed the bug I was having. Is this working for you?

**Comment by chemzqm** [comment]
Please use `typescript.format.enabled` and `javascript.format.enabled` configuration.
