### ISSUE TITLE
Is it possible to get more information from doHover?

### ISSUE THREAD

**Issue by bag-man** [neoclide/coc-tsserver#71]
If I put my cursor on an interface being used as a return type, and run `doHover` I just get `interface  JobQueue`, nothing more. It would be really helpful if it would actually show me the typing for that interface as well. I guess it is correct in showing the type, and it works well for primitives, but would be cool to see the whole type definition. 

Is this possible? 

Thanks!

**Comment by chemzqm** [comment]
It just shows what from language server, so I think you need ask at https://github.com/microsoft/TypeScript/issues

**Comment by bag-man** [comment]
Thanks, I've been using that too, but it would be nice to have it in the preview! Thanks for the quick response! :D
