### ISSUE TITLE
Function to stop the tsserver (including node process)

### ISSUE THREAD

**Issue by tuxflo** [neoclide/coc-tsserver#72]
Hi!

Sometimes I nearly run out of memory and then I want to disable the tsserver. My expectation was, that the node process that is created by the tsserver is stopped if I run `CocDisable` but this isn't the case. Also it seems that there is nothtingh like `CocCommand tsserver.stop` or `CocCommand tsserver.disable`.

Thanks in advance,
tuxflo

**Comment by chemzqm** [comment]
`:call coc#rpc#stop()`
