### ISSUE TITLE
Resolve module relative to Vim pwd

### ISSUE THREAD

**Issue by uri** [neoclide/coc-tsserver#73]
I have a project that looks like the following

```
monolith_rooth
-->common
  --> file.ts
-->project
    --> src
       --> common -symlink> ../../common
```

When I open `:e src/common/file.ts` Vim resolves it to `~/mypaths/monolith_root/common/file.ts`

It seems that Vim will always resolve symbolic links and I'm assuming module lookup is done relative to the filepath. Would be possible to lookup the module via the current working directory (`:pwd`) via config?

**Comment by chemzqm** [comment]
No, it have to work on real file path, project folder is not parent folder of your file.
