### ISSUE TITLE
`executeAutofix` on save?

### ISSUE THREAD

**Issue by pablopunk** [neoclide/coc-tsserver#75]
Hi, first of all I love coc.nvim, thanks for this awesome project.

I got working the autoimport feature but I don't get the import to show up until I run the command `tsserver.executeAutofix`. Is there any setting to run that on save just like `tslint` and `eslint`?

**Comment by fannheyward** [comment]
I use this: `autocmd BufWritePre *.ts :call CocAction('runCommand', 'tsserver.executeAutofix')`

**Comment by pablopunk** [comment]
@fannheyward thanks for the tip! I figured out I could do something like that but since coc-eslint and coc-tslint both have this config already, I thought this extension should have it too.

**Comment by chemzqm** [comment]
The autofix from tsserver may conflict with other tools while sometimes gives unexpected fix, and uses defined autocmd gives you better control.

The typescript-vscode extension also doesn't have this feature.

**Comment by pablopunk** [comment]
@chemzqm ok that makes sense then, I'll close the issue. Thanks!
