### ISSUE TITLE
Command to reload the current file

### ISSUE THREAD

**Issue by Emigre** [neoclide/coc-tsserver#76]
I would like to reload the TypeScript diagnostics of a file that I am editing.

I see that the plugin has a `tsserver.reloadProjects` command, that triggers [the ReloadProjects command](https://github.com/Microsoft/TypeScript/blob/master/lib/protocol.d.ts#L47) in the TS server protocol. I see that the protocol has a [Reload command](https://github.com/Microsoft/TypeScript/blob/master/lib/protocol.d.ts#L40) too that -I think- would reload the file. I might be wrong. 

Is there a way at the moment to send that `Reload` command to the TS server or to trigger that functionality in another way? If not, could we add a `reload` command to the coc-tsserver commands?

Thanks.

**Comment by fannheyward** [comment]
Try `CocRestqrt`

**Comment by Emigre** [comment]
Thanks @fannheyward. That could be an alternative solution, but it seems too much to restart coc.nvim as a whole just to get diagnostics again for a single file.

**Comment by chemzqm** [comment]
That command doesn't work, use `:edit!` to reload buffer.

**Comment by Emigre** [comment]
That’s a good solution. Thank you!

**Comment by tingham** [comment]
Edit your configuration, either:

:e ~/.vimrc
:e ~/.config/nvim/init.vim

Add:
```
" Reload
map <F5>:edit!<CR>
```

Reload your configuration

:source ~/.config/nvim/init.vim
