### ISSUE TITLE
Warnings for unused parameters even with "typescript.showUnused: false"

### ISSUE THREAD

**Issue by markormesher** [neoclide/coc-tsserver#77]
_First up, thanks for your work on `coc` and related plugins - I'm new to using them but loving them so far! :heart:_

--

I'm using `coc-tsserver` with the following (stripped back) config file:

```json
{
  "diagnostic.displayByAle": true,
  "typescript.showUnused": false
}
```

I confirmed that this is definitely the config file being used via `:CocConfig`.

Despite having `"typescript.showUnused": false` (because I prefer how `eslint` handles it), I'm still seeing a warning for the unused variable here:

![image](https://user-images.githubusercontent.com/6496999/65977898-a5bffd80-e46a-11e9-913a-6c65fca4d67d.png)

I don't have `noUnusedParameters` set in my `tsconfig.json` file (does this plugin look there anyway?), but I tested with it set to `false`, restarted the `coc` server, the `tsserver` process and Neovim itself, but nothing changed.

Am I missing something or is this a bug?

**Comment by chemzqm** [comment]
Please provide your coc-tsserver and tsserver version.

**Comment by markormesher** [comment]
vim version: NVIM v0.4.2
coc.nvim version: 0.0.74-e04013a8bd
coc-tsserver version: 1.4.1
tsserver version: 3.6.3

**Comment by graue** [comment]
Hi, I'm experiencing this issue again... and it looks like reverting #78 and changing that line of code from saying `Information` _back_ to `Hint`, fixes it.
