### ISSUE TITLE
Reporting of false errors in tsx files for html elements

### ISSUE THREAD

**Issue by ManiacalAce** [neoclide/coc-tsserver#8]
I've been stuck on this for quite some time and am now asking for help. I'm not sure if this is a bug.
I'm trying to switch to coc-nvim for completions, but for typescript tsx files, I keep getting complaints for the various html tags... 
`[tsserver 2304] [E] Cannot find name 'div'.`
`[tsserver 2304] [E] Cannot find name 'header'.`
etc etc

Here's a minimal reproduction:
(Based on instructions in https://facebook.github.io/create-react-app/docs/adding-typescript)
`$ npx create-react-app@next painful_ts`
`$ cd painful_ts`
`$ npm install --save typescript @types/node @types/react @types/react-dom @types/jest`
`$ mv src/App.js src/App.tsx`
`$ mv src/index.js src/index.tsx`
`$ npm start`
`$ nvim src/App.tsx`
--> Bajillion error markers about tsserver not being able to understand html tags

If I do 'go to definition' on the `import React...` line, it takes me to the relevant React definitions file. I also see definitions for `div` etc in that file under `interface ReactHTML {...`. But `go to definition` does not work on the `div` or `img` or any other html tags.

So what is going on?

Interestingly, if I go to an old existing react TS project, and i open one of the tsx files, things seem to work okay. 'Go to definition' for the html tags take me to the right definitions file. The tsc version was 2.6.2 in an old project. I updated it to latest 3.2.2, then the errors appeared again on opening files. I downgraded typescript to 2.6.2 again, but I STILL saw the errors there.

Pretty confused. Help would be appreciated. 
Thanks.

**Comment by chemzqm** [comment]
* You should use latest version of typescript for better feature support.
* You should install `@types/node` in your project for tsserver intellisense.
* The filetype of should be `javascript.jsx` or `javascriptreact` for jsx files.
* You may need to create a `jsconfig.json` for tsserver to understand your project https://code.visualstudio.com/docs/languages/jsconfig

**Comment by ManiacalAce** [comment]
@chemzqm To clarify, this is a typescript project. 

1. I am using the latest typescript. It is 3.2.2
2. @types/node has been installed as i mentioned above 
3. Okay, I understand that for JS and JSX files, but my files are TSX files.
4. Do I need to create a `jsconfig.json` for a typescript project? I think my `tsconfig.json` should suffice?

**Comment by chemzqm** [comment]
> but my files are TSX files.

The filetype should be `typescript.tsx` or `typescript.jsx`

**Comment by ManiacalAce** [comment]
Ookay, looks like that seemed to be the issue.

My filetype was `typescript` and I only had the 'leafgarland/typescript-vim' installed.
I found this issue there: https://github.com/leafgarland/typescript-vim/pull/140

It's still open.
So I installed the 'ianks/vim-tsx' plugin and it seems to work okay now.

Thanks!
