### ISSUE TITLE
Auto import not working?

### ISSUE THREAD

**Issue by eyaleizenberg** [neoclide/coc-tsserver#80]
I start typing a variable's name and seeing the `auto import from ...` tooltip. I press `tab` to select  the proper variable and it completes the variable correctly but it's not adding the import to the file. What am I missing?

**Comment by chemzqm** [comment]
You have to confirm completion, read wiki of coc.nvim

**Comment by eyaleizenberg** [comment]
Thanks for the quick answer @chemzqm . Turned out I had a conflict with the super tab package which don't need anymore because of COC.
