### ISSUE TITLE
Format settings not taken into account

### ISSUE THREAD

**Issue by noomly** [neoclide/coc-tsserver#81]
As stated in the title format settings written in coc-settings.json aren't taken into account (apparently). I don't really know if this is a bug or if I just can't figure out how this works.

Anyway, here is my coc-settings:

```json
{
    "coc.preferences.formatOnSaveFiletypes": ["rust", "typescript"],
    "typescript.preferences.quoteStyle": "double",
}
```

When I save my .ts file, it does reformate it. The problem is, having installed the plugin `coc-tslint-plugin`, I get some lints warning on this line for example:

```typescript
image.onload = (_) => {res(image);};
```

The warning being `[tslint 1] [W] missing whitespace (whitespace)` at the second bracket. If a put a space after the first bracket and before the second one, the warning disappear. The problem is that when I save the file it gets reformated and the spaces I around the brackets gets deleted (and the lint warning reappears).

I tried to add the following line to the `coc-settings.json`:

```json
"typescript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets": false
```

But it didn't have any effect, the problem is persisting.

Is this a good behavior and I didn't understand how to make it work the way I want? If yes, how do I fix this formatting problem?

Thanks for your work on this plugin!

**Comment by chemzqm** [comment]
Need log of tsserver to inspect

**Comment by cursorzz** [comment]
I am actually experience the same issue, do you know where can I get that log of tsserver for debug?

**Comment by chemzqm** [comment]
Read readme.
