### ISSUE TITLE
I get function is declared but its value is never read false positives 

### ISSUE THREAD

**Issue by blasco** [neoclide/coc-tsserver#83]
I'm working with Ionic using typescript and angular. I have both coc-tsserver and coc-angular. I'm using the function as a (click) event but in the typescript file I get warnings saying the the value of the function is never read. Is this an error or how should I configure so it properly detects that the function is being read in the associated html files?

**Comment by chemzqm** [comment]
coc-tsserver doesn't have support for html files,check your output.

**Comment by blasco** [comment]
Is there something like /* tslint:disable-next-line */ to suppress the warnings?

**Comment by chemzqm** [comment]
Read doc of tslint, it's off topic
