### ISSUE TITLE
Can't save all files

### ISSUE THREAD

**Issue by blasco** [neoclide/coc-tsserver#84]
When trying to save all files `:wa` I get:

```
E141: No file name for buffer 37
```

From session to session the buffer number changes, and if I check what's in this buffer, it is the message generated for floating windows such as errors or warnings.

It doesn't happen consistently, only time to time, not sure how could I provide more information in order to tackle down the issue.

**Comment by chemzqm** [comment]
You have unnamed buffer with changes, it's your issue.

**Comment by chemzqm** [comment]
It should be nofile filetype which doesn't affect file save, can't reproduce your issue.

**Comment by blasco** [comment]
Well... it is not. Any idea what could be causing it?

**Comment by chemzqm** [comment]
No, you should try minimal vimrc
