### ISSUE TITLE
How can I solve this problem?

### ISSUE THREAD

**Issue by heguohui2018** [neoclide/coc-tsserver#88]
I have searched for a long time and have not solved this problem.

<img width="1115" alt="截屏2019-11-0519 49 11" src="https://user-images.githubusercontent.com/35359288/68205635-c3eac180-0005-11ea-88cd-9e6f01e6564e.png">

<img width="1440" alt="截屏2019-11-0519 51 43" src="https://user-images.githubusercontent.com/35359288/68205662-cfd68380-0005-11ea-8326-a44161f00592.png">

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
or switch to other plugins.
