### ISSUE TITLE
Errors from tsserver on vanilla javascript project configured to use standard styling

### ISSUE THREAD

**Issue by expelledboy** [neoclide/coc-tsserver#89]
I am getting TypeScript specific errors in a vanilla JavaScript file (`.js` extension), is this incorrect detection of the file, or is this bad configuration?

I have simple installed coc and run `:CocInstall coc-tsserver`. Apparently this plugin is used for javascript just the same as TS?

![Screenshot 2019-11-05 at 16 51 05](https://user-images.githubusercontent.com/102334/68218338-d3114580-ffec-11e9-878e-1adf34a24e13.png)

**Comment by chemzqm** [comment]
It's expected hint, read doc of configurations you can use

**Comment by expelledboy** [comment]
Thanks of the quick reply.

@chemzqm This is in a vanilla javascript file, using the default configuration of the plugin, giving you type errors. Surely this cant be expected?

By docs you mean the README? Apart from disabling linting in javascript files I don't see how to prevent typescript linting occurring on vanilla js files.

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc-tsserver#configuration-options

and `:h coc-configuration`

**Comment by expelledboy** [comment]
Okay I have looked at every setting. How do I get rid of these irrelevant messages when coding in vanilla javascript. I still want the code completion of TS, but not see these messages.

Looking for something like

```
  "tsserver.noLintingJavascript": true,
```

**Comment by expelledboy** [comment]
Wait I think I found it, for anyone else looking: `javascript.validate.enable`
