### ISSUE TITLE
Unable to resolve typescript paths

### ISSUE THREAD

**Issue by mjarrettjohnson** [neoclide/coc-tsserver#9]
When using coc-tsserver in a project that uses typescript paths for importing modules.

i.e. import * as utils from "@my-app/utils"

coc-tsserver is unable to correctly resolve the module.

**Comment by chemzqm** [comment]
Check out https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

**Comment by mjarrettjohnson** [comment]
@chemzqm I have the correct tsconfig set up. The vim lsp plugin works correctly using the typescript language server.

**Comment by chemzqm** [comment]
I can't reproduce, consider provide the verbose log: https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by chemzqm** [comment]
Try update coc-tsserver, I've improved logci of project root path resolve.

**Comment by mjarrettjohnson** [comment]
Hi @chemzqm I have updated the coc-tsserver and I'm still getting errors.

Just to note that the errors take some time (~3 minutes) to appear. I am working on a large typescript monorepo.

**Comment by chemzqm** [comment]
The root path resolve could be wrong for monorepo, I've changed it use workspace root when possible.
You may need to change `coc.preferences.rootPatterns` settings for correct rootPath.

**Comment by mjarrettjohnson** [comment]
I believe the problem is that coc installs all my extensions on a network drive which is different to my project.

Looking at the logs I can see that the tsserver hangs when it tries to use the tsserver located on my working drive and it is only after restarting it that it falls back to using the tsserver in the extensions folder which is located on my network drive. 

I have created an issue in coc.nvim https://github.com/neoclide/coc.nvim/issues/393

**Comment by mjarrettjohnson** [comment]
Ok so moving the extensions installation from the networked drive did not work solve the problem. 

Now what is happening is if the projectRoot uses the monorepo root folder, tsserver hangs on every attempted action. 

If however, the root folder is set to be a sub folder with its own internal tsconfig.json then tsserver correctly functions. 

The above is the reason why the project references were unable to be parsed, as the root folder was being set to the sub folder in the mono repo meaning tsserver could not find the paths that existed outside its current folder. 

So the major issue now is that the tsserver does not process any commands when the correct root project is set.

**Comment by chemzqm** [comment]
I think your need references feature of tsserver, checkout https://github.com/Quramy/lerna-yarn-workspaces-example/blob/master/packages/tsconfig.json.

**Comment by chemzqm** [comment]
OK, I've check VSCode, it doesn't work with monorepo as well.
So it seems bug of tsserver itself.

**Comment by mjarrettjohnson** [comment]
The mono repo is run using nx (https://nrwl.io/) and uses tsconfig in libraries that extend the base tsconfig. 

the individual repo has a tsconfig that looks like
{
  "extends": "../tsconfig.json"
  "compilerOptions": {...},
  "angularCompilerOptions": {...}
}

the main repo has 
{
  "compilerOptions": {...}
  "paths": {
    "sub-repo-name": ["path/to/sub/repo"]
   }
}

When tsserver uses the correct project root all communication with it fails resulting in constant timeouts

the vim-lsp plugin does not have the issues that coc has with the monorepo.

However I would really like to use coc as when it works it is a lot faster and provides more functionality.

Also testing in my current monorepo. Vscode has no issues with the tsconfig's and can correctly find definitions via paths

**Comment by chemzqm** [comment]
I need an example project to reproduce the problem.

**Comment by mjarrettjohnson** [comment]
I just want to say thankyou so much for helping out and being so responsive. I ended up cleaning out node modules globally and tidying up my path and now everything is working. I did this once I realized even vs code was not able to load the tsserver. Thank you so much again! I'm now able to use coc and am absolutely loving it!
