### ISSUE TITLE
Automatically enable for .vue files

### ISSUE THREAD

**Issue by doits** [neoclide/coc-tsserver#94]
I'm sorry if this is just a config option I cannot find, but I  cannot find a way to automatically enable it for `.vue` files.

I can manually enable it in vim by ...

```
$ vim myComponent.vue
:CocList exentions
// scroll to `+ coc-tsserver`
// press enter, now it says `* coc-tsserver`
```

... and it works, but how can I enable it automatically for all my `.vue` files?

I thought there might be some config option to specify file extensions (or similar) but I cannot find it.

**Comment by chemzqm** [comment]
Use vetur

**Comment by nicolnt** [comment]
> Use vetur
@doits did you find any way to make JavaScript language server work within `.vue` files, without the overhead of enabling it like you've mentioned? 
I'm already using `coc-vetur` and it's fine for vue specific stuff. But I am looking for vanillaJS completion within the single file component's `<script>` tag.

**Comment by chemzqm** [comment]
It should work if your filetype if vue.

**Comment by nicolnt** [comment]
> It should work if your filetype if vue.

Is there any way to automatically enforce it as it seems not to be the case for us please?

**Comment by chemzqm** [comment]
coc-tsserver doesn't work with vue files, you need make the filetype to be vue and use coc-vetur.

**Comment by nicolnt** [comment]
> coc-tsserver doesn't work with vue files, you need make the filetype to be vue and use coc-vetur.

Okay so basically with what I can understand `vetur` will not help when it comes to working with plain non-vue specific JavaScript code that is located in a `.vue` file. And that there is no straightforward way to make `tsserver` work alongside `vetur` for this purpose. A workaround is to manually toggle `tsserver` with `:CocList exentions` when one needs to type JavaScript.
