### ISSUE TITLE
How do I disable only typescript-related linting?

### ISSUE THREAD

**Issue by achen0115** [neoclide/coc-tsserver#95]
![image](https://user-images.githubusercontent.com/7344958/68974142-dc48a200-07a4-11ea-8abf-43e7f4911f7a.png)

I can't not hide this warning even after setting:
"typescript.validate.enable": false,
"typescript.suggest.enabled": false,

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc-tsserver#configuration-options
`:h coc-configuration`

**Comment by chemzqm** [comment]
`"typescript.suggestionActions.enabled": false`
