### ISSUE TITLE
Improving configuration documentation

### ISSUE THREAD

**Issue by alextes** [neoclide/coc-tsserver#98]
I'm not exactly sure how to configure tsserver for this plugin. As soon as I figure it out I'll propose how to change the documentation to make it obvious (:

**Comment by fannheyward** [comment]
`:CocConfig` opens `coc-settings.json`, and you can config what you want.

**Comment by chemzqm** [comment]
Use tsconfig.json and jsconfig.json for tsserver.

**Comment by alextes** [comment]
Thanks! but it's not that I can't find it 😅 . I've already found it (:. My point was that it took me more than a couple of seconds to figure out how.

@fannheyward mentions what I was getting at. All those keys under "Configuration Options" can be added as top-level keys.

How about adding under "Configuration Options" at the top that any of the below strings are keys that can be added to `coc-settings.json` on the top level? It would be nice if it was also obvious what values are possible for each key but let's leave that out for now.

**Comment by alextes** [comment]
I guess I'll keep this in my unread list and see about opening a PR. It's low effort, and this doesn't seem to get your attention.

**Comment by alextes** [comment]
Fixed! https://github.com/neoclide/coc-tsserver/commit/4f493d6c35bfef71ec21e8db648bcabda5f9ad21
