### ISSUE TITLE
Auto import module path prefix

### ISSUE THREAD

**Issue by jsnick** [neoclide/coc-tsserver#99]
How to set a prefix of auto-import module path? 
For example, I use `~/` mark for noting project root path like below.
So I want auto-imported module path to have `~/`mark prefix 

```javascript
// tsconfig
{
  ...
  "paths": {
    "~*": [".*"]
  },
  ...
}
```

```typescript
// example code
import { BadRequestError } from '~/src/errors';

throw new BadRequestError();
```

**Comment by chemzqm** [comment]
I don't know if tsserver has such kind of feature, you can ask them there.

**Comment by chemzqm** [comment]
Maybe `typescript.preferences.importModuleSpecifier` could work.
